<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - SANKER EPS -Aishwarya Domde
Creation Date	- Apr 20, 2019 3:20:40 PM  3:00:31 PM 
Project Name	- MLWB 
Module Name		- 
Page			- 
Description		-
Link			-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employee Leave Master</title>
<link href="assets/css/style.css" rel="stylesheet">
<link href="assets/plugins/switchery/switchery.min.css" rel="stylesheet">
 <!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>
<link rel="stylesheet" type="text/css"href="assets/plugins/daterange_new/daterangepicker.css" />
<script type="text/javascript"src="assets/plugins/daterange_new/daterangepicker.js"></script>
<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Data Parsley [ OPTIONAL ]-->
<script src="assets/plugins/parsley/parsley.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Jquery Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>
<script src="assets/plugins/switchery/switchery.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<link href="assets/plugins/pretty-checkbox/pretty-checkbox.min.css" rel="stylesheet">
<script src="assets/js/focusOnEnter.js"></script>
<!--Tabbable JS -->
<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<style>
.LblImp:after{
	content:"*";
	color:red;
}
th.sorting {
    text-align: center;
}
#EditEmpFamilyDet>tbody>tr>td>input {
    width: 100%;
}
</style>
<script type="text/javascript">
let global_EmpLeaveId  = 0;
let op_flag = "N";
let showForm = false;
let showTable = true;
let formValidator=null;
$(document).ready(function() {	
	$('.showTableDiv').show(); 
	$('.showFormDiv').hide();
	LoadListTbl();
	validateForm();
	$("#leaveType").alphanum();
	$("#leaveName").alphanum();
	$("#fromDate").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#toDate").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#workingDays").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#leaveQuotaYr").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#maxLeavesBalance").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#workDayForLeave").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#maxEncashBalance").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#leaveQuotaMax").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#maxLeaveTransfer").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#dedSalPerLeave").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#fromDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 }); 
	$("#toDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 }); 
	$("select").select2({
		placeholder:"Select",
		width:'100%',
		multiple:false,
		allowClear:true,		
	});
	/*********************************************************************/
	$('form').find('input').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	$('.select2-container').tooltipster({
	    functionInit: function(instance, helper){
	        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
	        instance.content(content);
	    },
	    delay: 100,
	    theme: 'tooltipster-punk',
	    side: 'bottom'
	});
	/*********************************************************************/
	$('form').on('keyup change paste blur select2:close', 'input, select, textarea, button, a', function(event){
		let elem = event.target;
		let elValid = false;
		if (!$(elem).valid()) {
			elValid = true;
	    }
	    $('.mandatory').each(function() {
	    	if ($(this).val()=='' || $(this).val()==null) {
				elValid = true;
	        }
	    });
	    if (elValid) {
	    	$('.submitBtnName').attr('disabled', 'disabled');
	    } else {
	    	$('.submitBtnName').removeAttr('disabled');
	    	
	    }
	});
	/*********************************************************************/
	$.ajax({  
	    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
	    data : JSON.stringify({
			"param" : "null",
			"sqlMstId" :200
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(response){
	    	let resp = JSON.parse(response["codeList"])
	    	$("#cForwardMstId").append('<option value="">Select cForwardMstId</option>');
	    	$.each(resp, function(key,value) {
					nKey = parseInt(key)+1;
					$("#cForwardMstId").append('<option value="'+resp[key].leave_mst_id+'"> '+resp[key].leave_name+'');
			}); 
	      },
	 });
	 /******************************************************************/
	 $("#SaveLeaveMaster").on("click",function(){
		 if($("#LeaveMaster").valid()){
				let postParameters = {
				opFlag	  			: op_flag,
				userId				: $("#userId").val(),
				branchMstId			: $("#branchMstId").val(),
	            LeaveId    			: global_EmpLeaveId,
				leaveType		 	: $("#leaveType").val(),
				leaveName			: $("#leaveName").val(),
				fromDate			: $("#fromDate").val(),
				toDate				: $("#toDate").val(),
				workingDays			: $("#workingDays").val(),
				leaveQuotaYr		: $("#leaveQuotaYr").val(),
				maxLeavesBalance	: $("#maxLeavesBalance").val(),
				workDayForLeave		: $("#workDayForLeave").val(),
				leaveAllocateFreq	: $("#leaveAllocateFreq").val(),
				holidayAsLeave		: $("#holidayAsLeave").val(),
				Encashment			: $("#Encashment").val(),
				maxEncashBalance	: $("#maxEncashBalance").val(),
				cForward			: $("#cForward").val(),
				cForwardMstId		: $("#cForwardMstId").val(),
				leaveQuotaMax		: $("#leaveQuotaMax").val(),
				maxLeaveTransfer	: $("#maxLeaveTransfer").val(),
				dedSalPerLeave		: $("#dedSalPerLeave").val(),
				ltcAppliFlag		: $("#ltcAppliFlag").val(),
				defaultFlag         : $("#defaultFlag").val(),
				Attendance_Type     : $("#Attendance_Type").val(),
				AttendFlag          : $("#AttendFlag").val(),
				leaveFlag           : $("#leaveFlag").val(),
				ServiceBookFlg      : $("#ServiceBookFlg").val()
								
			}
			console.log(postParameters)
			if(op_flag=="D"){
				$.confirm({
	                title: 'Are you sure want to delete ?',
	                content: '',
	                type: 'blue',
	                buttons: {
			            Delete: {			              
			                action: function () {
			                   deleteRecord(postParameters);
			                }
			            },
			            Cancel: {
			                keys: ['N'],
			                action: function () {
			                	$('.showFormDiv').hide();
			                    $('.showTableDiv').show();
			                }
			            },
			        }
	            }); 
			}else if(op_flag=="M" || op_flag=="N"){
				$.ajax({
					url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/EmpLeaveMaster/SaveEmpLeaveMaster",
					data : JSON.stringify(postParameters),
					method : "post",
					dataType : "json",
					contentType : "application/json",
					success : function(res) {
					 	if (JSON.parse(res["responseObj"]).status == "success") {
				         	toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
				            closeButton: true,
				            positionClass: 'toast-bottom-right'
				          });
				          showForm = true;
				          EnableInputs();
				          LoadListTbl();
				          resetForm();
				          DisableInputs()
				        } else {
				          	toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
				            closeButton: true,
				            positionClass: 'toast-top-right'
				          });
				        }
					}
				});
			}
		 }
	 });
})
/**********************************************************************/
function deleteRecord(postParameters){
	$.ajax({
		url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/EmpLeaveMaster/SaveEmpLeaveMaster",
		data : JSON.stringify(postParameters),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		success : function(res) {
		 	if (JSON.parse(res["responseObj"]).status == "success") {
	          toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
	            closeButton: true,
	            positionClass: 'toast-bottom-right'
	          });
	          resetForm();
	          LoadListTbl();
	        } else {
	          toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
	            closeButton: true,
	            positionClass: 'toast-bottom-right'
	          });
	        }
		}
	});
}
/*************************Document Ready over function starts Reset Settings*************************/
function resetForm(){
	$("#leaveType").val("");
	$("#leaveName").val("");
	$("#fromDate").val("");
	$("#toDate").val("");
	$("#workingDays").val("");
	$("#leaveQuotaYr").val("");
	$("#maxLeavesBalance").val("");;
	$("#workDayForLeave").val("");
	$("#leaveAllocateFreq").val("").trigger('change');
	$("#holidayAsLeave").val("").trigger('change');
	$("#Encashment").val("").trigger('change');
	$("#maxEncashBalance").val("");
	$("#cForward").val("").trigger('change');
	$("#cForwardMstId").val("").trigger('change');
	$("#leaveQuotaMax").val("");
	$("#maxLeaveTransfer").val("");
	$("#dedSalPerLeave").val("");
	$("#ltcAppliFlag").val("").trigger('change');
	$("#defaultFlag").val("").trigger('change');    
	$("#Attendance_Type").val("").trigger('change');
	$("#AttendFlag").val("").trigger('change');
	$("#leaveFlag").val("").trigger('change');     
	$("#ServiceBookFlg").val("").trigger('change');     
	let global_EmpLeaveId  = 0;
	let op_flag = "N";
	formValidator.resetForm();
}
/******************************Disable Fields**********************************************/
 function DisableInputs(){
	 $("#leaveType").attr('disabled', 'disabled');
	 $("#leaveName").attr('disabled', 'disabled');
	 $("#fromDate").attr('disabled', 'disabled');
	 $("#toDate").attr('disabled', 'disabled');
	 $("#workingDays").attr('disabled', 'disabled');
	 $("#leaveQuotaYr").attr('disabled', 'disabled');
	 $("#maxLeavesBalance").attr('disabled', 'disabled');
	 $("#workDayForLeave").attr('disabled', 'disabled');
	 $("#leaveAllocateFreq").attr('disabled', 'disabled');
	 $("#holidayAsLeave").attr('disabled', 'disabled');
	 $("#Encashment").attr('disabled', 'disabled');
	 $("#maxEncashBalance").attr('disabled', 'disabled');
	 $("#cForward").attr('disabled', 'disabled');
	 $("#cForwardMstId").attr('disabled', 'disabled');
	 $("#leaveQuotaMax").attr('disabled', 'disabled');
	 $("#maxLeaveTransfer").attr('disabled', 'disabled');
	 $("#dedSalPerLeave").attr('disabled', 'disabled');
	 $("#ltcAppliFlag").attr('disabled', 'disabled');
}
/******************************Disable Fields**********************************************/
 function EnableInputs(){
	 $("#leaveType").removeAttr('disabled');
	 $("#leaveName").removeAttr('disabled');
	 $("#fromDate").removeAttr('disabled');
	 $("#toDate").removeAttr('disabled');
	 $("#workingDays").removeAttr('disabled');
	 $("#leaveQuotaYr").removeAttr('disabled');
	 $("#maxLeavesBalance").removeAttr('disabled');
	 $("#workDayForLeave").removeAttr('disabled');
	 $("#leaveAllocateFreq").removeAttr('disabled');
	 $("#holidayAsLeave").removeAttr('disabled');
	 $("#Encashment").removeAttr('disabled');
	 $("#maxEncashBalance").removeAttr('disabled');
	 $("#cForward").removeAttr('disabled');
	 $("#cForwardMstId").removeAttr('disabled');
	 $("#leaveQuotaMax").removeAttr('disabled');
	 $("#maxLeaveTransfer").removeAttr('disabled');
	 $("#dedSalPerLeave").removeAttr('disabled');
	 $("#ltcAppliFlag").removeAttr('disabled');
 }
 /**********************************Validate Form*************************************/
 function validateForm(){
 	formValidator = $("#LeaveMaster").validate({
         rules: {
        	 "leaveName": {required: true},
        	 "leaveType": {required: true},
         	},
         messages: {
         	"leaveName": {required: "Please select Leave Name"},
         	"leaveType": {required: "Please select Leave Name"},
          },
         highlight: function (element, errorClass, validClass) {
         	if($(element).hasClass('mandatory')){
         		var elem = $(element);
                 elem.addClass(errorClass);
                 elem.siblings('.select2-container').addClass(errorClass); 
         	}
         },    
         unhighlight: function (element, errorClass, validClass) {
               var elem = $(element);
               elem.removeClass(errorClass);
               elem.siblings('.select2-container').removeClass(errorClass);
               elem.siblings('small').empty();
         },
         errorPlacement: function(error, element) {
             $(element).siblings('small').empty().html(error);
          },
         submitHandler: function (form) {
         	e.preventDefault(e);
             return false; 
         }
     });
 }
 /*************************************Toggle table and Form*********************************************/
 function toggleTableAndForm(flag, empMstId) {
 	if (showForm) {
 		showForm = false;
 		showTable = true;
 		$('.showTableDiv').show();
 		$('.showFormDiv').hide();
 	} else {
 		if (flag == 'M') {
 			$("#ResetLeaveMaster").hide();
 			$('.formTitle').html('Update  Employee Master');
 			$('.submitBtnName').html('<i class="fa fa-save"></i> Update Employee Master ');
 			op_flag = "M";	
 			EnableInputs(); 			
 			setFormData(empMstId);
 		}
 		if (flag == 'N') {	
 			$("#ResetLeaveMaster").show();	
 			$('.formTitle').html('Create New Employee Master ');
 			$('.submitBtnName').html('<i class="fa fa-save"></i> Save Employee Master ');
 			$('.submitBtnName').attr('disabled', 'disabled');
 			EnableInputs(); 			
 			resetForm();
     		$('.showTableDiv').show();
 		}
 		if (flag == 'D') {
 			$("#ResetLeaveMaster").hide();
 			$('.formTitle').html('<i class="fa fa-save"></i> Delete  Employee Master');
 			$('.submitBtnName').html('Delete Employee Master ');
 			op_flag = "D"; 			
 			setFormData(empMstId);
 			DisableInputs();	
 		}
 		showForm = true;
 		showTable = false;
 		$('.showTableDiv').hide();
 		$('.showFormDiv').show();
 	}	
 }
 /*******************************Loading List For Modify and Delete*****************************/
function LoadListTbl(){
	 $.ajax({
			url: "${pageContext.request.contextPath}/app/common/getCodeList",
			data : JSON.stringify({
				"param" : "null",
				"sqlMstId" :200
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
	        success: function (resp) {
	       	 	if ($.fn.DataTable.isDataTable('#detailList')) {
	                $('#detailList').DataTable().destroy();
	            }
	            $("#detailList tbody").empty();
	        	RespEmpLeaveMasterList = JSON.parse(resp["codeList"]);
	        	let datacourt=[];
	        	let keyVal=0;
	        	 $.each(RespEmpLeaveMasterList, function (key,i) {
	        		keyVal=keyVal+1;
	     			datacourt.push([keyVal,RespEmpLeaveMasterList[key]['leave_name'],RespEmpLeaveMasterList[key]['leave_type'],
	   				'<a href="javascript:;" onclick="toggleTableAndForm(\'M\',\''+RespEmpLeaveMasterList[key]['leave_mst_id']+'\')" class="btn btn-primary btn-sm btn-round" title="Edit">'+
	                '<i class="fa fa-pencil"style="padding: 5px;"></i>'+
		            '</a>&nbsp;'+
		            '<a href="javascript:;" onclick="toggleTableAndForm(\'D\',\''+RespEmpLeaveMasterList[key]['leave_mst_id']+'\')" class="btn btn-danger btn-sm btn-round" title="Delete">'+
		            '<i class="fa fa-trash" style="padding: 5px;"></i>'+
		            '</a>']);        		
	        	 });
	        	 $('#detailList').DataTable({
	                 data: datacourt,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageLength: 10,
	                 "bLengthChange": false,
	                 info: false,
	                 scrollCollapse: true,
	                 responsive: true,
	                 "columnDefs": [
	                     {
	                         "className": "text-center",
	                         "targets": [0,3]
	                     } 
	                    ]
	             });
			},
			failure : function() {
				console.log("failed to load list.");
			}		
		});
}
/**********************Setting for Modify**************/
function setFormData(RespEmpLeaveMasterId){
	$.each(RespEmpLeaveMasterList, function (key,i) {
		if(RespEmpLeaveMasterList[key]['leave_mst_id']==RespEmpLeaveMasterId){
			global_EmpLeaveId=RespEmpLeaveMasterId;
			$("#ltcAppliFlag").val(RespEmpLeaveMasterList[key]['ltc_appli_flag']).trigger('change');
			$("#leaveName").val(RespEmpLeaveMasterList[key]['leave_name']);
			$("#maxLeavesBalance").val(RespEmpLeaveMasterList[key]['max_leaves_balance']);
			$("#workDayForLeave").val(RespEmpLeaveMasterList[key]['work_day_for_leave']).trigger('change');
			$("#leaveQuotaYr").val(RespEmpLeaveMasterList[key]['leave_year']);
			$("#leaveAllocateFreq").val(RespEmpLeaveMasterList[key]['quota_allot_frq']).trigger('change');
			$("#workingDays").val(RespEmpLeaveMasterList[key]['working_days']);
			$("#holidayAsLeave").val(RespEmpLeaveMasterList[key]['holiday_as_leave']).trigger('change');
			$("#maxEncashBalance").val(RespEmpLeaveMasterList[key]['max_encash_balance']);
			$("#Encashment").val(RespEmpLeaveMasterList[key]['encash']).trigger('change');
			$("#leaveType").val(RespEmpLeaveMasterList[key]['leave_type']);
			$("#cForward").val(RespEmpLeaveMasterList[key]['c_forward']).trigger('change');
			$("#cForwardMstId").val(RespEmpLeaveMasterList[key]['c_forward_mst_id']).trigger('change');
			$("#leaveQuotaMax").val(RespEmpLeaveMasterList[key]['leave_quota_max']);
			$("#defaultFlag").val(RespEmpLeaveMasterList[key]['default_flag']).trigger('change');  
			$("#maxLeaveTransfer").val(RespEmpLeaveMasterList[key]['max_leave_transfer']);
			$("#Attendance_Type").val(RespEmpLeaveMasterList[key]['attendance_type']).trigger('change');
			$("#dedSalPerLeave").val(RespEmpLeaveMasterList[key]['ded_sal_per_leave']);  
			$("#AttendFlag").val(RespEmpLeaveMasterList[key]['attendance_flag']).trigger('change');
			$("#fromDate").val(RespEmpLeaveMasterList[key]['from_date']);
			$("#leaveFlag").val(RespEmpLeaveMasterList[key]['leave_flag']).trigger('change'); 
			$("#toDate").val(RespEmpLeaveMasterList[key]['to_date']);    
			$("#ServiceBookFlg").val(RespEmpLeaveMasterList[key]['service_book_flag']).trigger('change');     
		}
	});
}
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptId" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<div class="row showTableDiv">
	<div class="col-lg-12">
		<div class="panel newPanel">
			<div class="panel-heading">
				<div class="panel-control">
					<button class="btn btn-default" data-click="panel-expand">
						<i class="fa fa-expand"></i>
					</button>
					<button class="btn btn-default" data-click="panel-reload" onclick="loadListOfLocation();">
						<i class="fa fa-refresh"></i>
					</button>
					<button class="btn btn-default" data-click="panel-collapse">
						<i class="fa fa-chevron-down"></i>
					</button>
					 <button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
					<button onclick="toggleTableAndForm('N',null)" class="btn btn-info">
						<i class="fa fa-plus"></i> Add New
					</button>
				</div>
				<h3 class="panel-title">Employee Leave Master</h3>
			</div>
			<div class="panel-body">		
				<table class="table table-striped table-bordered table-hover locationMasterTable table-responsive" id="detailList">
					<thead>
						<tr>
							<th>Sr. No.</th>
							<th>Leave Name </th>
							<th>Leave Type</th>	
							<th>Action</th>													
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>								
			</div>
		</div>
	</div>
</div>
<!------------------------------------------------------------>
<div class="row showFormDiv">
	<div class="col-lg-12">
		<form id="LeaveMaster">
			<div class="panel newpanel">
				<div class="panel-heading">
					<div class="panel-control">
						<button class="btn btn-default" data-click="panel-expand">
							<i class="fa fa-expand"></i>
						</button>
						<button class="btn btn-default" data-click="panel-reload">
							<i class="fa fa-refresh"></i>
						</button>
						<button class="btn btn-default" data-click="panel-collapse">
							<i class="fa fa-chevron-down"></i>
						</button>
						<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()">
							<i class="fa fa-times"></i>
						</button>
						<button onclick="toggleTableAndForm('N',null);" type="button" class="btn btn-success">
						<i class="fa fa-chevron-left"></i>&nbsp; Back to List </button>
					</div>
					<h3 class="panel-title formTitle"> Create New Employee Leave Master </h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
								<label for="leaveType" class="control-label LblImp">
									<spring:message code="label.leaveType"></spring:message>
								</label>
								<input name="leaveType" type="text" class="form-control mandatory" data-toggle="tooltip" name="leaveType"
								 placeholder="Enter <spring:message code="label.leaveType"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="3"  id="leaveType" required ><small style=color: red></small>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="leaveName" class="control-label LblImp">
									<spring:message code="label.leaveName"></spring:message>
								</label>
								<input name="leaveName" type="text" class="form-control mandatory" data-toggle="tooltip" name="leaveName"
								 placeholder="Enter <spring:message code="label.leaveName"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="50"  id="leaveName" required ><small style=color: red></small>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<div class="form-group has-feedback">	
									<label for="fromDate" class="control-label">
										<spring:message code="label.fromDate"></spring:message></label>
									<input name="fromDate" type="text" class="form-control hasDatepic" data-toggle="tooltip" id="fromDate"
									 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.fromDate"></spring:message>">
									<span class="fa fa-calendar fa-lg form-control-feedback"></span>
								</div>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<div class="form-group has-feedback">	
									<label for="toDate" class="control-label">
										<spring:message code="label.toDate"></spring:message></label>
									<input name="toDate" type="text" class="form-control hasDatepic" data-toggle="tooltip" id="toDate"
									 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.toDate"></spring:message>">
									<span class="fa fa-calendar fa-lg form-control-feedback"></span>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
								<label for="workingDays" class="control-label">
									<spring:message code="label.workingDays"></spring:message>
								</label>
								<input name="workingDays" type="text" class="form-control " data-toggle="tooltip" name="workingDays"
								 placeholder="Enter <spring:message code="label.workingDays"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="5"  id="workingDays"  >
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="leaveQuotaYr" class="control-label">
									<spring:message code="label.leaveQuotaYr"></spring:message>
								</label>
								<input name="leaveQuotaYr" type="text" class="form-control " data-toggle="tooltip" name="leaveQuotaYr"
								 placeholder="Enter <spring:message code="label.leaveQuotaYr"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10"  id="leaveQuotaYr"  >
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="maxLeavesBalance" class="control-label">
									<spring:message code="label.maxLeavesBalance"></spring:message>
								</label>
								<input name="maxLeavesBalance" type="text" class="form-control " data-toggle="tooltip" name="maxLeavesBalance"
								 placeholder="Enter <spring:message code="label.maxLeavesBalance"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10"  id="maxLeavesBalance"  >
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="workDayForLeave" class="control-label">
									<spring:message code="label.workDayForLeave"></spring:message>
								</label>
								<input name="workDayForLeave" type="text" class="form-control " data-toggle="tooltip" name="workDayForLeave"
								 placeholder="Enter <spring:message code="label.workDayForLeave"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10"  id="workDayForLeave"  >
							</div>
						</div>
					</div>	
					<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
								<label for="leaveAllocateFreq" class="control-label">
									<spring:message code="label.leaveAllocateFreq"></spring:message></label>
								<select name="leaveAllocateFreq" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.leaveAllocateFreq"></spring:message>"  id="leaveAllocateFreq">
									<option value="12"> Yearly </option>
									<option value="6"> Half Yearly </option>
									<option value="3"> Quaterly </option>
									<option value="0"> NA </option>
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="holidayAsLeave" class="control-label">
									<spring:message code="label.holidayAsLeave"></spring:message></label>
								<select name="holidayAsLeave" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.holidayAsLeave"></spring:message>" id="holidayAsLeave">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="Encashment" class="control-label">
									<spring:message code="label.Encashment"></spring:message></label>
								<select name="Encashment" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.Encashment"></spring:message>"  id="Encashment">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="maxEncashBalance" class="control-label">
									<spring:message code="label.maxEncashBalance"></spring:message>
								</label>
								<input name="maxEncashBalance" type="text" class="form-control " data-toggle="tooltip" name="maxEncashBalance"
								 placeholder="Enter <spring:message code="label.maxEncashBalance"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10"  id="maxEncashBalance"  >
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
								<label for="cForward" class="control-label">
									<spring:message code="label.cForward"></spring:message></label>
								<select name="cForward" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.cForward"></spring:message>"  id="cForward">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="cForwardMstId" class="control-label">
									<spring:message code="label.cForwardMstId"></spring:message></label>
								<select name="cForwardMstId" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.cForwardMstId"></spring:message>"  id="cForwardMstId">
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="leaveQuotaMax" class="control-label">
									<spring:message code="label.leaveQuotaMax"></spring:message>
								</label>
								<input name="leaveQuotaMax" type="text" class="form-control " data-toggle="tooltip" name="leaveQuotaMax"
								 placeholder="Enter <spring:message code="label.leaveQuotaMax"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10"  id="leaveQuotaMax"  >
							</div>
						</div>
						<div class="col-sm-3">
								<div class="form-group">
								<label for="maxLeaveTransfer" class="control-label">
									<spring:message code="label.maxLeaveTransfer"></spring:message>
								</label>
								<input name="maxLeaveTransfer" type="text" class="form-control " data-toggle="tooltip" name="maxLeaveTransfer"
								 placeholder="Enter <spring:message code="label.maxLeaveTransfer"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10" id="maxLeaveTransfer"  >
							</div>
						</div>
					</div>	
					<div class="row">
						<div class="col-sm-3">
								<div class="form-group">
								<label for="dedSalPerLeave" class="control-label">
									<spring:message code="label.dedSalPerLeave"></spring:message>
								</label>
								<input name="dedSalPerLeave" type="text" class="form-control " data-toggle="tooltip" name="dedSalPerLeave"
								 placeholder="Enter <spring:message code="label.dedSalPerLeave"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="10" id="dedSalPerLeave"  >
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="ltcAppliFlag" class="control-label">
									<spring:message code="label.ltcAppliFlag"></spring:message></label>
								<select name="ltcAppliFlag" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.ltcAppliFlag"></spring:message>" id="ltcAppliFlag">
								  	
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="defaultFlag" class="control-label">
									<spring:message code="label.defaultFlag"></spring:message></label>
								<select name="defaultFlag" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.defaultFlag"></spring:message>" id="defaultFlag">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="Attendance_Type" class="control-label">
				  					<spring:message code="label.Attendance_Type"></spring:message></label>
								<select name="Attendance_Type" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.Attendance_Type"></spring:message>" id="Attendance_Type">
								  	<option value="ABD"	>ABD </option>
									<option value="HFD" >HFD </option>
									<option value="HPLD">HPLD</option>
									<option value="HYD" >HYD </option>
									<option value="PLD" >PLD </option>
									<option value="PRD" >PRD </option>
									<option value="TRD" >TRD </option>
								</select>
							</div>
						</div>
					</div>	
					<div class="row">
						<div class="col-sm-3">
							<div class="form-group">
								<label for="AttendFlag" class="control-label">
									<spring:message code="label.AttendFlag"></spring:message></label>
								<select name="AttendFlag" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.AttendFlag"></spring:message>" id="AttendFlag">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>						
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="leaveFlag" class="control-label">
									<spring:message code="label.leaveFlag"></spring:message></label>
								<select name="leaveFlag" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.leaveFlag"></spring:message>" id="leaveFlag">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>						
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="ServiceBookFlg" class="control-label">
									<spring:message code="label.ServiceBookFlg"></spring:message></label>
								<select name="ServiceBookFlg" class="form-control Advocate" data-toggle="tooltip"  
								  title="Select <spring:message code="label.ServiceBookFlg"></spring:message>" id="ServiceBookFlg">
								  	<option value="Y"> Yes </option>
									<option value="N"> No </option>
								</select>
							</div>
						</div>
					</div>		
					<hr>
					<button  class="btn btn-primary submitBtnName" type="button" id="SaveLeaveMaster">
					 <i class="fa fa-save"></i>Save Employee Leave Master
					</button>
					&nbsp;
					<button type="button" class="btn resetBtnName btn-danger" id="ResetLeaveMaster" onclick="resetForm()">
					Reset
					</button>						
				</div>
			</div>
		</form>
	</div>
</div>
</body>
<script src="assets/js/validation.js"></script>
</html>