<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - Aishwarya Domde
Creation Date	- Jun 27, 2019 3:45:19 PM
Project Name	- MLWB 
Module Name		- 
Page\Class\etc... Name -: Employee Leave Allotment
Description	-
Link		-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employee Leave Allotment</title>
<link href="assets/css/style.css" rel="stylesheet">
<link href="assets/plugins/switchery/switchery.min.css" rel="stylesheet">
 <!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>
<link rel="stylesheet" type="text/css"href="assets/plugins/daterange_new/daterangepicker.css" />
<script type="text/javascript"src="assets/plugins/daterange_new/daterangepicker.js"></script>
<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Data Parsley [ OPTIONAL ]-->
<script src="assets/plugins/parsley/parsley.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Jquery Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>
<script src="assets/plugins/switchery/switchery.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<link href="assets/plugins/pretty-checkbox/pretty-checkbox.min.css" rel="stylesheet">
<script src="assets/js/focusOnEnter.js"></script>
<!--Tabbable JS -->
<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<style>
.textMY{
	width:45px !important;
}
.LblImp:after{
	content:"*";
	color:red;
}
</style>
<script type="text/javascript">
let global_LeaveAllotId  = 0;
let op_flag = "N";
let showForm = false;
let showTable = true;
let formValidator=null;
let branchId = $("#branchMstId").val();
var myDate = new Date();
var TodaySet = myDate.getDate() + '/' +(myDate.getMonth()+1) + '/' +myDate.getFullYear();
$(document).ready(function() {	
	$("#sancDate").val(TodaySet);
	var table ;
	$('.showTableDiv').show(); 
	$('.showFormDiv').hide();
	LoadList();
	validateForm();
	$("select").select2({
		placeholder:"Select",
		width:'100%',
		multiple:false,
		allowClear: false,		
	});
	$("#startDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	      minDate:'0'
	 }); 
	$("#EndDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate:'0'
	 });
	$("#sancDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate:'0'
	 });
	 /******************************************************************/
	$('form').find('input,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	$('.select2-container').tooltipster({
	     functionInit: function(instance, helper){
		       var content = $(helper.origin).closest('.form-group').find('select').attr("title");
		        instance.content(content);
		    }, 
		    delay: 100,
		    theme: 'tooltipster-punk',
		    side: 'bottom'
		}); 
	/*********************************************************************/
	$('form').on('keyup change paste blur select2:close', 'input, select, textarea, button, a', function(event){
		let elem = event.target;
		let elValid = false;
		if (!$(elem).valid()) {
			elValid = true;
	    }
	    $('.mandatory').each(function() {
	    	if ($(this).val()=='' || $(this).val()==null) {
				elValid = true;
	        }
	    });
	    if (elValid) {
	    	$('.submitBtnName').attr('disabled', 'disabled');
	    } else {
	    	$('.submitBtnName').removeAttr('disabled');
	    }
	});	
	/************************Getting List for Leave Types *****************/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getHelpList",//getHelpList==branchMstId
		data : JSON.stringify({
		"param" :"PLEAVEHELP~"
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(respp){
	    	resp = (respp["helpList"]);
	    	$("#leaveType").empty().append("<option></option>");
	    	$.each(resp, function(key,value) {
	    	    if(resp[key].prop8=="Y" && resp[key].prop4>0){
				nKey = parseInt(key)+1;
				console.log('<option value="'+resp[key].prop2+'"> '+resp[key].prop3)
				$("#leaveType").append('<option value="'+resp[key].prop2+'"> '+resp[key].prop3);
	    	    }
			}); 
	      },
	 });
   /******************Adding Leave Year Selection*******************/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getCodeList",
	    type:'post',  
	    dataType:'json',
	    data : JSON.stringify({
	    	sqlMstId : "426",
	    	param : "null"
	    }),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(resp){
	    	resp =JSON.parse(resp["codeList"]);
	    	$("#leaveYear").empty().append("<option></option>");
	    	$.each(resp, function(key,value) {
					nKey = parseInt(key)+1;
					$("#leaveYear").append("<option rel1='"+resp[key].from_dt+"' rel2='"+resp[key].to_dt+"' rel3='"+resp[key].finyr_code+"' value='"+resp[key].finyr_id+"'>"+resp[key].finyr_code+"</option>");
				}); 	
	      },
	 });
	 /***************Adding Sanction Employee Name******************/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getCodeList",
	    type:'post',  
	    dataType:'json',
	    data : JSON.stringify({
	    	sqlMstId : "206",
	    	param : "  null~null~null~null"
	    }),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(resp){
	    	resp =JSON.parse(resp["codeList"]);
	    	$("#sanctionBy").empty().append("<option></option>");
	    	$.each(resp, function(key,value) {
					nKey = parseInt(key)+1;
					$("#sanctionBy").append('<option value="'+resp[key].employee_mst_id+'"> '+resp[key].employee);
			}); 	
	      },
	 });
	 /*********************************************************/
	 $("#leaveType,#leaveYear,#tranTypeId").on("change",function(){
			var LeaveType =$("#leaveType").val();
			var LeaveYear =$("#leaveYear").val();
			var TranType  =$("#tranTypeId").val();
			if((op_flag =="N" )&&(LeaveType!="") && (LeaveYear!="") && (TranType!="")){
				 NewEmployeList()
			}
			else if((op_flag =="M" )&&(LeaveType!="") && (LeaveYear!="") && (TranType!="")){
				ModifyEmployeList()
			}
			else if((op_flag =="D" )&&(LeaveType!="") && (LeaveYear!="") && (TranType!="")){
				ModifyEmployeList()
			}
	})
	 /************On change of leaveType add Yearly Quota*************/
	$("#leaveType").on("change",function(){
			$.ajax({  
				url : "${pageContext.request.contextPath}/app/common/getCodeList",
			    type:'post',  
			    dataType:'json',
			    data : JSON.stringify({
			    	sqlMstId : "200",
			    	param :$("#leaveType").val()
			    }),
				method : "post",
				dataType : "json",
				contentType : "application/json",
				async: false,
			    success: function(resp){
			    	resp =JSON.parse(resp["codeList"]);
			    	$("#yearlyquota").val(resp[0].leave_year);
			      },
			 });
		});
	 /************On change of leaveType add Yearly Quota*************/
	$("#leaveYear").on("change",function(){
			$.ajax({  
				url : "${pageContext.request.contextPath}/app/common/getCodeList",
			    type:'post',  
			    dataType:'json',
			    data : JSON.stringify({
			    	sqlMstId : "107",
			    	param :  '1~22', 
			    }),
				method : "post",
				dataType : "json",
				contentType : "application/json",
				async: false,
			    success: function(resp){
			    	resp =JSON.parse(resp["codeList"]);
			      },
			 });
		})
	 /************************After setting *******************/
	 $("#leaveYear").on("change",function(){
		$("#startDate").val($("#leaveYear option:selected" ).attr("rel1"));
		$("#EndDate").val($("#leaveYear option:selected" ).attr("rel2"))
	});
	/***********************************************************/
	$(".showFormDiv").on('change',"input[type=checkbox]",function(){
		if(op_flag=="M"){
				if($(this).is(":checked")){
					$(this).attr("flag-Active","Y");
					$(this).attr("flag-Delete","N");
					
				}else{
					$(this).attr("flag-Active","N");
					$(this).attr("flag-Delete","Y");

					}
		}		
	});
	 /************************CRUD Opertion**********************/
	 $("#SaveLeaveAllot").on("click",function(){
		 if($("#LeaveAllot").valid()){
			 var tblListLength 		 = $("#OverView tbody>tr").length;
			 var Arr_employee_mst_id = [];
			 var Arr_flag1			 = [];	
			 var Arr_flag2			 = [];	
			 var Arr_tranTypeId		 = [];		
			 var crdr_flag			 = "C";	
			 var flag1			 	 = "Y";
			 var LeaveYrQuota		 = [];
			 var Arr_leave_mstId 	 = [];
			 var count=0;
			 if(op_flag=="N"){
				 $('#OverView>tbody>tr').each(function() {
						$(this).find('td:eq(4)').each (function() {
							if($(this).find('input[type=checkbox]').is(":checked")){
								Arr_tranTypeId.push($('#tranTypeId').val());
								
								Arr_leave_mstId.push($(this).closest('tr').find("td:eq(0)>input").val());							
								LeaveYrQuota.push($(this).closest('td').prev('td').find('input[type=text]').val());
								Arr_employee_mst_id.push($(this).find('input[type=checkbox]').val());
								Arr_flag1.push($(this).find('input[type=checkbox]').attr("flag-Active"));
								Arr_flag2.push($(this).find('input[type=checkbox]').attr("flag-Delete"));
								count++;
				          }
					});
				});	
			}else if (op_flag=="M"||op_flag=="D"){
				 $('#OverView>tbody>tr').each(function() {
						$(this).find('td:eq(4)').each (function() {
						Arr_tranTypeId.push($('#tranTypeId').val());
						Arr_leave_mstId.push($(this).closest('tr').find("td:eq(0)>input").val());							
						LeaveYrQuota.push($(this).closest('td').prev('td').find('input[type=text]').val());
						Arr_employee_mst_id.push($(this).find('input[type=checkbox]').val());
						Arr_flag1.push($(this).find('input[type=checkbox]').attr("flag-Active"));
						Arr_flag2.push($(this).find('input[type=checkbox]').attr("flag-Delete"));
						count++;
					});
				});	
			}	
			if(count>0){
				let postParameters = {
						/*************Dump data****************/
						Arr_tranTypeId		: Arr_tranTypeId,
						Arr_employee_mst_id	: Arr_employee_mst_id,
						Arr_leave_mstId		: Arr_leave_mstId,
						flag1				: flag1,
						Arr_flag2			: Arr_flag2,
						Arr_flag1			: Arr_flag1,
						crdr_flag			: crdr_flag,
						LeaveYrQuota		: LeaveYrQuota,
						encash_mst_id		: (null),
						leave_batch_no		: (null),
						leave_set_id		: (null),
						reason_code_id		: (null),
						/*******************************/
						leaveType     : $("#leaveType").val(),
						leaveName     : $("#leaveType option:selected").text(),
						leaveYear     : $("#leaveYear").val(),
						issueMonth    : $("#issueMonth").val(),
						tranTypeId    : $("#tranTypeId").val(),
						startDate     : $("#startDate").val(),
						EndDate       : $("#EndDate").val(),
						sanctionBy    : $("#sanctionBy").val(),
						sancDate      : $("#sancDate").val(),
						yearlyquota   : $("#yearlyquota").val(),
						reason        : $("#reason").val(),
						opFlag	  	  : op_flag,
						userId		  : $("#userId").val(),
						branchMstId   : $("#branchMstId").val(),
						LeaveId       : global_LeaveAllotId
			};
			if(op_flag=="D"){
				$.confirm({
	                title: 'Are you sure want to delete ?',
	                content: '',
	                type: 'blue',
	                buttons: {
			            Delete: {			              
			                action: function () {
			                   deleteRecord(postParameters);
			                }
			            },
			            Cancel: {
			                keys: ['N'],
			                action: function () {
			                	$('.showFormDiv').hide();
			                    $('.showTableDiv').show();
			                }
			            },
			        }
	            }); 
			}else if(op_flag=="M" || op_flag=="N"){
				$.ajax({
					url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveTransaction/SaveEmpLeaveAllot",
					data : JSON.stringify(postParameters),
					method : "post",
					dataType : "json",
					contentType : "application/json",
					success : function(res) {
					 	if (JSON.parse(res["responseObj"]).status == "success") {
				         	toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
				            closeButton: true,
				            positionClass: 'toast-bottom-right'
				          });
				          showForm = true;
				          EnableInputs();
				          resetForm();
				          LoadList();
				          DisableInputs();
				        } else {
				          	toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
				            closeButton: true,
				            positionClass: 'toast-top-right'
				          });
				        }
					}
				});
			}
		}else{
          	toastr.error("Select atleast one employee", 'Error', {
	            closeButton: true,
	            positionClass: 'toast-top-right'
	         });
		}			
	 }
  });
});
/**********************************Validate Form*************************************/
function validateForm(){
	formValidator = $("#LeaveAllot").validate({
        rules: {
        	},
        messages: {
        },
        highlight: function (element, errorClass, validClass) {
        	if($(element).hasClass('mandatory')){
        		var elem = $(element);
                elem.addClass(errorClass);
                elem.siblings('.select2-container').addClass(errorClass); 
        	}
        },    
        unhighlight: function (element, errorClass, validClass) {
              var elem = $(element);
              elem.removeClass(errorClass);
              elem.siblings('.select2-container').removeClass(errorClass);
              elem.siblings('small').empty();
        },
        errorPlacement: function(error, element) {
            $(element).siblings('small').empty().html(error);
         },
        submitHandler: function (form) {
        	e.preventDefault(e);
            return false; 
        }
    });
}

/*************************************Toggle table and Form*********************************************/
function toggleTableAndForm(flag, empMstId) {
	if (showForm) {
		showForm = false;
		showTable = true;
		$('.showTableDiv').show();
		$('.showFormDiv').hide();
	} else {
		if (flag == 'M') {
			$("#ResetLeaveAllot").hide();
			$('.formTitle').html('Update Employee Leave Allotment');
			$('.submitBtnName').html('<i class="fa fa-save"></i> Update Employee Leave Allotment ');
// 			EnableInputs();
			resetForm(); 	
			op_flag = "M";	
			setFormData(empMstId); 
			setTimeout(function() {
				$('#OverView').DataTable().columns.adjust().responsive.recalc();
			}, 3); 
		  	$('#OverView').show();
		}
		if (flag == 'N') {	
			$('.formTitle').html('Create New Employee Leave Allotment ');
			$('.submitBtnName').html('<i class="fa fa-save"></i> Save Employee Leave Allotment ');
			$('.submitBtnName').attr('disabled', 'disabled');
// 			EnableInputs(); 
			$("#ResetLeaveAllot").show();		
			resetForm();
    		$('.showTableDiv').show();
		}
		if (flag == 'D') {
			$("#ResetLeaveAllot").hide();
			$('.formTitle').html('<i class="fa fa-save"></i> Delete  Employee Leave Allotment');
			$('.submitBtnName').html('Delete Employee Leave Allotment ');
			op_flag = "D"; 	
			setFormData(empMstId);
			setTimeout(function() {
				$('#OverView').DataTable().columns.adjust().responsive.recalc();
			}, 3); 
		  	$('#OverView').show();
			DisableInputs();
			$("input").attr("disabled","disabled")
			$('.submitBtnName').removeAttr('disabled');
		}
		showForm = true;
		showTable = false;
		$('.showTableDiv').hide();
		$('.showFormDiv').show();
	}		 
}
/**********************Loading List for Table*****************************/
function LoadList(){
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getHelpList",//getHelpList==branchMstId
		data : JSON.stringify({
		"param" :"LEAVE_TRAN~AND L.OP_BRANCH_MST_ID = 11 and coalesce(L.ACTIVE_FLAG,''Y'') = ''Y'' AND coalesce(L.DELETE_FLAG,''N'') = ''N''"
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(respTbl){
	    	if ($.fn.DataTable.isDataTable('#detailList')) {
                $('#detailList').DataTable().destroy();
            }
            $("#detailList tbody").empty();
		    let dataTbl=[];let keyVal=0;	
	    	respTbl1 = (respTbl["helpList"]);
	    	$.each(respTbl1, function (key,i) {				
        		keyVal=keyVal+1;        		
 				dataTbl.push([keyVal,
 	 				respTbl1[key]['prop3'],
 	 				respTbl1[key]['prop5'],
 	 				respTbl1[key]['prop6'],
 	 				'<a href="javascript:;" onclick="toggleTableAndForm(\'M\',\''+respTbl1[key]['prop2']+'\')" class="btn btn-primary btn-sm btn-round" title="Edit">'+
 		            '<i class="fa fa-pencil"style="padding: 5px;"></i>'+
 		            '</a>&nbsp;'+
 		            '<a href="javascript:;" onclick="toggleTableAndForm(\'D\',\''+respTbl1[key]['prop2']+'\')" class="btn btn-danger btn-sm btn-round" title="Delete">'+
 		            '<i class="fa fa-trash" style="padding: 5px;"></i>'+
 		            '</a>'
	 				]) ; 
        		});
	    	 $('#detailList').DataTable({
	                data: dataTbl,
	    	 });   	
	      },
	 });
}
/*******************************************************/
 function setFormData(LeaveId){
	 var ChckSum = []; var ChckSum1=[]; var ChckSum2=[];
	 var leave_mst_id,hr_fin_year_mst_id,issue_month,tran_type,sanction_emp_id;		
	 $.ajax({
			url:"${pageContext.request.contextPath}/app/common/getCodeList",  
			data : JSON.stringify({
	            param :LeaveId+"~null~null~null",
	        	sqlMstId : 206,
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response) {	
			   resp = JSON.parse(response["codeList"]);
		    	$.each(resp, function(key,value) {
		    		global_LeaveAllotId=LeaveId;
		    		$("#startDate").val(resp[key].leave_from_date);
		    		$("#EndDate").val(resp[key].leave_to_date);
		    		$("#yearlyquota").val(resp[key].leave_yr_quota);
		    		$("#reason").val(resp[key].reason);
		    		ChckSum.push(resp[key].employee_mst_id);
		    		ChckSum1.push(resp[key].leave_days);
		    		ChckSum2.push(resp[key].leave_trans_id);
		    		leave_mst_id=resp[key].leave_mst_id;
		    		hr_fin_year_mst_id=resp[key].hr_fin_year_mst_id;
					issue_month=resp[key].issue_month;
					tran_type=resp[key].tran_type;
					sanction_emp_id=resp[key].sanction_emp_id;
		  	 });			  	 				  
		  }
	 });
		for(var i=0;i<(ChckSum.length);i++){
		 	$("input[name='empId"+ChckSum[i]+"']").attr("Flag-value",ChckSum[i]);
		 	$("input[name='YrQuota"+ChckSum[i]+"']").val(ChckSum1[i])
		 	$("input[name='TransTblId"+ChckSum[i]+"']").val(ChckSum2[i])
			$("input[name='empId"+ChckSum[i]+"']").prop("checked",true);
		}

		setTimeout(function(){$("#leaveType").val(leave_mst_id).trigger('change');         },10);
		setTimeout(function(){$("#leaveYear").val(hr_fin_year_mst_id).trigger('change');   },11);
		setTimeout(function(){$("#issueMonth").val(issue_month).trigger('change');         },12);
		setTimeout(function(){$("#tranTypeId").val(tran_type).trigger('change');           },13);
		setTimeout(function(){$("#sanctionBy").val(sanction_emp_id).trigger('change');     },14);
}
/*******************Getting All Employees in Table for New****************************/
 function NewEmployeList(){
	var LeaveType =$("#leaveType").val();
	var LeaveYear =$("#leaveYear").val();
	var TranType  =$("#tranTypeId").val();
	var YrQuota	  =$("#yearlyquota").val();
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getCodeList",
	    type:'post',  
	    dataType:'json',
	    data : JSON.stringify({
	    	sqlMstId : "7255",//416
	    	param : branchId+"~"+LeaveType+"~"+LeaveYear+"~"+TranType
	    }),
	    method : "post",
		dataType : "json",
		async : false,
		contentType : "application/json",
		success : function(resp) {	

	    	if ($.fn.DataTable.isDataTable('#OverView')) {
                $('#OverView').DataTable().destroy();
            }
            $("#OverView tbody").empty();		
			let keyVal=0;	let datacourt=[];
			responList1 =JSON.parse(resp["codeList"]);
			$.each(responList1, function (key,i) {				
        		keyVal=keyVal+1;        		
 				datacourt.push([keyVal+'<input type="hidden" class="form-control" id="TransTblId'+keyVal+'" name="TransTblId'+responList1[key]["id"]+'"  value=0>',
 	 				responList1[key]['name'],
 	 				responList1[key]['desig_name'],'<div class="mb-3">'
 			      	+'<input type="text" class="form-control" id="YrQuota'+keyVal+'" name="YrQuota'+responList1[key]["id"]+'" value='+YrQuota+' style="width: 50px !important;" >'
 			    	+'</div>',
 	 				'<div class="mb-3">'
 			      	+'<input type="checkbox" id="empId'+keyVal+'" name="empId'+responList1[key]["id"]+'" '+
 			      	'value='+responList1[key]["id"]+' flag-Value=0  flag-Active=Y flag-Delete=N>'
 			    	+'</div>'
 	 				]) ; 
        });
		  	$('#OverView').show();	
		table = $('#OverView').DataTable({
                data: datacourt,
                "autoWidth": true,
                deferRender: true, 
                 "scrollY": "200px",
                "scrollCollapse": true,
                "paging": false,
                responsive: true,
                "columnDefs": [
                	{
                        "className": "text-center textMY",
                        "targets": [0]
                    } ,
                   {'targets': 4,'checkboxes': {'selectRow': true} },
                   
	          ],
	          select: {'style': 'multi'},
            });  
		}	
	});
    // Check/uncheck all checkboxes in the table
	 $('#example-select-all').on('click', function(){
	      var rows = table.rows({ 'search': 'applied' }).nodes();
	      $('input[type="checkbox"]', rows).prop('checked', this.checked);
	  });
}
 /*******************Getting All Employees in Table for Modify****************************/
  function ModifyEmployeList(){
 	var LeaveType =$("#leaveType").val();
 	var LeaveYear =$("#leaveYear").val();
 	var TranType  =$("#tranTypeId").val();
 	var YrQuota	  =$("#yearlyquota").val();
 	$.ajax({  
 		url : "${pageContext.request.contextPath}/app/common/getCodeList",
 	    type:'post',  
 	    dataType:'json',
 	    data : JSON.stringify({
 	    	sqlMstId : "7265",//416
 	    	param : branchId+"~"+LeaveType+"~"+LeaveYear+"~"+TranType
 	    }),
 	    method : "post",
 		dataType : "json",
 		async : false,
 		contentType : "application/json",
 		success : function(resp) {	
 	    	if ($.fn.DataTable.isDataTable('#OverView')) {
                 $('#OverView').DataTable().destroy();
             }
             $("#OverView tbody").empty();		
 			let keyVal=0;	let datacourt=[];
 			responList1 =JSON.parse(resp["codeList"]);
 			$.each(responList1, function (key,i) {				
         		keyVal=keyVal+1;        		
  				datacourt.push([keyVal+'<input type="hidden" class="form-control" id="TransTblId'+keyVal+'" name="TransTblId'+responList1[key]["id"]+'"  >',
  	 				responList1[key]['name'],
  	 				responList1[key]['desig_name'],'<div class="mb-3">'
  			      	+'<input type="text" class="form-control" id="YrQuota'+keyVal+'" name="YrQuota'+responList1[key]["id"]+'" style="width: 50px !important;" >'
  			    	+'</div>',
  	 				'<div class="mb-3">'
  			      	+'<input type="checkbox" id="empId'+keyVal+'" name="empId'+responList1[key]["id"]+'" '+
  			      	'value='+responList1[key]["id"]+' flag-Value=0  flag-Active=Y flag-Delete=N>'
  			    	+'</div>'
  	 				]) ; 
         });
 		  	$('#OverView').show();
 		table = $('#OverView').DataTable({
                 data: datacourt,
                 "autoWidth": true,
                 deferRender: true, 
                  "scrollY": "200px",
                 "scrollCollapse": true,
                 "paging": false,
                 responsive: true,
                 "columnDefs": [
                 	{
                         "className": "text-center textMY",
                         "targets": [0]
                     } ,
                    {'targets': 4,'checkboxes': {'selectRow': true} },                    
	 	          ],
	 	          select: {'style': 'multi'},
	            }); 	 
 			}	
 		});
 	 	$('#example-select-all').on('click', function(){
 	      // Check/uncheck all checkboxes in the table
 	      var rows = table.rows({ 'search': 'applied' }).nodes();
 	      $('input[type="checkbox"]', rows).prop('checked', this.checked);
 	   });
 }
/*************************Reset to inital********************************************/
 function resetForm(){
	 $("#leaveType").val("").trigger('change');
	 $("#leaveYear").val("").trigger('change');
	 $("#issueMonth").val("").trigger('change');
	 $("#tranTypeId").val("").trigger('change');
	 $("#startDate").val("");
	 $("#EndDate").val("");
	 $("#sanctionBy").val("").trigger('change');
	 $("#yearlyquota").val("");
	 $("#reason").val("");
		if ($.fn.DataTable.isDataTable('#OverView')) {
         $('#OverView').DataTable().destroy();
     }
     $("#OverView tbody").empty();
  	 $('#OverView>tbody>tr').each(function() {
		$(this).find('td:eq(4)').each (function() {
  				$(this).find($("input")).removeAttr("checked")
			})
	 });
   	$('#OverView').hide();
  	op_flag="N";
	global_LeaveAllotId=0;
	EnableInputs();
 	formValidator.resetForm();				
}
/*****************Enable Inputs**********************************/
 function EnableInputs(){
	 $("#leaveType").removeAttr('disabled');
	 $("#leaveYear").removeAttr('disabled');
	 $("#issueMonth").removeAttr('disabled');
	 $("#tranTypeId").removeAttr('disabled');
	 $("#sanctionBy").removeAttr('disabled');
	 $("#reason").removeAttr('disabled');
  	 $('#OverView>tbody>tr').each(function() {
		$(this).find('td:eq(4)').each (function() {
  				$(this).find($("input")).removeAttr('disabled');
			});
	 });
 }
 /***********************Disable Filed******************************/
 function DisableInputs(){
	 $("#leaveType").attr('disabled', 'disabled');
	 $("#leaveYear").attr('disabled', 'disabled');
	 $("#issueMonth").attr('disabled', 'disabled');
	 $("#tranTypeId").attr('disabled', 'disabled');
	 $("#startDate").attr('disabled', 'disabled');
	 $("#EndDate").attr('disabled', 'disabled');
	 $("#sanctionBy").attr('disabled', 'disabled');
	 $("#yearlyquota").attr('disabled', 'disabled');
	 $("#reason").attr('disabled', 'disabled');
  	 $('#OverView>tbody>tr').each(function() {
		$(this).find('td:eq(4)').each (function() {
  				$(this).find($("input")).attr('disabled', 'disabled');
			});
	 });
}
/************************delete Record**********************************/
 function deleteRecord(postParameters){
 	$.ajax({
 		url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveTransaction/SaveEmpLeaveAllot",
 		data : JSON.stringify(postParameters),
 		method : "post",
 		dataType : "json",
 		contentType : "application/json",
 		success : function(res) {
 		 	if (JSON.parse(res["responseObj"]).status == "success") {
 	          toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
 	            closeButton: true,
 	            positionClass: 'toast-bottom-right'
 	          });
 	          resetForm();
 	          LoadList();
 	          DisableInputs();
 	        } else {
 	          toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
 	            closeButton: true,
 	            positionClass: 'toast-bottom-right'
 	          });
 	        }
 		}
 	});
 }
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptIdF" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<div class="row showTableDiv">
	<div class="col-lg-12">
		<div class="panel newPanel">
			<div class="panel-heading">
				<div class="panel-control">
					<button class="btn btn-default" data-click="panel-expand">
						<i class="fa fa-expand"></i>
					</button>
					<button class="btn btn-default" data-click="panel-reload" onclick="loadListOfLocation();">
						<i class="fa fa-refresh"></i>
					</button>
					<button class="btn btn-default" data-click="panel-collapse">
						<i class="fa fa-chevron-down"></i>
					</button>
					 <button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
					<button onclick="toggleTableAndForm('N',null)" class="btn btn-info">
						<i class="fa fa-plus"></i> Add New
					</button>
				</div>
				<h3 class="panel-title">Employee Leave Allotment</h3>
			</div>
			<div class="panel-body">		
				<table class="table table-striped table-bordered table-hover locationAllotTable table-responsive" id="detailList" class="display nowrap" style="width:100%">
					<thead>
						<tr>
							<th>Sr. No.</th>
							<th>Leave Name</th>
							<th>Leave Year</th>
							<th>Transaction Type</th>
							<th>Action</th>									
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>								
			</div>
		</div>
	</div>
</div>
<!------------------------------------------------------------>
<div class="row showFormDiv">
	<div class="col-lg-12">
		<form id="LeaveAllot">
			<div class="panel newpanel">
				<div class="panel-heading">
					<div class="panel-control">
						<button class="btn btn-default" data-click="panel-expand">
							<i class="fa fa-expand"></i>
						</button>
						<button class="btn btn-default" data-click="panel-reload">
							<i class="fa fa-refresh"></i>
						</button>
						<button class="btn btn-default" data-click="panel-collapse">
							<i class="fa fa-chevron-down"></i>
						</button>
						<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()">
							<i class="fa fa-times"></i>
						</button>
						<button onclick="toggleTableAndForm('N',null);" type="button" class="btn btn-success">
						<i class="fa fa-chevron-left"></i>&nbsp; Back to List </button>
					</div>
					<h3 class="panel-title formTitle"> Create New Employee Leave Allotment </h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-6">
							<div class="row">
								<div class="col-sm-6">									
									<div class="form-group">
										<label for="leaveType" class="control-label LblImp"> 
											<spring:message code="label.leaveType"></spring:message></label>
										<select name="leaveType" class="form-control mandatory" data-toggle="tooltip"  required
										  title="Select <spring:message code="label.leaveType"></spring:message>"  id="leaveType">
										</select>
										<small style="color: red"></small>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="form-group">
										<label for="tranTypeId" class="control-label LblImp">
											<spring:message code="label.tranTypeId"></spring:message></label>
										<select name="tranTypeId" class="form-control mandatory" data-toggle="tooltip"   required
										  title="Select <spring:message code="label.tranTypeId"></spring:message>"  id="tranTypeId">
											<option value=""></option>
											<option value="0" id="opening" >Opening</option>
											<option value="1" id="allot" >Allot</option>
											<option value="3" id="trans" >Transferred</option>
											<option value="4" id="laps"  >Laps</option>
											<option value="5" id="leaveEnc">Leave Encashment</option>
											<option value="6" id="leaveSal">Surrender Leave Salary</option>
											<option value="7" id="le"  >Leave</option>
										</select><small style="color: red"></small>
									</div>
								</div>
							</div>	
							<div class="row">
								
								<div class="col-sm-3">
									<div class="form-group">
										<label for="leaveYear" class="control-label LblImp">
											<spring:message code="label.leaveYear"></spring:message></label>
										<select name="leaveYear" class="form-control mandatory" data-toggle="tooltip" required 
										  title="Select <spring:message code="label.leaveYear"></spring:message>"  id="leaveYear">
										</select><small style="color: red"></small>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="form-group">
										<label for="issueMonth" class="control-label">
											<spring:message code="label.issueMonth"></spring:message></label>
										<select name="issueMonth" class="form-control " data-toggle="tooltip"  
										  title="Select <spring:message code="label.issueMonth"></spring:message>"  id="issueMonth">
										   <option value=''></option>
										   <option value='1'>Janaury</option>
										   <option value='2'>February</option>
										   <option value='3'>March</option>
										   <option value='4'>April</option>
										   <option value='5'>May</option>
										   <option value='6'>June</option>
										   <option value='7'>July</option>
										   <option value='8'>August</option>
										   <option value='9'>September</option>
										   <option value='10'>October</option>
										   <option value='11'>November</option>
										   <option value='12'>December</option>
										</select>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="form-group">
										<div class="form-group has-feedback">	
											<label for="startDate" class="control-label">
												<spring:message code="label.startDate"></spring:message></label>
											<input name="startDate" type="text" class="form-control" data-toggle="tooltip" id="startDate" disabled="disabled"
											 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.startDate"></spring:message>">
											<span class="fa fa-calendar fa-lg form-control-feedback" ></span>
										</div>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="form-group">
										<div class="form-group has-feedback">	
											<label for="EndDate" class="control-label">
												<spring:message code="label.EndDate"></spring:message></label>
											<input name="EndDate" type="text" class="form-control" data-toggle="tooltip" id="EndDate" disabled
											 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.EndDate"></spring:message>">
											<span class="fa fa-calendar fa-lg form-control-feedback"></span>
										</div>
									</div>
								</div>
							</div>	
							<div class="row">						
								<div class="col-sm-6">
									<div class="form-group">
										<label for="sanctionBy" class="control-label">
											<spring:message code="label.sanctionBy"></spring:message></label>
										<select name="sanctionBy" class="form-control " data-toggle="tooltip"  
										  title="Select <spring:message code="label.sanctionBy"></spring:message>"  id="sanctionBy">
										</select>
									</div>
								</div>
								<div class="col-sm-3">
									<div class="form-group">
										<div class="form-group has-feedback">	
											<label for="sancDate" class="control-label">
												<spring:message code="label.sancDate"></spring:message></label>
											<input name="sancDate" type="text" class="form-control" data-toggle="tooltip" id="sancDate" readonly
											 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.sancDate"></spring:message>">
											<span class="fa fa-calendar fa-lg form-control-feedback"></span>
										</div>
									</div>
							</div>
								<div class="col-sm-3">								
									<div class="form-group">
										<label for="yearlyquota" class="control-label LblImp">
											<spring:message code="label.yearlyquota"></spring:message>
										</label>
										<input name="yearlyquota" type="text" class="form-control mandatory" data-toggle="tooltip" disabled="disabled"
										 placeholder="Enter <spring:message code="label.yearlyquota"></spring:message>"  title="Enter Party Filling Case" 
										  size="60" maxlength="200"  id="yearlyquota" required >
										  <small style="color: red"></small>
									</div>
								</div>	
							</div>		
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<label for="reason"  class="LblImp control-label">
											<spring:message code="label.reason"></spring:message></label>
										<textarea name="reason" class="form-control mandatory" data-toggle="tooltip"
										 placeholder="Enter Subject Matter"  title="Enter <spring:message code="label.reason"></spring:message>" required
										 rows="7" maxlength="2000"  id="reason"  style='resize: vertical;'></textarea>
									<small style="color: red"></small>
									</div>
								</div>
							</div>					
						</div>
						<div class="col-sm-6">
							<table class="table table-striped table-bordered table-hover locationMasterTable table-responsive" id="OverView">
								<thead>
									<tr>
										<th>Sr. No.</th>
										<th>Employee Name </th>
										<th>Designation</th>
										<th style="width: 40px !important;">Leave Yr. Quota</th>
										<th><input name="select_all" value="1" id="example-select-all" type="checkbox" /></th>
									</tr>
								</thead>
						</table>
						</div>
					</div>
					<hr>
					<button  class="btn btn-primary submitBtnName" type="button" id="SaveLeaveAllot">
					 <i class="fa fa-save"></i>Save Employee Leave Application
					</button>
					&nbsp;
					<button type="button" class="btn resetBtnName btn-danger" id="ResetLeaveAllot" onclick="resetForm()">
					Reset
					</button>
				</div>
			</div>
		</form>
	</div>
</div>
</body>
</html>