<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - SANKER EPS -Aishwarya Domde
Creation Date	- Apr 20, 2019 6:30:40 PM 
Project Name	- MLWB 
Module Name		- Payroll
Page			- Leave Details
Description		-
Link			-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employee Leave Master</title>
<link href="assets/css/style.css" rel="stylesheet">
<link href="assets/plugins/switchery/switchery.min.css" rel="stylesheet">
 <!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>
<link rel="stylesheet" type="text/css"href="assets/plugins/daterange_new/daterangepicker.css" />
<script type="text/javascript"src="assets/plugins/daterange_new/daterangepicker.js"></script>
<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Data Parsley [ OPTIONAL ]-->
<script src="assets/plugins/parsley/parsley.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Jquery Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>
<script src="assets/plugins/switchery/switchery.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<link href="assets/plugins/pretty-checkbox/pretty-checkbox.min.css" rel="stylesheet">
<script src="assets/js/focusOnEnter.js"></script>
<!--Tabbable JS -->
<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<script src="assets/js/validation.js"></script>
<style>
.LblImp:after{
	content:"*";
	color:red;
}
th.sorting {
    text-align: center;
}
#EditEmpFamilyDet>tbody>tr>td>input {
    width: 100%;
}
</style>
<script type="text/javascript">

$(document).ready(function() {	
	$("#leaveFromDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 });
	$("#leaveToDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    maxDate: '0',
	 });
	$("#empName").select2({
		placeholder:"Select",
		width:'100%',
		multiple:false,
		allowClear:true,	
	});
	var today = new Date();
	var dd = today.getDate();
	var mm = today.getMonth() + 1; //January is 0!

	var yyyy = today.getFullYear();
	if (dd < 10) {
	  dd = '0' + dd;
	} 
	if (mm < 10) {
	  mm = '0' + mm;
	} 
	var today = dd + '/' + mm + '/' + yyyy;
	$("#leaveToDate").val(today).trigger('change')
	$("#leaveFromDate").val(today).trigger('change')
	/*********************************************************************/
	$('.showTableDiv').find('input').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	$('.select2-container').tooltipster({
	    functionInit: function(instance, helper){
	        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
	        instance.content(content);
	    },
	    delay: 100,
	    theme: 'tooltipster-punk',
	    side: 'bottom'
	});
	/*********************************************************************/
	$('.showTableDiv').on('keyup change paste blur select2:close', 'input, select, textarea, button, a', function(event){
		let elem = event.target;
		let elValid = false;
		if (!$(elem).valid()) {
			elValid = true;
	    }
	    $('.mandatory').each(function() {
	    	if ($(this).val()=='' || $(this).val()==null) {
				elValid = true;
	        }
	    });
	    if (elValid) {
	    	$('.submitBtnName').attr('disabled', 'disabled');
	    } else {
	    	$('.submitBtnName').removeAttr('disabled');
	    	
	    }
	});
	/*********************************************************************/
	$.ajax({  
	    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
	    data : JSON.stringify({
			"param" : "null",
			"sqlMstId" :428
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(response){
	    	Emp_resp = JSON.parse(response["codeList"])
	    	$.each(Emp_resp, function(key,value) {
					nKey = parseInt(key)+1;
					$("#empName").append('<option value="'+Emp_resp[key].employee_mst_id+'"> '+Emp_resp[key].employee_name+'');
			}); 
	      },
	 });
	 /**************************************************************************************/
	 $("#ShowLeaveDetails").on("click",function(){
		 let param={
					fromDate 	: $("#leaveFromDate").val(),
					toDate		: $("#leaveToDate").val(),
					EmpMstId	: $("#empName").val(),
				};
		 $.ajax({
				url :"${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveDetails/getLeaveData",			
				data : JSON.stringify(param),
				method : "post",
				dataType : "json",
				contentType : "application/json",
				async: false,
			    success: function(resp){
			    	EmpLeaveDetails = JSON.parse(resp["EmpLeaveDetails"]);
				}
		 });
	 });
	/************************************************************************************/
	$("#empName").on("change", function(){
		let EmpId = $("#empName").val();
		$.each(Emp_resp, function (key,i) {
			if(Emp_resp[key]['employee_mst_id']==EmpId){
				$("#Designation").val(Emp_resp[key]['desig_name']);
				$("#employeeDeptId").val(Emp_resp[key]['dept_name']);
			}
		});
	});
});
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptId" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<div class="row showTableDiv">
	<div class="col-lg-12">
		<div class="panel newPanel">
			<div class="panel-heading">
				<div class="panel-control">
					<button class="btn btn-default" data-click="panel-expand">
						<i class="fa fa-expand"></i>
					</button>
					<button class="btn btn-default" data-click="panel-reload" onclick="loadListOfLocation();">
						<i class="fa fa-refresh"></i>
					</button>
					<button class="btn btn-default" data-click="panel-collapse">
						<i class="fa fa-chevron-down"></i>
					</button>
					 <button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
					<button  class="btn btn-primary submitBtnName" type="button" id="ShowLeaveDetails">
					 <i class="fa fa-inbox"></i>  Show Employee Leave Details
					</button>
				</div>
				<h3 class="panel-title">Employee Leave Details</h3>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-sm-4">
						<div class="form-group">
							<label for="empName" class="control-label LblImp">
								<spring:message code="label.empName"></spring:message></label>
							<select name="empName" class="form-control Advocate mandatory" data-toggle="tooltip"  required
							  title="Select <spring:message code="label.empName"></spring:message>"  id="empName">
							 <option></option>
							</select>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
								<div class="form-group has-feedback">	
									<label for="leaveFromDate" class="control-label LblImp">
										<spring:message code="label.leaveFromDate"></spring:message></label>
									<input name="leaveFromDate" type="text" class="form-control hasDatepic mandatory" data-toggle="tooltip" id="leaveFromDate"
									 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;" required title="Enter <spring:message code="label.leaveFromDate"></spring:message>">
									<span class="fa fa-calendar fa-lg form-control-feedback"></span>
								</div>
							</div>
					</div>
					<div class="col-sm-2">
					<div class="form-group">
								<div class="form-group has-feedback">	
									<label for="leaveToDate" class="control-label LblImp">
										<spring:message code="label.leaveToDate"></spring:message></label>
									<input name="leaveToDate" type="text" class="form-control hasDatepic mandatory" data-toggle="tooltip" id="leaveToDate"
									 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;" required title="Enter <spring:message code="label.leaveToDate"></spring:message>">
									<span class="fa fa-calendar fa-lg form-control-feedback"></span>
								</div>
							</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<label for="Designation" class="control-label LblImp">
								<spring:message code="label.Designation"></spring:message>
							</label>
							<input name="Designation" type="text" class="form-control mandatory" data-toggle="tooltip" name="Designation"
							 placeholder="Enter <spring:message code="label.Designation"></spring:message>"  title="Enter Party Filling Case" 
							  size="60" maxlength="200"  id="Designation" required disabled>
						</div>
					</div>
					<div class="col-sm-2">
						<div class="form-group">
							<label for="employeeDeptId" class="control-label LblImp">
								<spring:message code="label.employeeDeptId"></spring:message>
							</label>
							<input name="employeeDeptId" type="text" class="form-control mandatory" data-toggle="tooltip" name="employeeDeptId"
							 placeholder="Enter <spring:message code="label.employeeDeptId"></spring:message>"  title="Enter Party Filling Case" 
							  size="60" maxlength="200" id="employeeDeptId" required disabled>
						</div>
					</div>
				</div>	<br>	
				<div class="row">
					<table class="table table-striped table-bordered table-hover locationMasterTable table-responsive" id="detailList">
						<thead>
							<tr>
								<th>Name</th>
								<th>Leave Name</th>
								<th>Application Date</th>
								<th>Leave From</th>
								<th>Leave To</th>
								<th>Reason</th>
								<th>Recommend Flag</th>
								<th>Recommend Employee</th>
								<th>Recommended Date</th>
								<th>Sanction Flag</th>
								<th>Sanction Emp</th>
								<th>Sanction Date</th>
								<th>First Half</th>
								<th>Second Half</th>
								<th>Public Holiday</th>
								<th>Apply Days</th>
								<th>Leave Address</th>												
							</tr>
						</thead>
						<tbody></tbody>
					</table>
				</div>								
			</div>
		</div>
	</div>
</div>
</body>
</html>