<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - Aishwarya Domde
Creation Date	- May 3, 2019 5:59:15 PM
Project Name	- MLWB 
Module Name		- 
Page\Class\etc... Name -: Employee Family Details
Description	-
Link		-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employee Leave Recommendation</title>
<link href="assets/css/style.css" rel="stylesheet">
<link href="assets/plugins/switchery/switchery.min.css" rel="stylesheet">
 <!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>
<link rel="stylesheet" type="text/css"href="assets/plugins/daterange_new/daterangepicker.css" />
<script type="text/javascript"src="assets/plugins/daterange_new/daterangepicker.js"></script>
<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Data Parsley [ OPTIONAL ]-->
<script src="assets/plugins/parsley/parsley.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Jquery Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>
<script src="assets/plugins/switchery/switchery.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<link href="assets/plugins/pretty-checkbox/pretty-checkbox.min.css" rel="stylesheet">
<script src="assets/js/focusOnEnter.js"></script>
<!--Tabbable JS -->
<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<style>
.LblImp:after{
	content:"*";
	color:red;
}
th.sorting {
    text-align: center;
}
</style>
<script type="text/javascript">
let global_LeaveRecomdId  = 0;
let op_flag = "N";
let showForm = false;
let showTable = true;
let formValidator=null,To_apply ;

var myDate = new Date();
var TodaySet = myDate.getDate() + '/' +(myDate.getMonth()+1) + '/' +myDate.getFullYear();
$(document).ready(function() {	
	$('.showTableDiv').show(); 
	$('.showFormDiv').hide();
	LoadListTbl();
	getsetInt();
	GetDetails();
	validateForm();
	$("#Reco_recomedLeaveDays,#Reco_leaveDays").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#Apply_applyLeaveDays,#Apply_publicHoliday,#Apply_leaveDays").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#Reco_publicHoliday").numeric({negative: false}).addClass("speech-right numbersOnly");
	$("#Reco_toDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate:'0'
	 }); 
	$("#Reco_fromDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate:'0'
	 }); 
	$("#Reco_Date").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate: '0',
	    maxDate: '0',
	 });
	$("select").select2({
		placeholder:"Select",
		width:'100%',
		multiple:false,
		allowClear:true,		
	});
	$('form').find('input,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	/*********************************************************************/
	$('form').on('keyup change paste blur select2:close', 'input, select, textarea, button, a', function(event){
		let elem = event.target;
		let elValid = false;
		if (!$(elem).valid()) {
			elValid = true;
	    }
	    $('.mandatory').each(function() {
	    	if ($(this).val()=='' || $(this).val()==null) {
				elValid = true;
	        }
	    });
	    if (elValid) {
	    	$('.submitBtnName').attr('disabled', 'disabled');
	    } else {
	    	$('.submitBtnName').removeAttr('disabled');
	    }
	});
	/*************This is used to get reason Code From Code Master**********/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getCodeList",
	    type:'post',  
	    dataType:'json',
	    data : JSON.stringify({
	    	sqlMstId : "107",
	    	param : 35+"~"+"null"
	    }),
	    method : "post",
		dataType : "json",
		async : false,
		contentType : "application/json",
		success : function(resp) {
			responList =JSON.parse(resp["codeList"]);
			let listOfEmpOptions = '<optgroup class="def-cursor" label="Reason ID" data-id="Reason ID" data-design="Reason">';
			var optGrpEnd = '</optgroup>';
			var optionsList='';	
				$.each(responList, function (key,i) {
					optionsList = optionsList+'<option value="'+responList[key]["code"]+'" data-id="'+responList[key]["code"]
					+'" data-design="'+responList[key]["description"]+'">'+responList[key]["description"]+'</option>';
		 		});
			 optionsList=listOfEmpOptions+optionsList+optGrpEnd;
	       	 $("#Reco_reasonCodeId").empty().append(optionsList);
	       	 $('#Reco_reasonCodeId').select2({
	    		    width: '100%',
	    			placeholder:"Select",
	    			allowClear: true,
	    		    templateResult: formatResultMulti,
	    		}).on('change',function(){
	    			
	    		});
		},
		failure : function() {
			console.log("failed to load list.");
		}		
	});
	/*********************************************************************/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getHelpList",
		data : JSON.stringify({
		"param" :"PLEAVEHELP~"
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(respp){
	    	resp = (respp["helpList"]);
	    	$("#Reco_recomendLeaveName").empty().append("<option></option>");
	    	$.each(resp, function(key,value) {
	    	    if(resp[key].prop8=="Y"){
		    	    	nKey = parseInt(key)+1;
					$("#Reco_recomendLeaveName").append('<option value="'+resp[key].prop2+'"> '+resp[key].prop3);
	    	    }
			}); 
	      },
	 });
	$('.select2-container').tooltipster({
	    functionInit: function(instance, helper){
	        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
	        instance.content(content);
	    },
	    delay: 100,
	    theme: 'tooltipster-punk',
	    side: 'bottom'
	});
	 /******************************************************************/
	 $("#SaveLeaveRecomd").on("click",function(){
		 if($("#LeaveRecomd").valid()){
			 let Reco_Flgchck1= "N";	 let Reco_Flgchck2= "N";
			 let Apply_Flgchck1= "N";	 let Apply_Flgchck2= "N";
			 
			 	if($("#Apply_Fhalf").is(":checked")){
			 		Apply_Flgchck1 = "Y";
				}else{
					Apply_Flgchck1= "N";
				}
			 	if($("#Apply_Shalf").is(":checked")){
			 		Apply_Flgchck2 = "Y";
				}else{
					Apply_Flgchck2= "N";
				}
			 	if($("#Reco_Fhalf").is(":checked")){
			 		Reco_Flgchck1 = "Y";
				}else{
					Reco_Flgchck1= "N";
				}
			 	if($("#Reco_Shalf").is(":checked")){
			 		Reco_Flgchck2 = "Y";
				}else{
					Reco_Flgchck2= "N";
				}
				let postParameters = {
						Apply_employeeName  	: $("#Apply_employeeName").val(), 
						Apply_Designation       : $("#Apply_Designation").val(), 
						Apply_deptId            : $("#Apply_deptId").val(), 
						Apply_leaveNameId       : $("#Apply_leaveNameId").val(),
						Apply_applicationDate   : $("#Apply_applicationDate").val(),
						Apply_leaveFromDate     : $("#Apply_leaveFromDate").val(),
						Apply_Fhalf             : Apply_Flgchck1,
						Apply_leaveToDate       : $("#Apply_leaveToDate").val(),
						Apply_Shalf             : Apply_Flgchck2,
						Apply_applyLeaveDays    : $("#Apply_applyLeaveDays").val(), 
						Apply_publicHoliday     : $("#Apply_publicHoliday").val(), 
						Apply_leaveDays         : $("#Apply_leaveDays").val(), 
						Apply_recoEmpName       : $("#Apply_recoEmpName").val(),
						Apply_reasonCodeId      : $("#Apply_reasonCodeId").val(),
						Apply_leaveDaysAddress  : $("#Apply_leaveDaysAddress").val(),
						Apply_reason            : $("#Apply_reason").val(), 
						Reco_EmpName            : $("#Reco_EmpName").val(), 
						Reco_EmpDepartment      : $("#Reco_EmpDepartment").val(), 
						Reco_Date               : $("#Reco_Date").val(),
						Reco_fromDate           : $("#Reco_fromDate").val(),
						Reco_Fhalf              : Reco_Flgchck1,
						Reco_toDate             : $("#Reco_toDate").val(),
						Reco_Shalf              : Reco_Flgchck2,
						Reco_publicHoliday      : $("#Reco_publicHoliday").val(), 
						Reco_recoleaveDays      : $("#Reco_recomedLeaveDays").val(), 
						Reco_recomendLeaveName  : $("#Reco_recomendLeaveName").val(), 
						Reco_sancReason         : $("#Reco_sancReason").val(), 
						Reco_leaveRecomendFlag  : $("#Reco_leaveRecomendFlag").val(),
						Reco_reasonCodeId       : $("#Reco_reasonCodeId").val(),
						Recom_opFlag	  		: op_flag,
						LeaveId    				: global_LeaveRecomdId,
						Recom_userId			: $("#userId").val(),	
						Apply_userId			: $("#Apply_userId").val(),	
						Recom_branchMstId	    : $("#branchMstId").val(),	
						Reco_Ldays       		: $("#Reco_leaveDays").val(), 
			};
			console.log(postParameters);
			if(op_flag=="D"){
				$.confirm({
	                title: 'Are you sure want to delete ?',
	                content: '',
	                type: 'blue',
	                buttons: {
			            Delete: {			              
			                action: function () {
			                   deleteRecord(postParameters);
			                }
			            },
			            Cancel: {
			                keys: ['N'],
			                action: function () {
			                	$('.showFormDiv').hide();
			                    $('.showTableDiv').show();
			                }
			            },
			        }
	            }); 
			}else if(op_flag=="M" || op_flag=="N"){
				$.ajax({
					url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveRecomd/SaveEmpLeaveRecomd",
					data : JSON.stringify(postParameters),
					method : "post",
					dataType : "json",
					contentType : "application/json",
					success : function(res) {
					 	if (JSON.parse(res["responseObj"]).status == "success") {
				         	toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
				            closeButton: true,
				            positionClass: 'toast-bottom-right'
				          });
				          showForm = true;
				          resetForm();
				          LoadListTbl();
				          EnableInputs();
				        } else {
				          	toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
				            closeButton: true,
				            positionClass: 'toast-top-right'
				          });
				        }
					}
				});
			}
		 }
	 });
 	/****************************************************/	
 	$("#Reco_fromDate ,#Reco_toDate").on("change",function(){
	 	 	var LeaveToDate = $("#Reco_toDate").val();
	 	 	var leaveFromDate = $("#Reco_fromDate").val();
	 	 	if(leaveFromDate!="" && LeaveToDate!=""){
	 		$.ajax({  
	 			url : "${pageContext.request.contextPath}/app/common/getCodeList",
	 		    type:'post',  
	 		    dataType:'json',
	 		    data : JSON.stringify({
	 		    	sqlMstId : "7125",
	 		    	param : "''D'',''"+leaveFromDate+"'',''"+LeaveToDate+"''"
	 		    }),
	 		    method : "post",
	 			dataType : "json",
	 			async : false,
	 			contentType : "application/json",
	 			success : function(resp) {
	 				responList =JSON.parse(resp["codeList"]);
	 				$("#Reco_recomedLeaveDays").val(responList[0].days_leave);
	 	 		}
	 		}); 	
	 	}	
	 	$("#Reco_publicHoliday").val("0");
	 	$("#Reco_leaveDays").val($("#Reco_recomedLeaveDays").val());
		 	doCheckavil()
	 });
 	/****************************************************/
 	$("input[type=checkbox]").on("change",function(){
		var AplyLeave = $("#Reco_recomedLeaveDays").val();
		var totalAplyLeave;var LeaveToDate = $("#Reco_toDate").val();
 	 	var leaveFromDate = $("#Reco_fromDate").val();
	 	if(LeaveToDate!=""&&leaveFromDate!=""){
		if($(this).is(":checked")){
			totalAplyLeave =parseFloat(AplyLeave) - Number(0.5);
			$("#Reco_recomedLeaveDays").val(totalAplyLeave);
			$("#Reco_leaveDays").val(totalAplyLeave);
		}else{
			totalAplyLeave =parseFloat(AplyLeave) + Number(0.5);
			$("#Reco_recomedLeaveDays").val(totalAplyLeave);
			$("#Reco_leaveDays").val(totalAplyLeave);
			}

	 	doCheckavil()
	 	}
		$("#Reco_publicHoliday").trigger("change");
	});
	/***************************************************/
	$("#Reco_publicHoliday").on("change",function(){
		var AplyLeave = $("#Reco_recomedLeaveDays").val();
		var Reco_publicHoliday = $("#Reco_publicHoliday").val();
		if(AplyLeave>Reco_publicHoliday){
		var totalAplyLeave =parseFloat(AplyLeave) - Number(Reco_publicHoliday);
		if(totalAplyLeave>=0){
			$("#Reco_leaveDays").val(totalAplyLeave);
		}else{$("#Reco_leaveDays").val("");}
		}else{
			$("#Reco_publicHoliday").val("0");
			$("#Reco_leaveDays").val(AplyLeave);
			}
		doCheckavil()
	});
	/**********************For Checking whether leaves are available of not*******************************************/
	$("#Reco_recomendLeaveName").on("select2:select change",function(){
		let SLeaveName = $(this).val();
		let Tbl_LeaveName,isAvil,applied;
		$('#OverView tbody>tr>td:nth-child(2).display_hide').each(function() {
			Tbl_LeaveName =$(this).text();
			console.log(SLeaveName,Tbl_LeaveName)
			if(Tbl_LeaveName==SLeaveName && SLeaveName!="6"){
				isAvil=$(this).nextAll('td').closest(".avil_Leave").text();
				if(isAvil=="0"){
					$("#Reco_recomendLeaveName").select2('destroy'); 
					$("#Reco_recomendLeaveName").select2({placeholder:"Select",
			 				width:'100%',
			 				multiple:false,
			 				allowClear:true,					
			 		});
					$("select").find('option').each(function(i) {
						$('#Reco_recomendLeaveName option[value='+SLeaveName+']').attr('disabled','disabled');
					});
					$("#Reco_recomendLeaveName").find('.select2-container').tooltipster({
			 			    functionInit: function(instance, helper){
			 			        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
			 			        instance.content(content);
			 			    },
			 			    delay: 100,
			 			    theme: 'tooltipster-punk',
			 			    side: 'bottom'
			 			}); 
					$("#Reco_recomendLeaveName").val("").trigger("change");
					$("#Reco_recomendLeaveName").siblings('small').append("Please select another Leave,this leave type not available");
					
				}
			}
			/***********************************************/			
		    $.ajax({  
			    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
			    data : JSON.stringify({
					"param" : SLeaveName+"~"+$("#userId").val(),
					"sqlMstId" :7338
				}),
				method : "post",
				dataType : "json",
				contentType : "application/json",
				async: false,
			    success: function(response){
			    	let resp = JSON.parse(response["codeList"])
			    	applied=(resp[0].pending_sanction_leave)
			      },
			 });
			if(SLeaveName==Tbl_LeaveName){
			    To_apply= ($(this).closest("tr").find(".avil_Leave").text()-applied)
			}
			
		});
	});
});
/*************************Document Ready over function starts Reset Settings*************************/
 function validateForm(){
 	formValidator = $("#LeaveRecomd").validate({
         rules: {
         	},
         messages: {
          },
         highlight: function (element, errorClass, validClass) {
         	if($(element).hasClass('mandatory')){
         		var elem = $(element);
                 elem.addClass(errorClass);
                 elem.siblings('.select2-container').addClass(errorClass); 
         	}
         },    
         unhighlight: function (element, errorClass, validClass) {
               var elem = $(element);
               elem.removeClass(errorClass);
               elem.siblings('.select2-container').removeClass(errorClass);
               elem.siblings('small').empty();
         },
         errorPlacement: function(error, element) {
             $(element).siblings('small').empty().html(error);
          },
         submitHandler: function (form) {
         	e.preventDefault(e);
             return false; 
         }
     });
 }
 /*************************************Toggle table and Form*********************************************/
 function toggleTableAndForm(flag, empMstId) {
 	if (showForm) {
 		showForm = false;
 		showTable = true;
 		$('.showTableDiv').show();
 		$('.showFormDiv').hide();
 	} else {
 		if (flag == 'M') {
 			$("#ResetLeaveRecomd").hide();
 			$('.formTitle').html('Update Employee Leave Recommendation');
 			$('.submitBtnName').html('<i class="fa fa-save"></i> Update Employee Leave Recommendation ');
 			resetForm();
 			DisableInputs();
 			GetDetails();
 			SetApplyRecomdDetails(empMstId);
 			getsetInt();GetDetails();
 			op_flag = "M";	
 		}
 		if (flag == 'N') {	
 			$("#ResetLeaveRecomd").show();	
 			$('.formTitle').html('Create New Employee Leave Recommendation ');
 			$('.submitBtnName').html('<i class="fa fa-save"></i> Save Employee Leave Recommendation ');
 			$('.submitBtnName').attr('disabled', 'disabled');
 			resetForm();
			DisableInputs();
 			GetDetails();
     		$('.showTableDiv').show();
 		}
 		if (flag == 'D') {
 			$("#ResetLeaveRecomd").hide();
 			$('.formTitle').html('<i class="fa fa-save"></i> Delete  Employee Leave Recommendation');
 			$('.submitBtnName').html('Delete Employee Leave Recommendation ');
 			resetForm();
 			EnableInputs();
 			GetDetails();
 			SetApplyRecomdDetails(empMstId);
 			op_flag = "D"; 	
 		}
 		showForm = true;
 		showTable = false;
 		$('.showTableDiv').hide();
 		$('.showFormDiv').show();
 	}	
 	 $('#detailList').DataTable().columns.adjust().responsive.recalc();
}
/*********************resetForm**************************************/
 function resetForm(){
	 $("#Apply_userId").val("");			
	 $("#Apply_employeeName").val("");
	 $("#Apply_Designation").val("");
	 $("#Apply_deptId").val("");	
	 $("#Apply_leaveNameId").val("");
	 $("#Apply_leaveName").val("");
	 $("#Apply_applicationDate").val("");
	 $("#Apply_leaveFromDate").val("");	
	 $("#Apply_Fhalf").val("");	
	 $("#Apply_leaveToDate").val("");
	 $("#Apply_Shalf").val("");	
	 $("#Apply_applyLeaveDays").val("");	
	 $("#Apply_publicHoliday").val("");	
	 $("#Apply_leaveDays").val("");
	 $("#Apply_recoEmpName").val("");
	 $("#Apply_reasonCodeId").val("");
	 $("#Apply_reasonCodeName").val("");	
	 $("#Apply_leaveDaysAddress").val("");
	 $("#Apply_reason").val("");	
	 
	 $("#Reco_EmpName").val("");	
	 $("#Reco_EmpDepartment").val("");
	 $("#Reco_Date").val("");		
	 $("#Reco_fromDate").val("");	
	 $("#Reco_Fhalf").val("");		
	 $("#Reco_toDate").val("");	
	 $("#Reco_Shalf").val("");		
	 $("#Reco_recomedLeaveDays").val("");
	 $("#Reco_publicHoliday").val("");
	 $("#Reco_leaveDays").val("");	
	 $("#Reco_sancReason").val("");
	 if($('#Reco_reasonCodeId').val()!=null){
		 $('#Reco_reasonCodeId').val(null).trigger('change');
	}
	 if($('#Reco_recomendLeaveName').val()!=null){
		 $('#Reco_recomendLeaveName').val(null).trigger('change');
	}	
	 if($('#Reco_leaveRecomendFlag').val()!=null){
		 $('#Reco_leaveRecomendFlag').val(null).trigger('change');
	}
	$("#Apply_Fhalf").prop('checked', false);
	$("#Apply_Shalf").prop('checked', false);
	$("#Reco_Fhalf").prop('checked', false);
	$("#Reco_Shalf").prop('checked', false);	
	op_flag="N";
	global_LeaveRecomdId=0;		
	formValidator.resetForm();	
}
/********************************************************************/
 function DisableInputs(){
	 $("#Reco_Date").removeAttr('disabled');		
	 $("#Reco_fromDate").removeAttr('disabled');	
	 $("#Reco_Fhalf").removeAttr('disabled');		
	 $("#Reco_toDate").removeAttr('disabled');	
	 $("#Reco_Shalf").removeAttr('disabled');		
	 $("#Reco_publicHoliday").removeAttr('disabled');	
	 $("#Reco_sancReason").removeAttr('disabled');
	 $('#Reco_reasonCodeId').removeAttr('disabled');
	 $('#Reco_recomendLeaveName').removeAttr('disabled');
	 $('#Reco_leaveRecomendFlag').removeAttr('disabled');
	 $("#Reco_Shalf").prop('checked', false).removeAttr('disabled');	
	 $("#Reco_Fhalf").prop('checked', false).removeAttr('disabled');	
}
/********************************************************************/
 function EnableInputs(){
	 $("#Reco_Date").attr("disabled","disabled");		
	 $("#Reco_fromDate").attr("disabled","disabled");	
	 $("#Reco_Fhalf").attr("disabled","disabled");		
	 $("#Reco_toDate").attr("disabled","disabled");	
	 $("#Reco_Shalf").attr("disabled","disabled");		
	 $("#Reco_recomedLeaveDays").attr("disabled","disabled");
	 $("#Reco_publicHoliday").attr("disabled","disabled");	
	 $("#Reco_sancReason").attr("disabled","disabled");
	 $('#Reco_reasonCodeId').attr("disabled","disabled");
	 $('#Reco_recomendLeaveName').attr("disabled","disabled");
	 $('#Reco_leaveRecomendFlag').attr("disabled","disabled");
	 $("#Reco_Fhalf").prop('checked', false).attr("disabled","disabled");
	 $("#Reco_Shalf").prop('checked', false).attr("disabled","disabled");	
}
 /********************for column creation in select2************************************/
 function formatResultMulti(data) {
	  var design = $(data.element).data('design');
	  var id = $(data.element).data('id');
	  var classAttr = $(data.element).attr('class');
	  var hasClass = typeof classAttr != 'undefined';
	  classAttr = hasClass ? ' ' + classAttr : '';
	  var $result = $(
	    '<div class="row" id=' + id + '>' +
	    '<div class="col-md-4 col-xs-4' + classAttr + '">' + id + '</div>' +
	    '<div class="col-md-8 col-xs-8' + classAttr + '">' + design + '</div>'  +
	    '</div>'
	  );
	  return $result;
}
/**************This is used to get Details of Application and Recommendation************************/
function SetApplyRecomdDetails(SectId){
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getCodeList",
	    type:'post',  
	    dataType:'json',
	    data : JSON.stringify({
	    	sqlMstId : "197",
	    	param : "null"
	    }),
	    method : "post",
		dataType : "json",
		async : false,
		contentType : "application/json",
		success : function(resp) {
		$("#EditEmpFamilyDet tbody").empty();
     	respListSet = JSON.parse(resp["codeList"]);
     	$.each(respListSet, function (key,j) {
    		if(respListSet[key]['leave_appli_id']==SectId){
    				global_LeaveRecomdId=SectId;
				/**********************Check half Day**************************/
				let first_half,recomend_to_date;
				let second_half,recomend_from_date;
				let rec_first_half;
				let rec_second_half;
				if(respListSet[key]['first_half']=="YES"){
					$("#Apply_Fhalf").prop('checked', true).trigger("change");
				}else{
					$("#Apply_Fhalf").prop('checked', false).trigger("change");
				}
				if(respListSet[key]['second_half']=="YES"){
					$("#Apply_Shalf").prop('checked', true).trigger("change");
				}else{
					$("#Apply_Shalf").prop('checked', false).trigger("change");
				}
				if(respListSet[key]['rec_first_half']=="YES"){
					$("#Reco_Fhalf").val("Y");
				}else{
					if(respListSet[key]['second_half']=="YES"){
						$("#Reco_Fhalf").val("Y");
					}else{
					$("#Reco_Fhalf").prop('checked', false).trigger("change");
					};
				}
				if(respListSet[key]['rec_second_half']=="YES"){
					$("#Reco_Shalf").val("Y");
				}else{
					if(respListSet[key]['second_half']=="YES"){
						$("#Reco_Shalf").val("Y");
					}else{
					$("#Reco_Shalf").prop('checked', false).trigger("change");
					};
				}
				/***************************/
				if(respListSet[key]['recomend_from_date']==null){
					recomend_from_date=respListSet[key]['leave_from_date'];
				}else{
					recomend_from_date=respListSet[key]['recomend_from_date'];
				}
				if(respListSet[key]['recomend_to_date']==null){
					recomend_to_date=respListSet[key]['leave_to_date'];
				}else{
					recomend_to_date=respListSet[key]['recomend_to_date'];
				}
     			/******************Application******************/
     			$("#Apply_userId").val(respListSet[key]['employee_mst_id']);
				$("#Apply_employeeName").val(respListSet[key]['employee_name']);
				$("#Apply_Designation").val(respListSet[key]['designation_name']); 
				$("#Apply_deptId").val(respListSet[key]['department_name']);
				$("#Apply_leaveNameId").val(respListSet[key]['leave_mst_id']);
				$("#Apply_leaveName").val(respListSet[key]['leave_name']);								
				$("#Apply_applicationDate").val(respListSet[key]['application_date']);							
				$("#Apply_leaveFromDate").val(respListSet[key]['leave_from_date']);						
				$("#Apply_leaveToDate").val(respListSet[key]['leave_to_date']);						
				$("#Apply_applyLeaveDays").val(respListSet[key]['apply_leave_days']);							 
				$("#Apply_publicHoliday").val(respListSet[key]['public_holiday']);							 
				$("#Apply_leaveDays").val(respListSet[key]['leave_days']);							 
				$("#Apply_recoEmpName").val(respListSet[key]['recomend_emp_name']);						
				$("#Apply_reasonCodeId").val(respListSet[key]['reason_code_id']);								
				$("#Apply_reasonCodeName").val(respListSet[key]['reason_code_name']);							
				$("#Apply_leaveDaysAddress").val(respListSet[key]['leave_days_address']);								
				$("#Apply_reason").val(respListSet[key]['reason']);	
				/*********************************************/							 
				$("#Reco_EmpName").val(respListSet[key]['recomend_emp_name']);					 
				$("#Reco_EmpDepartment").val(respListSet[key]['recomend_dept_name']);				
				$("#Reco_fromDate").val(recomend_from_date).trigger("change");	
				$("#Reco_toDate").val(recomend_to_date).trigger("change"); 		
				$("#Reco_recomedLeaveDays").val(respListSet[key]['rec_apply_leave_days']);						 
				$("#Reco_publicHoliday").val(respListSet[key]['rec_public_holiday']);								 
				$("#Reco_recomendLeaveName").val(respListSet[key]['recomend_leave_mst_id']).trigger("change");								 
				$("#Reco_sancReason").val(respListSet[key]['reason']);								 
				$("#Reco_leaveRecomendFlag").val(respListSet[key]['leave_recomend_flag']).trigger("change");								
				$("#Reco_reasonCodeId").val(respListSet[key]['reason_code_id']).trigger("change");
				$("#Reco_Date").val(TodaySet);	
				$("#Reco_leaveDays").val(respListSet[key]['rec_leave_days']);	
				if(respListSet[key]['leave_sanc_flag']=="Y"){
					EnableInputs();
				}else{
					DisableInputs();
				}
		 	 }
		  });
		}
	});	
	$("#Reco_fromDate").trigger("change");
	if($("#Reco_Fhalf").val()=="Y"){
		$("#Reco_Fhalf").prop('checked', true).trigger("change");
	}
	 if($("#Reco_Shalf").val()=="Y"){
		$("#Reco_Shalf").prop('checked', true).trigger("change");
	}
}
/*******************This is used for View list Initial****************************************************/
 function LoadListTbl(){
	var branchMstId = $("#branchMstId").val();
	$.ajax({
		url : "${pageContext.request.contextPath}/app/common/getHelpList",
 		data : JSON.stringify({
 			"param" :"PLEAVEAPP~ AND t.OP_BRANCH_MST_ID = "+branchMstId+" AND t.LEAVE_SANC_FLAG IS NOT NULL AND t.ACTIVE_FLAG = ''Y'' AND t.DELETE_FLAG = ''N''" ,
 		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function (resp) {
	    	responList =(resp["helpList"]);	
	    	if ($.fn.DataTable.isDataTable('#detailList')) {
                $('#detailList').DataTable().destroy();
            }
            $("#detailList tbody").empty();
        	let keyVal=0;	let datacourt=[];
    		LeaveRecomdList  =(resp["helpList"]);
        	$.each(LeaveRecomdList, function (key,i) {
        		keyVal=keyVal+1;        		
 				datacourt.push([keyVal,LeaveRecomdList[key]['prop4'],LeaveRecomdList[key]['prop5'],LeaveRecomdList[key]['prop6'],LeaveRecomdList[key]['prop7'],LeaveRecomdList[key]['prop8'],
				'<a href="javascript:;" onclick="toggleTableAndForm(\'M\',\''+LeaveRecomdList[key]['prop2']+'\')" class="btn btn-primary btn-sm btn-round" title="Edit">'+
	            '<i class="fa fa-pencil"style="padding: 5px;"></i>'+
	            '</a>&nbsp;']) ; 
        });
       	 $('#detailList').DataTable({
                data: datacourt,
                "autoWidth": false,
                deferRender: true,
                pageLength: 10,
                "bLengthChange": false,
                info: false,
                scrollCollapse: true,
                responsive: true,
                "columnDefs": [
                    {
                        "className": "text-center ",
                        "targets": [0,3,4,6]
                    }  ,
                    {
                        "className": "text-right ",
                        "targets": [5]
                    } 
                   ]
            }); 
 		},
 		failure : function() {
 			console.log("failed to load list.");
 		}		
 	});
 }
 /**********************************************************/
 function getsetInt(){
	var branchMstId = $("#branchMstId").val(); 
	var employeeMstId = $("#userId").val();
	var sqlqueryno = "1008";
	$.ajax({
		url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		data : JSON.stringify({
            param : branchMstId+"~"+employeeMstId,
        	sqlMstId : sqlqueryno,
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	   success: function(response) {		       	    
		   resp = JSON.parse(response["codeList"]);
	    	$.each(resp, function(key,value) {
      	    		$("#Reco_EmpName").val(resp[key]["name"]);
          			$("#Reco_EmpDepartment").val(resp[key]["desig_name"]);
          			$("#deptId").val(resp[key]["dname"]);
	        });
       	}
    });
}
 /*************************************************/
 function GetDetails(){
    let postParametersView={
    		branchId : $("#branchMstId").val(),
   			userId	 : $("#userId").val(),
			EmpMstId : $("#userId").val(),
			desc	 : null,
			frmdate	 : null,
			todate	 : $("#Reco_toDate").val()==""?null:"'"+$("#Reco_toDate").val()+"'"
    	    };
	$.ajax({ 
		url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveApplication/getLeaveApplication",
		data : JSON.stringify(postParametersView),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		success : function(res) {
		if ($.fn.DataTable.isDataTable('#OverView')) {
                $('#OverView').DataTable().destroy();
            }
            $("#OverView tbody").empty();
        	let keyVal=0;	let datacourt=[];
        	 var ListDetails = JSON.parse(res["EmpLeaveDetails"]);
        	 $.each(ListDetails, function (key,i) {
          		keyVal=keyVal+1;        		
   				datacourt.push([keyVal,ListDetails[key]['leave_id'],ListDetails[key]['leave_name'],ListDetails[key]['opening_leaves'],
   	  				ListDetails[key]['total_allotted'],ListDetails[key]['total_used'],ListDetails[key]['bal_leaves']]) ; 
          	 });
        	 	$('#OverView').DataTable({
                 data: datacourt,
                 "autoWidth": false,
                 deferRender: true,
                 pageLength: 10,
                 "bLengthChange": false,
                 info: false,
                 scrollCollapse: true,
                 responsive: true,
                 "columnDefs": [
                     {
                         "className": "display_hide",
                         "targets": [1]
                     } ,
                     {
                         "className": "avil_Leave",
                         "targets": [6]
                     }  
                    ]
             }); 
 		},
 		failure : function() {
 			console.log("failed to load list.");
 		}	
	});
}
 /****************************/ 
function doCheckavil(){
     console.log($("#Reco_leaveDays").val(),"ji",To_apply)
    if($("#Reco_leaveDays").val()>To_apply){
	    $("#Reco_leaveDays").val("")
	  }
}
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptIdF" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<div class="row showTableDiv">
	<div class="col-lg-12">
		<div class="panel newPanel">
			<div class="panel-heading">
				<div class="panel-control">
					<button class="btn btn-default" data-click="panel-expand">
						<i class="fa fa-expand"></i>
					</button>
					<button class="btn btn-default" data-click="panel-reload" onclick="loadListOfLocation();">
						<i class="fa fa-refresh"></i>
					</button>
					<button class="btn btn-default" data-click="panel-collapse">
						<i class="fa fa-chevron-down"></i>
					</button>
					 <button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
				</div>
				<h3 class="panel-title">Employee Leave Recommendation</h3>
			</div>
			<div class="panel-body">		
				<table class="table table-striped table-bordered table-hover locationApplyTable table-responsive" id="detailList">
					<thead>
						<tr>
							<th>Sr. No.</th>
							<th>Employee Name</th>
							<th>Leave Name</th>	
							<th>From Date</th>	
							<th>To Date</th>	
							<th>Day</th>
							<th>Action</th>													
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>								
			</div>
		</div>
	</div>
</div>
<!------------------------------------------------------------>
<div class="row showFormDiv">
	<div class="col-lg-12">
			<div class="panel newpanel">
				<div class="panel-heading">
					<div class="panel-control">
						<button class="btn btn-default" data-click="panel-expand">
							<i class="fa fa-expand"></i>
						</button>
						<button class="btn btn-default" data-click="panel-reload">
							<i class="fa fa-refresh"></i>
						</button>
						<button class="btn btn-default" data-click="panel-collapse">
							<i class="fa fa-chevron-down"></i>
						</button>
						<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()">
							<i class="fa fa-times"></i>
						</button>
						<button onclick="toggleTableAndForm('N',null);" type="button" class="btn btn-success">
						<i class="fa fa-chevron-left"></i>&nbsp; Back to List </button>
					</div>
					<h3 class="panel-title formTitle"> Create New Employee Leave Recommendation </h3>
				</div>
				<div class="panel-body">
					<div class="row" id="tab1" data-role="tab">
						<ul class="nav nav-tabs">
							<li class="active firstTab" >
								<a href="#tabContent1" data-toggle="tab" id="tabLabel1"><spring:message code="label.applicationdetails"></spring:message></a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent2" id="tabLabel2"><spring:message code="label.HeadRecoLeave"></spring:message></a>
							</li>
						</ul>
						<br>
						<div class="tab-content">
						  	<div class="tab-pane fade active in" id="tabContent1">
								<div class="panel-body">
									<div class="row">
										<div class="col-sm-3">
											<div class="form-group">
												<label for="employeeName" class="control-label">
													<spring:message code="label.employeeName"></spring:message>
												</label>
												<input name="Apply_userId" type="hidden" class="form-control" data-toggle="tooltip"  size="60" maxlength="200"  id="Apply_userId"  disabled>
												<input name="employeeName" type="text" class="form-control" data-toggle="tooltip" name="employeeName" 
												  size="60" maxlength="200"  id="Apply_employeeName"  disabled>
												  <small style="color: red"></small>
											</div>	
										</div>		
										<div class="col-sm-3">
											<div class="form-group">
												<label for="Designation" class="control-label">
													<spring:message code="label.Designation"></spring:message>
												</label>
												<input name="Designation" type="text" class="form-control" data-toggle="tooltip" name="Designation" 
												  size="60" maxlength="200"  id="Apply_Designation"  disabled>
												  <small style="color: red"></small>
											</div>
										</div>
										<div class="col-sm-3">
											<div class="form-group">
												<label for="deptId" class="control-label">
													<spring:message code="label.deptId"></spring:message>
												</label>
												<input name="deptId" type="text" class="form-control" data-toggle="tooltip" name="Apply_deptId"
												  size="60" maxlength="200"  id="Apply_deptId" disabled >
												  <small style="color: red"></small>
											</div>
										</div>
										<div class="col-sm-3">
											<div class="form-group">
												<label for="leaveName" class="control-label">
													<spring:message code="label.leaveName"></spring:message></label>
												<input name="leaveName" type="hidden" class="form-control" data-toggle="tooltip" disabled id="Apply_leaveNameId">
												<input name="leaveName" type="text" class="form-control" data-toggle="tooltip" disabled id="Apply_leaveName">
												<small style="color: red"></small>
											</div>
										</div>
									</div>
									<!-- --------------------------------------------- -->
									<div class="row">												
										<div class="col-sm-3">
											<div class="form-group">
												<div class="form-group has-feedback">	
													<label for="applicationDate" class="control-label">
														<spring:message code="label.applicationDate"></spring:message></label>
													<input name="applicationDate" type="text" class="form-control" data-toggle="tooltip" id="Apply_applicationDate" disabled>
													<span class="fa fa-calendar fa-lg form-control-feedback"></span>
													<small style="color: red"></small>
												</div>
											</div>
										</div>
										<div class="col-sm-3">
											<div class="form-group">
												<div class="form-group has-feedback">	
													<label for="leaveFromDate" class="control-label">
														<spring:message code="label.leaveFromDate"></spring:message></label>
													<input name="leaveFromDate" type="text" class="form-control" data-toggle="tooltip" id="Apply_leaveFromDate" disabled>
													<span class="fa fa-calendar fa-lg form-control-feedback"></span>
													<input type="checkbox" value="N" id="Apply_Fhalf" disabled>Half Day
													<small style="color: red"></small>
												</div>
											</div>
										</div>
										<div class="col-sm-3">
											<div class="form-group">
												<div class="form-group has-feedback">	
													<label for="leaveToDate" class="control-label">
														<spring:message code="label.leaveToDate"></spring:message></label>
													<input name="leaveToDate" type="text" class="form-control" data-toggle="tooltip" id="Apply_leaveToDate" disabled
													 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.leaveToDate"></spring:message>">
													<span class="fa fa-calendar fa-lg form-control-feedback"></span>
													<input type="checkbox" value="N" id="Apply_Shalf" disabled>Half Day
													<small style="color: red"></small>
												</div>
											</div>
										</div>
										<div class="col-sm-3">
											<div class="form-group">
												<label for="applyLeaveDays" class="control-label">
													<spring:message code="label.applyLeaveDays"></spring:message>
												</label>
												<input name="applyLeaveDays" type="text" class="form-control" disabled data-toggle="tooltip" 
												  size="60" maxlength="200"  id="Apply_applyLeaveDays"  >
												  <small style="color: red"></small>
											</div>
										</div>
									</div>
									<!-- ----------------------------------------------------------- -->
									<div class="row">
										<div class="col-sm-3">
											<div class="form-group">
												<label for="publicHoliday" class="control-label">
													<spring:message code="label.publicHoliday"></spring:message>
												</label>
												<input name="publicHoliday" type="text" class="form-control" disabled data-toggle="tooltip"
												 placeholder="<spring:message code="label.publicHoliday"></spring:message>" title="<spring:message code="label.publicHoliday"></spring:message>"
												  size="60" maxlength="200"  id="Apply_publicHoliday"  >
												  <small style="color: red"></small>
											</div>
										</div>
										<div class="col-sm-3">
											<div class="form-group">
												<label for="leaveDays" class="control-label">
													<spring:message code="label.leaveDays"></spring:message>
												</label>
												<input name="leaveDays" type="text" class="form-control" disabled data-toggle="tooltip" 
												  size="60" maxlength="200"  id="Apply_leaveDays"  >
												  <small style="color: red"></small>
											</div>
										</div>												
										<div class="col-sm-3">
											<div class="form-group">
												<label for="recoEmpName" class="control-label">
													<spring:message code="label.recoEmpName"></spring:message></label>
												<input name="recoEmpName" class="form-control" data-toggle="tooltip" disabled id="Apply_recoEmpName">
												<small style="color: red"></small>
											</div>
										</div>										
										<div class="col-sm-3">
											<div class="form-group">
												<label for="reasonCodeId" class="control-label">
													<spring:message code="label.reasonCodeId"></spring:message></label>
												<input type="hidden" name="reasonCodeIdAply" class="form-control Advocate" data-toggle="tooltip"  
												  title="Select <spring:message code="label.reasonCodeId"></spring:message>"  id="Apply_reasonCodeId">
												<input type="text" name="reasonCodeNameAply" class="form-control Advocate" data-toggle="tooltip"  disabled
												  title="Select <spring:message code="label.reasonCodeId"></spring:message>"  id="Apply_reasonCodeName">
												</div>
										</div>
									</div>
									<!-- -------------------------------------------------------------------- -->
									<div class="row">
										<div class="col-sm-6">
											<div class="form-group">
												<label for="leaveDaysAddress"  class=" control-label">
													<spring:message code="label.leaveDaysAddress"></spring:message></label>
												<textarea name="leaveDaysAddress" class="form-control" disabled data-toggle="tooltip"
												 rows="3" maxlength="2000"  id="Apply_leaveDaysAddress" style='resize: vertical;'></textarea>
											<small style="color: red"></small>
											</div>
										</div>
											<div class="col-sm-6">
											<div class="form-group">
												<label for="reason"  class="control-label">
													<spring:message code="label.reason"></spring:message></label>
												<textarea name="reason" class="form-control" disabled data-toggle="tooltip"												
												 rows="3" maxlength="2000"  id="Apply_reason"  style='resize: vertical;'></textarea>
											<small style="color: red"></small>
											</div>
										</div>
									</div>							
								</div>
							</div>
							<!-- ---------------------------Second Tab For Recommendation------------------------>
							<div class="tab-pane fade" id="tabContent2">
								<div class="row">
									<form id="LeaveRecomd">	
										<div class="col-sm-5 FirstCol" >
										<div class="row">
											<div class="col-sm-12">
												<div class="form-group">
													<label for="recoEmpName" class="control-label LblImp">
														<spring:message code="label.recoEmpName"></spring:message>
													</label>
													<input name="recoEmpName" type="text" class="form-control mandatory" data-toggle="tooltip" 
													 placeholder="Enter <spring:message code="label.recoEmpName"></spring:message>"  title="Enter Party Filling Case" 
													  size="60" maxlength="200"  id="Reco_EmpName" required disabled>
												</div>
											</div>
										</div>
										<!------------------------------------------------------------>
										<div class="row">
											<div class="col-sm-6">
												<div class="form-group">
													<label for="recoEmpDepartment" class="control-label">
														<spring:message code="label.recoEmpDepartment"></spring:message>
													</label>
													<input name="recoEmpDepartment" type="text" class="form-control mandatory" data-toggle="tooltip"
													 placeholder="Enter <spring:message code="label.recoEmpDepartment"></spring:message>"  title="Enter Party Filling Case" 
													  size="60" maxlength="200"  id="Reco_EmpDepartment"  disabled>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<div class="form-group has-feedback">	
														<label for="recomendDate" class="control-label LblImp">
															<spring:message code="label.recomendDate"></spring:message></label>
														<input name="recomendDate" type="text" class="form-control mandatory" data-toggle="tooltip" id="Reco_Date" required
														 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.recomendDate"></spring:message>">
														<span class="fa fa-calendar fa-lg form-control-feedback"></span>
													</div>
												</div>
											</div>
										</div>
										<!------------------------------------------------------------>
											<div class="row">
											<div class="col-sm-6">
												<div class="form-group">
													<div class="form-group has-feedback">	
														<label for="fromDate" class="control-label LblImp">
															<spring:message code="label.fromDate"></spring:message></label>
														<input name="fromDate" type="text" class="form-control mandatory" data-toggle="tooltip" id="Reco_fromDate" readonly required
														 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.fromDate"></spring:message>">
														<span class="fa fa-calendar fa-lg form-control-feedback"></span>
														<input type="checkbox" value="N" id="Reco_Fhalf">Half Day
														<small style="color: red"></small>
													</div>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<div class="form-group has-feedback">	
														<label for="toDate" class="control-label LblImp">
															<spring:message code="label.toDate"></spring:message></label>
														<input name="toDate" type="text" class="form-control mandatory" data-toggle="tooltip" id="Reco_toDate" readonly required
														 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  title="Enter <spring:message code="label.toDate"></spring:message>">
														<span class="fa fa-calendar fa-lg form-control-feedback"></span>
														<input type="checkbox" value="N" id="Reco_Shalf">Half Day
														<small style="color: red"></small>
													</div>
												</div>
											</div>
											</div>
											<!------------------------------------------------------------>
											<div class="row">
											<div class="col-sm-6">
												<div class="form-group">
													<label for="RecLeaveDays" class="control-label LblImp">
														<spring:message code="label.RecLeaveDays"></spring:message>
													</label>
													<input name="RecLeaveDays" type="text" class="form-control" data-toggle="tooltip" required
													 placeholder="Enter <spring:message code="label.RecLeaveDays"></spring:message>"  title="Enter Party Filling Case" 
													  size="60" maxlength="200"  id="Reco_recomedLeaveDays"  disabled>
												</div>											
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<label for="publicHoliday" class="control-label LblImp">
														<spring:message code="label.publicHoliday"></spring:message>
													</label>
													<input name="publicHoliday" type="text" class="form-control mandatory" data-toggle="tooltip" required
													 placeholder="Enter <spring:message code="label.publicHoliday"></spring:message>"  title="Enter Party Filling Case" 
													  size="60" maxlength="200"  id="Reco_publicHoliday"  >
												</div>																								
											</div>
											</div>
											<!-- ----------------------------------------- -->
											<div class="row">
											<div class="col-sm-6">
												<div class="form-group">
													<label for="leaveDays" class="control-label LblImp">
														<spring:message code="label.leaveDays"></spring:message>
													</label>
													<input name="leaveDays" type="text" class="form-control mandatory" data-toggle="tooltip" required
													 placeholder="Enter <spring:message code="label.leaveDays"></spring:message>"  title="Enter Party Filling Case" 
													  size="60" maxlength="200"  id="Reco_leaveDays"  disabled>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<label for="recomendLeaveName" class="control-label LblImp">
														<spring:message code="label.recomendLeaveName"></spring:message>
													</label>
													<select name="recomendLeaveName" class="form-control mandatory" data-toggle="tooltip" required
													 title="Enter Party Filling Case"  id="Reco_recomendLeaveName"  ></select>
												</div>
											</div>
											</div>
											<!-- ------------------------------------------ -->
											<div class="row">
											<div class="col-sm-6">
												<div class="form-group">
													<label for="leaveRecomendFlag" class="control-label LblImp">
														<spring:message code="label.leaveRecomendFlag"></spring:message></label>
													<select name="leaveRecomendFlag" class="form-control mandatory" data-toggle="tooltip"  required
													  title="Select <spring:message code="label.leaveRecomendFlag"></spring:message>"  id="Reco_leaveRecomendFlag">
													<option value="Y">Yes</option>
													<option value="N">No</option>
													</select>
												</div>
											</div>
											<div class="col-sm-6">
												<div class="form-group">
													<label for="reasonCodeId" class="control-label LblImp">
														<spring:message code="label.reasonCodeId"></spring:message></label>
													<select name="reasonCodeId" class="form-control mandatory" data-toggle="tooltip"  required
													  title="Select <spring:message code="label.reasonCodeId"></spring:message>"  id="Reco_reasonCodeId">
													</select>
												</div>
											</div>
											</div>
											<!-- ------------------------------------------ -->
											<div class="row">
											<div class="col-sm-12">
												<div class="form-group">
													<label for="sancReason"  class=" control-label ">
														<spring:message code="label.sancReason"></spring:message></label>
													<textarea name="sancReason" class="form-control" data-toggle="tooltip" 
													 placeholder="Enter Subject Matter"  title="Enter <spring:message code="label.sancReason"></spring:message>" 
													 rows="3" maxlength="2000"  id="Reco_sancReason"  style='resize: vertical;'></textarea>
												<small style="color: red"></small>
												</div>										
											</div>
											</div>
										</div>
										<!-- -------------------------------------------------------------------------------------------------- -->
										<div class="col-sm-7">
											<table class="table table-striped table-bordered table-hover locationMasterTable table-responsive" id="OverView">
											<thead>
												<tr>
													<th>Sr. No.			</th><th>Leave id</th>
													<th>Leave Type      </th>
													<th>Opening Leave   </th>
													<th>Total Alloted Leave </th>
													<th>Used Leave      </th>
													<th>Available Leave </th>
												</tr>
											</thead>
											</table>
										</div>														
									</form>
								</div>
								<div class="col-sm-12">
								<hr>
									<button  class="btn btn-primary submitBtnName" type="button" id="SaveLeaveRecomd">
									 <i class="fa fa-save"></i>Save Employee Leave Recommendation
									</button>
									&nbsp;
									<button type="button" class="btn resetBtnName btn-danger" id="ResetLeaveRecomd" onclick="resetForm()">
									Reset
									</button>
								</div>
							</div>	
						</div>					
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
<script src="assets/js/validation.js"></script>
</html>