<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - SANKER EPS -Aishwarya Domde      
Creation Date	- Apr 25, 2019 2:34:15 PM 
Project Name	- MLWB 
Module Name		- PayRoll
Page			- Leave Application
Description		- Leave Application
Link			-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employee Leave Application</title>
<link href="assets/css/style.css" rel="stylesheet">
<link href="assets/plugins/switchery/switchery.min.css" rel="stylesheet">
 <!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>
<link rel="stylesheet" type="text/css"href="assets/plugins/daterange_new/daterangepicker.css" />
<script type="text/javascript"src="assets/plugins/daterange_new/daterangepicker.js"></script>
<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Data Parsley [ OPTIONAL ]-->
<script src="assets/plugins/parsley/parsley.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Jquery Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>
<script src="assets/plugins/switchery/switchery.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<link href="assets/plugins/pretty-checkbox/pretty-checkbox.min.css" rel="stylesheet">
<script src="assets/js/focusOnEnter.js"></script>
<!--Tabbable JS -->
<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<style>
.display_hide{
display: none;
}
.LblImp:after{
	content:"*";
	color:red;
}
th.sorting {
    text-align: center;
}
@media screen and (min-height: 500px) {
  .FirstCol {
    overflow-y: auto;    max-height: 56vh;
  }
}
.row{margin-top: 3px;margin-bottom: 3px;}
</style>
<script type="text/javascript">
let global_LeaveApplyId  = 0;
let op_flag = "N";
let showForm = false;
let showTable = true;
let formValidator=null, To_apply;
var myDate = new Date();
var TodaySet = myDate.getDate() + '/' +(myDate.getMonth()+1) + '/' +myDate.getFullYear();
$(document).ready(function() {	
	$('.showTableDiv').show(); 
	$('.showFormDiv').hide();
	LoadListTbl();
	validateForm();
	GetDetails();
	$("#leaveType").alphanum();
	$("#leaveName").alphanum();
	$("#publicHoliday").numeric({negative: false}).addClass("speech-right numbersOnly");
	$("#leaveDays,#applyLeaveDays").numeric({decimalPlaces: 2 ,negative: false}).addClass("speech-right");
	$("#leaveToDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	      minDate:'0'
	 }); 
	$("#leaveFromDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate:'0'
	 }); 
	$("#applicationDate").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	    minDate: '0',
	    maxDate: '0',
	 });
	$("select").select2({
		placeholder:"Select",
		width:'100%',
		multiple:false,
		allowClear:true,		
	});
	$('form').find('input,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	/*********************************************************************/
	$('form').on('keyup change paste blur select2:close', 'input, select, textarea, button, a', function(event){
		let elem = event.target;
		let elValid = false;
		if (!$(elem).valid()) {
			elValid = true;
	    }
	    $('.mandatory').each(function() {
	    	if ($(this).val()=='' || $(this).val()==null) {
				elValid = true;
	        }
	    });
	    if (elValid) {
	    	$('.submitBtnName').attr('disabled', 'disabled');
	    } else {
	    	$('.submitBtnName').removeAttr('disabled');
	    }
	});
	/*********************************************************************/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getHelpList",//getHelpList==branchMstId
		data : JSON.stringify({
		"param" :"PLEAVEHELP~"
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(respp){
	    	resp = (respp["helpList"]);
	    	$("#leaveName").empty().append("<option></option>");
	    	$.each(resp, function(key,value) {
		    	console.log(resp[key].prop8)
	    	    if(resp[key].prop8=="Y"){
					nKey = parseInt(key)+1;
					$("#leaveName").append('<option value="'+resp[key].prop2+'"> '+resp[key].prop3);}
			}); 
	      },
	 });
	/****************************************************************/
	$.ajax({
		url : "${pageContext.request.contextPath}/app/common/getHelpList",
		data : JSON.stringify({
		"param" :"LEAVE_EMPLIST~"
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function (resp) {
	    	responList =(resp["helpList"]);	
	    	let listOfEmpOptions = '<optgroup class="def-cursor" label="Name" data-id="Id" data-design="Designation" data-Dep="Department" >';
			var optGrpEnd = '</optgroup>';
			var optionsList='';
				$.each(responList, function (key,i) {
					optionsList = optionsList+'<option value="'+responList[key]["prop2"]+'" data-id="'+responList[key]["prop2"]+'" data-name="'+responList[key]["prop4"]+
					'" data-design="'+responList[key]["prop8"]+'" data-Dep="'+responList[key]["prop9"]+'">'+responList[key]["prop4"]+'</option>';
		 		});
			 optionsList=listOfEmpOptions+optionsList+optGrpEnd;
	       	 $("#recoEmpName").empty().append(optionsList);
	       	 $('#recoEmpName').select2({
	    		    width: '100%',
	    			placeholder:"Select",
	    			allowClear: true,
	    		    templateResult: formatResultMulti,
	    		}).on('change',function(){
	    			if($(this).val()==null){
	    				resetForm();
	    			}
	    		});	 
		},
		failure : function() {
			console.log("failed to load list.");
		}		
	});
 	/****************************************************/
	$.ajax({  
		url : "${pageContext.request.contextPath}/app/common/getCodeList",
	    type:'post',  
	    dataType:'json',
	    data : JSON.stringify({
	    	sqlMstId : "107",
	    	param : 35+"~"+"null"
	    }),
	    method : "post",
		dataType : "json",
		async : false,
		contentType : "application/json",
		success : function(resp) {
			responList_resnid =JSON.parse(resp["codeList"]);
			let listOfEmpOptions2= '<optgroup class="def-cursor" label="Reason ID" data-id2="Reason Id" data-design2="Reason" >';
			var optGrpEnd = '</optgroup>';
			var optionsList_resnid='';	
				$.each(responList_resnid, function (key,i) {
					optionsList_resnid = optionsList_resnid+'<option value="'+responList_resnid[key]["code"]+'" data-id2="'+responList_resnid[key]["code"]
					+'" data-design2="'+responList_resnid[key]["description"]+'">'+responList_resnid[key]["description"]+'</option>';
		 		});
			 optionsList_resnid=listOfEmpOptions2+optionsList_resnid+optGrpEnd;
	       	 $("#reasonCodeId").empty().append(optionsList_resnid);
	       	 $('#reasonCodeId').select2({
	    		    width: '100%',
	    			placeholder:"Select",
	    			allowClear: true,
	    		    templateResult: formatResultMulti2,
	    		});
		},
		failure : function() {
			console.log("failed to load list.");
		}		
	});
	/**********************For Checking whether leaves are available of not*******************************************/
	$("#leaveName").on("select2:select change",function(){
		let SLeaveName = $(this).val();
		let Tbl_LeaveName,isAvil,applied;
		 /***************For leave without pay9**************/
		$('#OverView tbody>tr>td:nth-child(2).display_hide').each(function() {
			Tbl_LeaveName =$(this).text();
			if(Tbl_LeaveName==SLeaveName && SLeaveName!="6"){
				isAvil=$(this).nextAll('td').closest(".avil_Leave").text();
				if(isAvil=="0"){
					$("#leaveName").select2('destroy'); 
					$("#leaveName").select2({placeholder:"Select",
			 				width:'100%',
			 				multiple:false,
			 				allowClear:true,					
			 		});
					$("#leaveName").find('.select2-container').tooltipster({
			 			    functionInit: function(instance, helper){
			 			        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
			 			        instance.content(content);
			 			    },
			 			    delay: 100,
			 			    theme: 'tooltipster-punk',
			 			    side: 'bottom'
			 			}); 
					$("select").find('option').each(function(i) {
						$('#leaveName option[value='+SLeaveName+']').attr('disabled','disabled');
					});
					$("#leaveName").val("").trigger("change");
					$("#leaveName").siblings('small').append("Please select another Leave,this leave type not available");
				}
			}
			/***********************************************/			
		    $.ajax({  
			    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
			    data : JSON.stringify({
					"param" : SLeaveName+"~"+$("#userId").val(),
					"sqlMstId" :7338
				}),
				method : "post",
				dataType : "json",
				contentType : "application/json",
				async: false,
			    success: function(response){
			    	let resp = JSON.parse(response["codeList"])
			    	applied=(resp[0].pending_sanction_leave)
			      },
			 });
			if(SLeaveName==Tbl_LeaveName){
			    To_apply= ($(this).closest("tr").find(".avil_Leave").text()-applied)
			}
			
		});
	});
	 /******************************************************************/
	 $("#SaveLeaveApply").on("click",function(){
		 if($("#LeaveApply").valid()){
			 let Flgchck1= "N";	 let Flgchck2= "N";
			 	if($("#Fhalf").is(":checked")){
			 		Flgchck = "Y";
				}else{
					Flgchck= "N";
				}
			 	if($("#Shalf").is(":checked")){
			 		Flgchck2 = "Y";
				}else{
					Flgchck2= "N";
				}
				let postParameters = {
						employeeName	:$("#employeeName").val(),
						recoEmpName		:$("#recoEmpName").val(),
						reasonCodeId	:$("#reasonCodeId").val(),
						deptId			:$("#deptId").val(),
						Designation		:$("#Designation").val(),
						leaveName		:$("#leaveName").val(),
						applicationDate :$("#applicationDate").val(),
						leaveFromDate	:$("#leaveFromDate").val(),
						leaveToDate		:$("#leaveToDate").val(),
						applyLeaveDays	:$("#applyLeaveDays").val(),
						publicHoliday	:$("#publicHoliday").val(),
						leaveDays		:$("#leaveDays").val(),
						leaveDaysAddress:$("#leaveDaysAddress").val(),
						reason			:$("#reason").val(),
						opFlag	  		: op_flag,
						userId			: $("#userId").val(),
						branchMstId		: $("#branchMstId").val(),
						LeaveId    		: global_LeaveApplyId,
						Fhalf			: Flgchck,
						Shalf			: Flgchck2
			};
			if(op_flag=="D"){
				$.confirm({
	                title: 'Are you sure want to delete ?',
	                content: '',
	                type: 'blue',
	                buttons: {
			            Delete: {			              
			                action: function () {
			                   deleteRecord(postParameters);
			                }
			            },
			            Cancel: {
			                keys: ['N'],
			                action: function () {
			                	$('.showFormDiv').hide();
			                    $('.showTableDiv').show();
			                }
			            },
			        }
	            }); 
			}else if(op_flag=="M" || op_flag=="N"){
				$.ajax({
					url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveApplication/SaveEmpLeaveApply",
					data : JSON.stringify(postParameters),
					method : "post",
					dataType : "json",
					contentType : "application/json",
					success : function(res) {
					 	if (JSON.parse(res["responseObj"]).status == "success") {
				         	toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
				            closeButton: true,
				            positionClass: 'toast-bottom-right'
				          });
				          showForm = true;
				          EnableInputs();
				          resetForm();
				          LoadListTbl();
				          DisableInputs();
				        } else {
				          	toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
				            closeButton: true,
				            positionClass: 'toast-top-right'
				          });
				        }
					}
				});
			}
		 }
	 });
	/*****************************************************/
 	$('.select2-container').tooltipster({
 	    functionInit: function(instance, helper){
 	        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
 	        instance.content(content);
 	    },
 	    delay: 100,
 	    theme: 'tooltipster-punk',
 	    side: 'bottom'
 	});
 	/****************************************************/	
 	$("#leaveToDate ,#leaveFromDate").on("change",function(){
 	 	var LeaveToDate = $("#leaveToDate").val();
 	 	var leaveFromDate = $("#leaveFromDate").val();
 	 	if(leaveFromDate!="" && LeaveToDate!=""){
 		$.ajax({  
 			url : "${pageContext.request.contextPath}/app/common/getCodeList",
 		    type:'post',  
 		    dataType:'json',
 		    data : JSON.stringify({
 		    	sqlMstId : "7125",
 		    	param : "''D'',''"+leaveFromDate+"'',''"+LeaveToDate+"''"
 		    }),
 		    method : "post",
 			dataType : "json",
 			async : false,
 			contentType : "application/json",
 			success : function(resp) {
 				responList =JSON.parse(resp["codeList"]);
 				$("#applyLeaveDays").val(responList[0].days_leave);
 				doCheckavil()
 	 		}
 		}); 	
 	}
 	$("#publicHoliday").trigger("change");
 	});
 	/****************************************************/
 	$("input[type=checkbox]").on("change",function(){
		var AplyLeave = $("#applyLeaveDays").val();
		var totalAplyLeave;
 	 	var LeaveToDate = $("#leaveToDate").val();
 	 	var leaveFromDate = $("#leaveFromDate").val();
	 	if(LeaveToDate!=""&&leaveFromDate!=""){ 	 
			if($(this).is(":checked")){
				totalAplyLeave =parseFloat(AplyLeave) - Number(0.5);
				$("#applyLeaveDays").val(totalAplyLeave);
			 	$("#leaveDays").val(totalAplyLeave);
			}else{
				totalAplyLeave =parseFloat(AplyLeave) + Number(0.5);
				$("#applyLeaveDays").val(totalAplyLeave);
			 	$("#leaveDays").val(totalAplyLeave);
				}
	 	 }
	 	doCheckavil()
	});
	/***************************************************/
	$("#publicHoliday").on("change",function(){
		var AplyLeave = $("#applyLeaveDays").val();
		var publicHoliday = $("#publicHoliday").val();
		if(AplyLeave>publicHoliday){
		var totalAplyLeave =parseFloat(AplyLeave) - Number(publicHoliday);
		if(totalAplyLeave>=0){
		$("#leaveDays").val(totalAplyLeave);}else{$("#leaveDays").val("");}
		}else{
			$("#publicHoliday").val(0);
			$("#leaveDays").val(AplyLeave);
			}
		doCheckavil()
	});
})
function doCheckavil(){
    if($("#leaveDays").val()>To_apply){
	    $("#leaveDays").val("")
	  }
}
/*************************Document Ready over function starts Reset Settings*************************/
function resetForm(){
	if($('#recoEmpName').val()!=null){
		 $('#recoEmpName').val(null).trigger('change');
	}
	if($('#reasonCodeId').val()!=null){
		 $('#reasonCodeId').val(null).trigger('change');
	}
	$("#Shalf").prop('checked', false);
	$("#Fhalf").prop('checked', false);
	$("#leaveName").val("").trigger('change');
	$("#leaveFromDate").val("");
	$("#leaveToDate").val("");
	$("#applyLeaveDays").val("");
	$("#publicHoliday").val("");
	$("#leaveDays").val("");
	$("#leaveDaysAddress").val("");  
	$("#reason").val(""); 
	 $("#applicationDate").val(TodaySet);
	op_flag="N";
	global_LeaveApplyId=0;
	EnableInputs();
 	formValidator.resetForm();
}
/******************************Disable Fields**********************************************/
 function DisableInputs(){
	 $("#reasonCodeId").attr('disabled', 'disabled');
	 $("#recoEmpName").attr('disabled', 'disabled');
	 $("#leaveName").attr('disabled', 'disabled');
	 $("#applicationDate").attr('disabled', 'disabled');
	 $("#leaveFromDate").attr('disabled', 'disabled');
	 $("#leaveToDate").attr('disabled', 'disabled');
	 $("#publicHoliday").attr('disabled', 'disabled');
	 $("#leaveDaysAddress").attr('disabled', 'disabled');  
	 $("#reason").attr('disabled', 'disabled'); 
}
/******************************Disable Fields**********************************************/
 function EnableInputs(){
	 $("#reasonCodeId").removeAttr('disabled');
	 $("#recoEmpName").removeAttr('disabled');
	 $("#leaveName").removeAttr('disabled');
	 $("#applicationDate").removeAttr('disabled');
	 $("#leaveFromDate").removeAttr('disabled');
	 $("#leaveToDate").removeAttr('disabled');
	 $("#publicHoliday").removeAttr('disabled');
	 $("#leaveDaysAddress").removeAttr('disabled');  
	 $("#reason").removeAttr('disabled'); 
 }
 /********************for column creation in select2************************************/
 function formatResultMulti2(data) {
	  var design = $(data.element).data('design2');
	  var id = $(data.element).data('id2');
	  var classAttr = $(data.element).attr('class');
	  var hasClass = typeof classAttr != 'undefined';
	  classAttr = hasClass ? ' ' + classAttr : '';
	  var $result = $(
	    '<div class="row" id=' + id + '>' +
	    '<div class="col-md-4 col-xs-4' + classAttr + '">' +id  + '</div>' +
	    '<div class="col-md-8 col-xs-8' + classAttr + '">' + design + '</div>'  +
	    '</div>'
	  );
	  return $result;
}
 /********************for column creation in select2************************************/
 function formatResultMulti(data) {
 		  var design = $(data.element).data('design');
 		  var Dep = $(data.element).data('dep');  
 		  var id = $(data.element).data('id');  
 		  var name = $(data.element).data('name');
 		  var classAttr = $(data.element).attr('class');
 		  var hasClass = typeof classAttr != 'undefined';
 		  classAttr = hasClass ? ' ' + classAttr : '';
 		  var $result = $(
 		    '<div class="row" id=' + id + '>' +
 		    '<div class="col-md-1 col-xs-1' + classAttr + '">' + id + '</div>' +
 		    '<div class="col-md-4 col-xs-4' + classAttr + '">' +  data.text + '</div>' +
 		    '<div class="col-md-3 col-xs-3' + classAttr + '">' + design + '</div>'  +
 		    '<div class="col-md-3 col-xs-3' + classAttr + '">' + Dep + '</div>' +
 		    '</div>'
 		  );
 		  return $result;
 }
 /**********************************Validate Form*************************************/
 function validateForm(){
 	formValidator = $("#LeaveApply").validate({
         rules: {
        	"employeeName": {required: true},
        	"recoEmpName": {required: true},
        	"leaveName": {required: true},
        	"applicationDate": {required: true},
        	"leaveFromDate": {required: true},
        	"leaveToDate": {required: true},
        	"applyLeaveDays": {required: true},
        	"publicHoliday": {required: true},
        	"leaveDays": {required: true},
        	"leaveDaysAddress": {required: true},  
        	"reason": {required: true}, 
         	},
         messages: {
        	"employeeName": {required: "Please select employee Name"},
        	"recoEmpName": {required: "Please select Recommend Emp Name"},
        	"leaveName": {required: "Please select Leave Name"},
        	"applicationDate": {required: "Please select application Date"},
        	"leaveFromDate": {required: "Please select leave From Date"},
        	"leaveToDate": {required: "Please select leave To Date"},
        	"applyLeaveDays": {required: "Please select apply Leave Days"},
        	"publicHoliday": {required: "Please select public Holiday"},
        	"leaveDays": {required: "Please select leave Days"},
        	"leaveDaysAddress": {required: "Please select leave Days Address"},  
        	"reason": {required: "Please select Leave reason"}, 
          },
         highlight: function (element, errorClass, validClass) {
         	if($(element).hasClass('mandatory')){
         		var elem = $(element);
                 elem.addClass(errorClass);
                 elem.siblings('.select2-container').addClass(errorClass); 
         	}
         },    
         unhighlight: function (element, errorClass, validClass) {
               var elem = $(element);
               elem.removeClass(errorClass);
               elem.siblings('.select2-container').removeClass(errorClass);
               elem.siblings('small').empty();
         },
         errorPlacement: function(error, element) {
             $(element).siblings('small').empty().html(error);
          },
         submitHandler: function (form) {
         	e.preventDefault(e);
             return false; 
         }
     });
 }
 /*************************************Toggle table and Form*********************************************/
 function toggleTableAndForm(flag, empMstId) {
 	if (showForm) {
 		showForm = false;
 		showTable = true;
 		$('.showTableDiv').show();
 		$('.showFormDiv').hide();
 	} else {
 		if (flag == 'M') {
 			$("#ResetLeaveApply").hide();
 			$('.formTitle').html('Update Employee Leave Application');
 			$('.submitBtnName').html('<i class="fa fa-save"></i> Update Employee Leave Application ');
 			EnableInputs();
 			resetForm(); 
 			getsetInt();		
 			setFormData(empMstId);
 			GetDetails();	
 			op_flag = "M";	
 		}
 		if (flag == 'N') {	
 			$("#ResetLeaveApply").show();	
 			$('.formTitle').html('Create New Employee Leave Application ');
 			$('.submitBtnName').html('<i class="fa fa-save"></i> Save Employee Leave Application ');
 			$('.submitBtnName').attr('disabled', 'disabled');
 			EnableInputs(); 			
 			resetForm();
 			getsetInt();
 			GetDetails();
     		$('.showTableDiv').show();
 		}
 		if (flag == 'D') {
 			$("#ResetLeaveApply").hide();
 			$('.formTitle').html('<i class="fa fa-save"></i> Delete  Employee Leave Application');
 			$('.submitBtnName').html('Delete Employee Leave Application ');
 			op_flag = "D"; 	
 			getsetInt();		
 			setFormData(empMstId);
 			DisableInputs();	
 			GetDetails();
 			$('.submitBtnName').removeAttr('disabled');
 		}
 		showForm = true;
 		showTable = false;
 		$('.showTableDiv').hide();
 		$('.showFormDiv').show();
 	}	$('#detailList').DataTable().columns.adjust().responsive.recalc();
 }
 /**********************************************************************/
 function deleteRecord(postParameters){
 	$.ajax({
 		url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveApplication/SaveEmpLeaveApply",
 		data : JSON.stringify(postParameters),
 		method : "post",
 		dataType : "json",
 		contentType : "application/json",
 		success : function(res) {
 		 	if (JSON.parse(res["responseObj"]).status == "success") {
 	          toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
 	            closeButton: true,
 	            positionClass: 'toast-bottom-right'
 	          });
 	          resetForm();
 	          LoadListTbl();
 	          DisableInputs();
 	        } else {
 	          toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
 	            closeButton: true,
 	            positionClass: 'toast-bottom-right'
 	          });
 	        }
 		}
 	});
 }
 /***************************************************/
 function LoadListTbl(){
	var branchMstId=$("#branchMstId").val();
	var employeeMstId=$("#userId").val();
 	$.ajax({
 		url : "${pageContext.request.contextPath}/app/common/getHelpList",//getHelpList==branchMstId
 		data : JSON.stringify({
 			"param" 	:"PLEAVEAPP~ AND t.OP_BRANCH_MST_ID = "+branchMstId+ " AND t.employee_mst_id = "+employeeMstId+" AND t.ACTIVE_FLAG = ''Y'' AND t.DELETE_FLAG = ''N''" ,
 		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
        success: function (resp) {
        	if ($.fn.DataTable.isDataTable('#detailList')) {
                $('#detailList').DataTable().destroy();
            }
            $("#detailList tbody").empty();
        	let keyVal=0;	let datacourt=[];
    		LeaveApplyList  =(resp["helpList"]);
        	$.each(LeaveApplyList, function (key,i) {
        		keyVal=keyVal+1;        		
 				datacourt.push([keyVal,LeaveApplyList[key]['prop4'],LeaveApplyList[key]['prop5'],LeaveApplyList[key]['prop6'],LeaveApplyList[key]['prop7'],
				'<a href="javascript:;" onclick="toggleTableAndForm(\'M\',\''+LeaveApplyList[key]['prop2']+'\')" class="btn btn-primary btn-sm btn-round" title="Edit">'+
	            '<i class="fa fa-pencil"style="padding: 5px;"></i>'+
	            '</a>&nbsp;'+
	            '<a href="javascript:;" onclick="toggleTableAndForm(\'D\',\''+LeaveApplyList[key]['prop2']+'\')" class="btn btn-danger btn-sm btn-round" title="Delete">'+
	            '<i class="fa fa-trash" style="padding: 5px;"></i>'+
	            '</a>']) ; 
        });
       	 $('#detailList').DataTable({
                data: datacourt,
                "autoWidth": false,
                deferRender: true,
                pageLength: 10,
                "bLengthChange": false,
                info: false,
                scrollCollapse: true,
                responsive: true,
                "columnDefs": [
                    {
                        "className": "text-center ",
                        "targets": [0,3,4,5]
                    }  
                   ]
            }); 
 		},
 		failure : function() {
 			console.log("failed to load list.");
 		}		
 	});
 }
 /************************************************************/
 function setFormData(empMstId){
	    var branchMstId = $("#branchMstId").val(); 
		var employeeMstId = $("#userId").val();
		var sqlqueryno = "197";
		$.ajax({
			url:"${pageContext.request.contextPath}/app/common/getCodeList",  
			data : JSON.stringify({
	            param :empMstId,
	        	sqlMstId : sqlqueryno,
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		   success: function(response) {	
			   resp = JSON.parse(response["codeList"]);
		    	$.each(resp, function(key,value) {
		    		global_LeaveApplyId=empMstId;
					$('#recoEmpName').val(resp[key].recomend_emp_id).trigger('change');
					$('#reasonCodeId').val(resp[key].reason_code_id).trigger('change');
					$("#leaveName").val(resp[key].leave_mst_id).trigger('change');
					$("#applicationDate").val(resp[key].application_date);
					$("#leaveFromDate").val(resp[key].leave_from_date);
					$("#leaveToDate").val(resp[key].leave_to_date);
					$("#applyLeaveDays").val(resp[key].apply_leave_days);
					$("#publicHoliday").val(resp[key].public_holiday);
					$("#leaveDays").val(resp[key].leave_days);
					$("#leaveDaysAddress").val(resp[key].leave_days_address);  
					$("#reason").val(resp[key].reason); 
					if(resp[key].first_half=="YES"){
						$("#Fhalf").prop('checked', true);
					}else{
						$("#Fhalf").prop('checked', false);
					}
					if(resp[key].second_half=="YES"){
						$("#Shalf").prop('checked', true);
					}else{
						$("#Shalf").prop('checked', false);
					}
					if(resp[key]['leave_sanc_flag']=="Y"){
						DisableInputs();
					}else{
						EnableInputs();
					}
			    });
	       	}
	    });
 }
 /**********************************************************/
 function getsetInt(){
	var branchMstId = $("#branchMstId").val(); 
	var employeeMstId = $("#userId").val();
	var sqlqueryno = "1008";
	$.ajax({
		url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		data : JSON.stringify({
            param : branchMstId+"~"+employeeMstId,
        	sqlMstId : sqlqueryno,
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	   success: function(response) {		       	    
		   resp = JSON.parse(response["codeList"]);
	    	$.each(resp, function(key,value) {
      	    		$("#employeeName").val(resp[key]["name"]);
          			$("#Designation").val(resp[key]["desig_name"]);
          			$("#deptId").val(resp[key]["dname"]);
	        });
       	}
    });
}
 /*************************************************/
 function GetDetails(){
    let postParametersView={
    		branchId : $("#branchMstId").val(),
   			userId	 : $("#userId").val(),
			EmpMstId : $("#userId").val(),
			desc	 : null,
			frmdate	 : null,
			todate	 : $("#leaveToDate").val()==""?"'"+TodaySet+"'":"'"+$("#leaveToDate").val()+"'"
    	    };
	$.ajax({ 
		url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveApplication/getLeaveApplication",
		data : JSON.stringify(postParametersView),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		success : function(res) {
		if ($.fn.DataTable.isDataTable('#OverView')) {
                $('#OverView').DataTable().destroy();
            }
            $("#OverView tbody").empty();
        	let keyVal=0;	let datacourt=[];
        	 var ListDetails = JSON.parse(res["EmpLeaveDetails"]);
        	 $.each(ListDetails, function (key,i) {
         		keyVal=keyVal+1;        		
  				datacourt.push([keyVal,ListDetails[key]['leave_id'],ListDetails[key]['leave_name'],ListDetails[key]['opening_leaves'],
  	  				ListDetails[key]['total_allotted'],ListDetails[key]['total_used'],ListDetails[key]['bal_leaves']]) ; 
         	 });
       	 	$('#OverView').DataTable({
                data: datacourt,
                "autoWidth": false,
                deferRender: true,
                pageLength: 10,
                "bLengthChange": false,
                info: false,
                scrollCollapse: true,
                responsive: true,
                "columnDefs": [
                    {
                        "className": "display_hide",
                        "targets": [1]
                    } ,
                    {
                        "className": "avil_Leave",
                        "targets": [6]
                    }  
                   ]
            }); 
 		},
 		failure : function() {
 			console.log("failed to load list.");
 		}	
	});
}
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptIdF" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<div class="row showTableDiv">
	<div class="col-lg-12">
		<div class="panel newPanel">
			<div class="panel-heading">
				<div class="panel-control">
					<button class="btn btn-default" data-click="panel-expand">
						<i class="fa fa-expand"></i>
					</button>
					<button class="btn btn-default" data-click="panel-reload" onclick="loadListOfLocation();">
						<i class="fa fa-refresh"></i>
					</button>
					<button class="btn btn-default" data-click="panel-collapse">
						<i class="fa fa-chevron-down"></i>
					</button>
					 <button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
					<button onclick="toggleTableAndForm('N',null)" class="btn btn-info">
						<i class="fa fa-plus"></i> Add New
					</button>
				</div>
				<h3 class="panel-title">Employee Leave Application</h3>
			</div>
			<div class="panel-body">		
				<table class="table table-striped table-bordered table-hover locationApplyTable table-responsive" id="detailList">
					<thead>
						<tr>
							<th>Sr. No.</th>
							<th>Leave Name </th>
							<th>Leave Type</th>	
							<th>From Date</th>	
							<th>To Date</th>	
							<th>Action</th>													
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>								
			</div>
		</div>
	</div>
</div>
<!------------------------------------------------------------>
<div class="row showFormDiv">
	<div class="col-lg-12">
		<form id="LeaveApply">
			<div class="panel newpanel">
				<div class="panel-heading">
					<div class="panel-control">
						<button class="btn btn-default" data-click="panel-expand">
							<i class="fa fa-expand"></i>
						</button>
						<button class="btn btn-default" data-click="panel-reload">
							<i class="fa fa-refresh"></i>
						</button>
						<button class="btn btn-default" data-click="panel-collapse">
							<i class="fa fa-chevron-down"></i>
						</button>
						<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()">
							<i class="fa fa-times"></i>
						</button>
						<button onclick="toggleTableAndForm('N',null);" type="button" class="btn btn-success">
						<i class="fa fa-chevron-left"></i>&nbsp; Back to List </button>
					</div>
					<h3 class="panel-title formTitle"> Create New Employee Leave Application </h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-6 FirstCol">
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group">
										<label for="employeeName" class="control-label LblImp">
											<spring:message code="label.employeeName"></spring:message>
										</label>
										<input name="employeeName" type="text" class="form-control mandatory" data-toggle="tooltip"
										 placeholder="Enter <spring:message code="label.employeeName"></spring:message>" title="Enter Party Filling Case" 
										 size="60" maxlength="200" id="employeeName" disabled required>
										 <small style="color: red"></small>
									</div>	
								</div>		
								<div class="col-sm-6">
									<div class="form-group">
										<label for="Designation" class="control-label ">
											<spring:message code="label.Designation"></spring:message>
										</label>
										<input name="Designation" type="text" class="form-control" data-toggle="tooltip"
										 placeholder="Enter <spring:message code="label.Designation"></spring:message>" title="Enter Party Filling Case" 
										 size="60" maxlength="200" id="Designation" disabled>
										 <small style="color: red"></small>
									</div>
								</div>
							</div>	
							<div class="row">
								<div class="col-sm-6">
									<div class="form-group">
										<label for="deptId" class="control-label">
											<spring:message code="label.deptId"></spring:message>
										</label>
										<input name="deptId" type="text" class="form-control " data-toggle="tooltip"
										 placeholder="Enter <spring:message code="label.deptId"></spring:message>" title="Enter Party Filling Case" 
										 size="60" maxlength="200" id="deptId" disabled="disabled">
										 <small style="color: red"></small>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="form-group">
										<label for="leaveName" class="control-label LblImp ">
											<spring:message code="label.leaveName"></spring:message></label>
										<select name="leaveName" class="form-control mandatory" data-toggle="tooltip" title="Select <spring:message code="label.leaveName">
										</spring:message>" id="leaveName" required>
										</select>
										<small style="color: red"></small>
									</div>
								</div>	
							</div>
							<div class="row">
								<div class="col-sm-4">
									<div class="form-group">
										<div class="form-group has-feedback">	
											<label for="applicationDate" class="control-label LblImp">
												<spring:message code="label.applicationDate"></spring:message></label>
											<input name="applicationDate" type="text" class="form-control mandatory" data-toggle="tooltip" id="applicationDate" readonly
											 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;" title="Enter <spring:message code="label.applicationDate"></spring:message>" required>
											<span class="fa fa-calendar fa-lg form-control-feedback"></span>
											<small style="color: red"></small>
										</div>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										<div class="form-group has-feedback">	
											<label for="leaveFromDate" class="control-label LblImp">
												<spring:message code="label.leaveFromDate"></spring:message></label>
											<input name="leaveFromDate" type="text" class="form-control mandatory" data-toggle="tooltip" id="leaveFromDate" readonly
											 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;" title="Enter <spring:message code="label.leaveFromDate"></spring:message>" required>
											<span class="fa fa-calendar fa-lg form-control-feedback"></span>
											<input type="checkbox" value="N" id="Fhalf">Half Day
											<small style="color: red"></small>
										</div>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										<div class="form-group has-feedback">	
											<label for="leaveToDate" class="control-label LblImp">
												<spring:message code="label.leaveToDate"></spring:message></label>
											<input name="leaveToDate" type="text" class="form-control mandatory" data-toggle="tooltip" id="leaveToDate" readonly
											 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;" title="Enter <spring:message code="label.leaveToDate"></spring:message>" required>
											<span class="fa fa-calendar fa-lg form-control-feedback"></span>
											<input type="checkbox" value="N" id="Shalf">Half Day
											<small style="color: red"></small>
										</div>
									</div>
								</div>
							</div>	
							<div class="row">
								<div class="col-sm-4">
									<div class="form-group">
										<label for="applyLeaveDays" class="control-label LblImp">
											<spring:message code="label.applyLeaveDays"></spring:message>
										</label>
										<input name="applyLeaveDays" type="text" class="form-control mandatory" data-toggle="tooltip"
										 placeholder="Enter <spring:message code="label.applyLeaveDays"></spring:message>" title="Enter Party Filling Case" 
										 size="60" maxlength="200" id="applyLeaveDays" disabled required>
										 <small style="color: red"></small>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										<label for="publicHoliday" class="control-label">
											<spring:message code="label.publicHoliday"></spring:message>
										</label>
										<input name="publicHoliday" type="text" class="form-control" data-toggle="tooltip"
										 placeholder="Enter <spring:message code="label.publicHoliday"></spring:message>" title="Enter <spring:message code="label.publicHoliday"></spring:message>" 
										 size="60" maxlength="200" id="publicHoliday">
										 <small style="color: red"></small>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										<label for="leaveDays" class="control-label LblImp">
											<spring:message code="label.leaveDays"></spring:message>
										</label>
										<input name="leaveDays" type="text" class="form-control mandatory" data-toggle="tooltip"
										 placeholder="Enter <spring:message code="label.leaveDays"></spring:message>" title="Enter Party Filling Case" 
										 size="60" maxlength="200" id="leaveDays" disabled required>
										 <small style="color: red"></small>
									</div>
								</div>
							</div>	
							<div class="row">													
								<div class="col-sm-8">
									<div class="form-group">
										<label for="recoEmpName" class="control-label LblImp">
											<spring:message code="label.recoEmpName"></spring:message></label>
										<select name="recoEmpName" class="form-control mandatory" data-toggle="tooltip" 
										 title="Select <spring:message code="label.recoEmpName"></spring:message>" id="recoEmpName" required>
										</select>
										<small style="color: red"></small>
									</div>
								</div>
								<div class="col-sm-4">
									<div class="form-group">
										<label for="reasonCodeId" class="control-label LblImp">
											<spring:message code="label.reasonCodeId"></spring:message></label>
										<select name="reasonCodeId" class="form-control mandatory" data-toggle="tooltip" 
										 title="Select <spring:message code="label.reasonCodeId"></spring:message>" id="reasonCodeId" required>
										</select>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<label for="leaveDaysAddress" class=" control-label LblImp">
											<spring:message code="label.leaveDaysAddress"></spring:message></label>
										<textarea name="leaveDaysAddress" class="form-control mandatory" data-toggle="tooltip" 
										 placeholder="Enter Subject Matter" title="Enter <spring:message code="label.leaveDaysAddress"></spring:message>" 
										 rows="2" maxlength="2000" id="leaveDaysAddress" style='resize: vertical;' required></textarea>
									<small style="color: red"></small>
									</div>
								</div>
							</div>
							<div class="row">
								<div class="col-sm-12">
									<div class="form-group">
										<label for="reason" class="control-label">
											<spring:message code="label.reason"></spring:message></label>
										<textarea name="reason" class="form-control " data-toggle="tooltip"
										 placeholder="Enter Subject Matter" title="Enter <spring:message code="label.reason"></spring:message>" 
										 rows="1" maxlength="2000" id="reason" style='resize: vertical;' ></textarea>
									</div>
								</div>
							</div>	
						</div>
						<div class="col-sm-6">
							<table class="table table-striped table-bordered table-hover locationMasterTable table-responsive" id="OverView">
								<thead>
									<tr>
										<th>Sr. No.</th><th>Leave id</th>
										<th>Leave Type</th>
										<th>Opening Leave</th>
										<th>Total Alloted Leave</th>
										<th>Used Leave</th>
										<th>Available Leave</th>
									</tr>
								</thead>
						</table>
						</div>
					</div>	
					<hr>
					<button  class="btn btn-primary submitBtnName" type="button" id="SaveLeaveApply">
					 <i class="fa fa-save"></i>Save Employee Leave Application
					</button>
					&nbsp;
					<button type="button" class="btn resetBtnName btn-danger" id="ResetLeaveApply" onclick="resetForm()">
					Reset
					</button>						
				</div>
			</div>
		</form>
	</div>
</div>
</body>
<script src="assets/js/validation.js"></script>
</html>