<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - Aishwarya Domde
Creation Date	- Apr 8, 2019  3:00:31 PM 
Project Name	- MLWB 
Module Name		- 
Page\Class\etc... Name -uri:Employee Family Details
Description	-
Link		-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Employee Family Details</title>
<link href="assets/css/style.css" rel="stylesheet">
<link href="assets/plugins/switchery/switchery.min.css" rel="stylesheet">
 <!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>
<link rel="stylesheet" type="text/css"href="assets/plugins/daterange_new/daterangepicker.css" />
<script type="text/javascript"src="assets/plugins/daterange_new/daterangepicker.js"></script>
<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Data Parsley [ OPTIONAL ]-->
<script src="assets/plugins/parsley/parsley.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Jquery Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>
<script src="assets/plugins/switchery/switchery.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<link href="assets/plugins/pretty-checkbox/pretty-checkbox.min.css" rel="stylesheet">
<script src="assets/js/focusOnEnter.js"></script>
<!--Tabbable JS-->
<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<script src="assets/js/validation.js"></script>
<style>
.LblImp:after{
	content:"*";
	color:red;
}
th.sorting {
    text-align: center;
}
</style>
<script type="text/javascript">
let global_Emp_FamdetId  = 0;
let global_empMstId ;
let op_flag = "N";
let showForm = false;
let showTable = true;
let formValidator=null;
$(document).ready(function() {	
	$('.showTableDiv').show(); 
	$('.showFormDiv').hide();
	LoadListTbl();
	validateForm();
	/*********************************************************************************************************************/
	$("#DateOfBirth").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 });
	$("#DateOfJoin").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 });
	$('.showFormDiv').find('input,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	/**********************************************************************************************************************/
	$('.showFormDiv').on('keyup change paste blur select2:close', 'input, select, textarea, button', function(event){
		let elem = event.target;
		let elValid = false;
		if (!$(elem).valid()) {
			elValid = true;
	    }
	    $('.mandatory').each(function() {
	    	if ($(this).val()=='' || $(this).val()==null) {
				elValid = true;
	        }
	    });
	    if (elValid) {
	    	$('.submitBtnName').attr('disabled', 'disabled');
	    } else {
	    	$('.submitBtnName').removeAttr('disabled');
	    }
	});
	/*********************Adding Row by One function****************************/
	$('.showFormDiv').on("click","#AddRow",function(){		
			CreateRow(1,"M");	
			$('#EditEmpFamilyDet').DataTable().columns.adjust().responsive.recalc();
	});
	/***************************************************************************/
	$('.select2-container').tooltipster({
	     functionInit: function(instance, helper){
	       var content = $(helper.origin).closest('.form-group').find('select').attr("title");
	        instance.content(content);
	    }, 
	    delay: 100,
	    theme: 'tooltipster-punk',
	    side: 'bottom'
	}); 
	/********************* For uploading Image in column****************************/
	$('.showFormDiv').on('change',"[id^=upload]", function () {
		var idno=($(this).attr('id'));
		var idSr=($(this).attr('id').match(/(\d+)/)[1]);
	    var fName = $("#"+idno)[0].files[0].name;
	    var input1 = $("#"+idno);
		var last = fName.split('.').pop();
		if( (last!="jpg" &&  last!="jpeg"  && last!="png" && last!="JPG" && last!="JPEG" && last!="PNG")||(input1[0].files[0].size>30720) ){
			if(last!="jpg" &&  last!="jpeg"  && last!="png" && last!="JPG" && last!="JPEG" && last!="PNG"){
				alert("File Type not permitted(only jpg,jpeg,png are allowed)");
				$("#browse").val("");
				return false;
				}else{
					alert("File size should not be greater than 30 KB !!!");
					$("#browse").val("");
					return false;
				}
		}
		else if (input1[0].files && input1[0].files[0]) {
		   var reader = new FileReader();
		   reader.onload = function (e) {
		   $('#userLogo'+idSr).attr('src', e.target.result);
		 };
		   reader.readAsDataURL(input1[0].files[0]);
		}	   
	});
	/***********************************************************************************/
	$("#ListEmpName").on("change select2:select",function(){
		let sEmpID= $(this).val();
		$.each(responList, function (key,i) {
			if(responList[key]['prop2']==sEmpID){
				global_empMstId=sEmpID;
				$("#Designation").val(responList[key]['prop4']);
				$("#DateOfBirth").val(responList[key]['prop5'])
				$("#DateOfJoin").val(responList[key]['prop6'])
			}
		});
	});
	/*****************************Check if last input of td is empty****************************/
	$('.showFormDiv').on('change',"input[type=text], select,.select2", function () {
		let countIf =0,CountAtr="";
		let konst="0";
		($(this).closest('tr').find('input[type=text],select')).each(function(){
			if($(this).val()==""){
				countIf++;
				CountAtr=$(this).attr('id')
			}			
		})
		if(countIf<5 ){
			for(var i=5;i>=1;i--){
				var m=$(this).closest('tr').find('td:eq('+i+')').find('.form-control').val();
			        if(m==""){ konst=i; }
				}
				if(konst!=""){ 	
					$(this).closest('tr').find('td:eq('+konst+')').find('.form-control').focus().addClass('mandatory').prop('required','required');
				}
		}
		else{
			$(this).closest('tr').next('tr').find('input[type=text],select,.select2').removeClass('mandatory').removeAttr('required');
			$(this).closest('tr').find('input[type=text],select,.select2').removeClass('mandatory')
			.removeClass('error').removeAttr('required').siblings('small').empty();
		}
 	})
	/******************************Check if last input of tr is empty************************/
	$('.showFormDiv').on('keydown focus select2:open',"input[type=text],select", function () { 
	var konst="";
	for(var i=5;i>=1;i--){
		var m=$(this).closest('tr').prev('tr').find('td:eq('+i+')').find('.form-control').val();
	        if(m==""){ konst=i; }
		}
		if(konst!=""){ 	
			$(this).closest('tr').prev('tr').find('td:eq('+konst+')').find('.form-control').focus();
		}
 	});
	/********************** For Save Modify Delete Records*************************************/
	$("#SaveEmpFamDetails").on("click",function(){
		let tblEditEmpFamilyDet = 0;
		 $("#EditEmpFamilyDet tbody tr>td>.form-control").each(function(m){
		   if($(this).val()!=""){
				tblEditEmpFamilyDet++;
		   }	   
		});
		tblEditEmpFamilyDet = parseInt(tblEditEmpFamilyDet/5); 
		console.log(tblEditEmpFamilyDet)
		let EmpFamD_Id= [];
		let EmpFamD_SrNo= [];
		let EmpFamD_Name= [];
		let EmpFamD_Rel= [];
		let EmpFamD_Date= [];
		let EmpFamD_Edu= [];
		let EmpFamD_Ocup= [];
		let EmpFamD_Depnd= [];
		let EmpFamD_Photo= [];
		let EmpFamD_activeFlag=[];
		let EmpFamD_deleteFlag=[];
		let EmpMstId=$("#ListEmpName").val();
		let EmpMstD_Desg=$("#Designation").val();
		let EmpMstD_dob=$("#DateOfBirth").val();
		let EmpMstD_doj=$("#DateOfJoin").val();
		let EmpFamD_PhotoN=[];
		let EmpFamD_Photopath=[];
		if($("#EmpFamilyDetails").valid()){
			for(let i=0 ; i<tblEditEmpFamilyDet ; i++){
				EmpFamD_Id.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(0) input.Empfamily_DetID").val());
				EmpFamD_SrNo.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(0) label").text());
				EmpFamD_Name.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(1) input").val());
				EmpFamD_Rel.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(2) select").val());
				EmpFamD_Date.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(3) input").val());
				EmpFamD_Edu.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(4) input").val());
				EmpFamD_Ocup.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(5) input").val());
				EmpFamD_Depnd.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(6) select").val());
				EmpFamD_Photopath.push(($("#EditEmpFamilyDet tbody tr:eq(0) td:eq(7) input").val()).replace("C:\\fakepath\\",""));
				EmpFamD_Photo.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(8) img.EmpFamDetImg").prop('src'));
				EmpFamD_activeFlag.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(0) input.activeFlag").val());
				EmpFamD_deleteFlag.push($("#EditEmpFamilyDet tbody tr:eq("+i+") td:eq(0) input.deleteFlag").val());
				EmpFamD_PhotoN.push(null);
			}
			let postParameters = {
					EmpMstId	 : EmpMstId,
					EmpMstD_Desg : EmpMstD_Desg,
					EmpMstD_dob  : EmpMstD_dob,
					EmpMstD_doj	 : EmpMstD_doj,
					EmpFamD_Id	 : EmpFamD_Id,
					EmpFamD_SrNo : EmpFamD_SrNo,
					EmpFamD_Name : EmpFamD_Name,
					EmpFamD_Rel	 : EmpFamD_Rel,
					EmpFamD_Date : EmpFamD_Date,
					EmpFamD_Edu	 : EmpFamD_Edu,
					EmpFamD_Ocup : EmpFamD_Ocup,
					EmpFamD_Depnd: EmpFamD_Depnd,
					EmpFamD_Photo: EmpFamD_Photo,
					userId		 : $("#userId").val(),
					branchMstId  : $("#branchMstId").val(),
					opFlag	     : op_flag,
					EmpFamD_PhotoN :EmpFamD_PhotoN,
					EmpFamD_Active :EmpFamD_activeFlag,
					EmpFamD_Delete :EmpFamD_deleteFlag,
					EmpFamD_Photopath:EmpFamD_Photopath
			}

			console.log(postParameters)
			if(op_flag=="D"){
				$.confirm({
	                title: 'Are you sure want to delete ?',
	                content: '',
	                type: 'blue',
	                buttons: {
			            Delete: {			              
			                action: function () {
			                   deleteRecord(postParameters);
			                }
			            },
			            Cancel: {
			                keys: ['N'],
			                action: function () {
			                	$('.showFormDiv').hide();
			                    $('.showTableDiv').show();
			                }
			            },
			        }
	            }); 
			}else if(op_flag=="M" || op_flag=="N"){
				$.ajax({
					url : "${pageContext.request.contextPath}/app/payroll/ServiceBook/EmployeeFamilyDetails/SaveEmpFamDetails",
					data : JSON.stringify(postParameters),
					method : "post",
					dataType : "json",
					contentType : "application/json",
					success : function(res) {
					 	if (JSON.parse(res["responseObj"]).status == "success") {
				         	toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
				            closeButton: true,
				            positionClass: 'toast-bottom-right'
				          });
				          showForm = true;
				          LoadListTbl();
				          resetForm(); 
				          DisableInputs()
				          $("#ResetEmpFamilyDetails").hide();
				        } else {
				          	toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
				            closeButton: true,
				            positionClass: 'toast-top-right'
				          });
				        }
					}
				});
			}			
		}
	});
	/*****************************************************/
	$('.mainnav-toggle').on('click change', function () {
		  setTimeout(function(){
		     EMPListDataTbl()},250);
		});
});
/**************************************************Document Ready finiished function call***************************************************************************/
 function ListEmp(op_flag){
	let branchMstId=$("#branchMstId").val();
	let parameter="";
	if(op_flag=="N"){
		parameter="EMP_EDU_HELP ~ and e.op_branch_mst_id ="+branchMstId+" and  not exists(select 1 from pay_emp_family_detail h where h.employee_mst_id = e.employee_mst_id and coalesce(h.active_flag,''Y'')=''Y'' and coalesce(h.delete_flag,''N'')=''N'')"}
	else{
		parameter="EMP_EDU_HELP ~ AND E.OP_BRANCH_MST_ID = "+branchMstId+" AND   EXISTS(SELECT 1 FROM pay_emp_family_detail H WHERE H.EMPLOYEE_MST_ID = E.EMPLOYEE_MST_ID AND coalesce(H.ACTIVE_FLAG,''Y'')=''Y'' AND coalesce(H.DELETE_FLAG,''N'')=''N'')"}
		$.ajax({
			url : "${pageContext.request.contextPath}/app/common/getHelpList",//getHelpList==branchMstId
			data : JSON.stringify({
			"param" : parameter
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
	        success: function (resp) {
	        	responList =(resp["helpList"]);
				let listOfEmpOptions = '<optgroup class="def-cursor" label="Employee Name" data-design="Designation" data-Dob="DOB" >';
				var optGrpEnd = '</optgroup>';
				var optionsList='';	//'<option value="" data-id="" label="" data-design="" data-Dob="">Select Employee</option>';
					$.each(responList, function (key,i) {
						optionsList = optionsList+'<option value="'+responList[key]["prop2"]+'" data-id="'+responList[key]["prop2"]+ '" label="'+responList[key]["prop3"]
						+'" data-design="'+responList[key]["prop4"]+'" data-Dob="'+responList[key]["prop5"]+'">'+responList[key]["prop3"]+'</option>';
			 		});
				 optionsList=listOfEmpOptions+optionsList+optGrpEnd;
		       	 $("#ListEmpName").empty().append(optionsList);
		       	 $('#ListEmpName').select2({
		    		    width: '100%',
		    			placeholder:"Select",
		    			allowClear: true,
		    		    templateResult: formatResultMulti,
		    		}).on('change',function(){
		    			if($(this).val()==null){
		    				resetForm();
		    			}
		    		});
			},
			failure : function() {
				console.log("failed to load list.");
			}		
		});
		$('.select2-container').tooltipster({
		    functionInit: function(instance, helper){
		        let content = $(helper.origin).closest('.form-group').find('select').attr("title");
		        instance.content(content);
		    },
		    delay: 100,
		    theme: 'tooltipster-punk',
		    side: 'bottom'
		});
}
/*******************************************************/
function triggerUpload(elem) {
	$(elem).closest('td').find(".upload").click();
}
/***************************************************************/
function LoadListTbl(){
	$.ajax({
		url: "${pageContext.request.contextPath}/app/common/getCodeList",
		data : JSON.stringify({
			"param" : "null",
			"sqlMstId" : 7073
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
        success: function (resp) {
       	 	if ($.fn.DataTable.isDataTable('#detailList')) {
                $('#detailList').DataTable().destroy();
            }
            $("#detailList tbody").empty();
        	respListLoadtbl = JSON.parse(resp["codeList"]);
        	let datacourt=[];
        	let keyVal=0;
        	$.each(respListLoadtbl, function (key,i) {
        		keyVal=keyVal+1;        		
     			datacourt.push([keyVal,
     				respListLoadtbl[key]["employee_name"]=="null"?"":respListLoadtbl[key]["employee_name"],
     						respListLoadtbl[key]["desig_name"]=="null"?"":respListLoadtbl[key]["desig_name"],
     	     						respListLoadtbl[key]["dob"]=="null"?"":respListLoadtbl[key]["dob"],
						'<a href="javascript:;" onclick="toggleTableAndForm(\'M\',\''+respListLoadtbl[key]['employee_mst_id']+'\')" class="btn btn-primary btn-sm btn-round" title="Edit">'+
		                '<i class="fa fa-pencil"style="padding: 5px;"></i>'+
			            '</a>&nbsp;'+
			            '<a href="javascript:;" onclick="toggleTableAndForm(\'D\',\''+respListLoadtbl[key]['employee_mst_id']+'\')" class="btn btn-danger btn-sm btn-round" title="Delete">'+
			            '<i class="fa fa-trash" style="padding: 5px;"></i>'+
			            '</a>']);
    		 });        	        	 
        	 $('#detailList').DataTable({
                 data: datacourt,
                 "autoWidth": false,
                 deferRender: true,
                 pageLength: 5,
                 "bLengthChange": false,
                 info: false,
                 scrollCollapse: true,
                 responsive: true,
                 "columnDefs": [
                     {
                         "className": "text-center",
                         "targets": [0,3,4]
                     } ,
                 ]
             });
		},
		failure : function() {
			console.log("failed to load list.");
		}		
	});
}
/**********************************************************************/
function removeRow(trObj){
	if(op_flag =="M"){
		$.confirm({
	        title: 'Are you sure want to Remove ?',
	        content: '',
	        type: 'blue',
	        buttons: {
	            Remove: {
	            	 action: function () {
	            		 if(parseInt($(trObj).closest('tr').find('.pi_srno').val())==0){
	            			 let rowSrNo = 0;
	            				let removedRow=$(trObj).closest('tr').index();
	            				$(trObj).closest('tr').remove();	
	            				let count=1;
	           					$('#EditEmpFamilyDet tbody tr').each(function(i){
	           						if($(this).is(":visible")){
	           							$(this).find('.rowSrNo').text(count);
	           							count++;
	           						}
	           						if($(this).find('.rowSrNo').text()=="1"){
	           							CreateRow(1,"M");	
	                   				}
	           					});	 
	            				 
	            		 }else {
	            		 	let rowSrNo = 0;
	            			let removedRow=$(trObj).closest('tr').index();
	            			$(trObj).closest('tr').hide();
	            			$(trObj).closest('tr').find(".activeFlag").val("N");
           					$(trObj).closest('tr').find(".deleteFlag").val("Y");           					
	            			let count=1;
           					$('#EditEmpFamilyDet tbody tr').each(function(i){
           						if($(this).is(":visible")){
           							$(this).find('.rowSrNo').text(count);
           							count++;
           						}
           						if($(this).find('.rowSrNo').text()=="1"){
           							CreateRow(1,"M");	
                   				}
           					});
	            		 }	
	            		 	
	            	 }
	            },
	             Cancel: {
	                keys: ['N'],
	                action: function () {
	                	
	                }
	            }, 
	        }  
		});	
		
	 }else{
		let rowSrNo = 0;
		let removedRow=$(trObj).closest('tr').index();
		$(trObj).closest('tr').remove();		
		 $('#EditEmpFamilyDet tbody tr').each(function(){
			$(this).find('.rowSrNo').text($(this).index()+1);
		});	
		if( $('#EditEmpFamilyDet tbody tr').length=="0")
		{
				CreateRow(1,"M");	
		}
	 }   
	$('#EditEmpFamilyDet').DataTable().columns.adjust().responsive.recalc();
}
/****************************************************************/
 function removeImg(log){
	$(log).removeAttr("src")
	$('#browse').val(null);
}
/**********************************************************************/
function deleteRecord(postParameters){
	$.ajax({
		url : "${pageContext.request.contextPath}/app/payroll/ServiceBook/EmployeeFamilyDetails/SaveEmpFamDetails",
		data : JSON.stringify(postParameters),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		success : function(res) {
		 	if (JSON.parse(res["responseObj"]).status == "success") {
	          toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
	            closeButton: true,
	            positionClass: 'toast-bottom-right'
	          });
	          resetForm();
	          LoadListTbl();
	          DisableInputs()
	        } else {
	          toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
	            closeButton: true,
	            positionClass: 'toast-bottom-right'
	          });
	        }
		}
	});
}
/*******************************************************************/
function CreateRow(noRow,tagFlag){
	$('table#EditEmpFamilyDet tbody').find('input,textarea,.select2-container,.select2,select').removeClass("tooltipstered");
	let  respReltion="";
	$.ajax({  
	    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
	    data : JSON.stringify({
			"param" : "1210",
			"sqlMstId" :12
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(response){
	    	 respReltion = JSON.parse(response["codeList"])	    	 
	      },
	 });
	let i=1;
	let count=noRow;
	let amtcount =1;
	for (var k = 1;k <= count; k++) { 
		if(tagFlag == "N")
			amtcount=$("#EditEmpFamilyDet tbody tr").length+1;
		else{
			amtcount=$("#EditEmpFamilyDet tbody tr:visible").length+1;
			}
		if(typeof ($("#EditEmpFamilyDet tbody tr:last").attr('id'))=="undefined"||($("#EditEmpFamilyDet tbody tr:last .rowSrNo").text())==""){
			i=1;
		}else{
			i =parseInt($("#EditEmpFamilyDet tbody tr:last").attr('id').match(/(\d+)/)[1])+1;
		}
		var tr = "<tr id='row"+i+"'>";
        var td1 = '<td class="rowCount"  style="text-align:center"><label class="rowSrNo">'+(amtcount)+'</label><input type="hidden" class="pi_srno" value=0>'
			    	+'<span class="pi_enquiry_trn_no hidden">0</span><input type="hidden" class=rowFlag  value=N>'
			    	+'<input type="hidden" id="Empfamily_DetID'+i+'" name="Empfamily_DetID" class="Empfamily_DetID right" size="5" value="0"/>'
			    	+'<input type="hidden" class="activeFlag" value="Y"><input type="hidden" class="deleteFlag" value="N"></span></td>';
 		var td2 = "<td><input type='text' class='form-control' maxlength=100 name='MembName' id='MembName"+i+"'  data-toggle='tooltip' title='Please fill member Name' placeholder='Please fill Member Name'><small style='color: red;'></small></td>";
 		var td3 = "<td><select id='relation"+i+"' name=relation class='form-control' data-toggle='tooltip' title='Please select relation' placeholder='Please select relation'></select><small style=color: red></small></td>";
		var td4 = '<td><div class="form-group"> <div class="form-group has-feedback">'
				 +'<input name="DateOfBirthTbl" type="text" class="form-control hasDatepic " data-toggle="tooltip" name="DateOfBirthTbl" id="DateOfBirthTbl'+i+'" placeholder="dd/mm/yy" maxlength="10" style="" title="Enter date of Birth"  >'
				 +'<span class="fa fa-calendar fa-lg form-control-feedback"></span> <small style="color: red"></small></div></div></td>';
		var td5 = "<td><input type='text' class='form-control' name='education' maxlength=30 id='education"+i+"'  data-toggle='tooltip' title='Please fill education' placeholder='Please fill education'><small style='color: red;'></small></td>";
		var td6 = "<td><input type='text' class='form-control' name='occupation' maxlength=120 id='occupation"+i+"'  data-toggle='tooltip' title='Please fill occupation' placeholder='Please fill occupation'><small style='color: red;'></small></td>";  
		var td7 = "<td><select id='depend"+i+"' class='form-control' data-toggle='tooltip' title='Please select Dependent or not' placeholder='Please select Dependent or not'><option value='Y' selected>Yes</option><option value='N' >No</option></select></td>";
		var td8 = "<td><span  class='btn btn-success btn-sm btn-round uploadIcon' id=browse"+i+"' onclick='triggerUpload(this)' title='Upload File'><i class='fa fa-upload' style='padding: 5px;'></i></span>"
				 +"<span class='fileName"+i+"'></span>"
				 +"<input type='file' class='upload' style='display:none' value='Browse' id='upload"+i+"'  accept='image/png,image/jpg,image/jpeg' />" 
				 +"<div class='progress progress-striped progress-lg active' style='display:none'><div style='width: 100%' class='progress-bar progress-bar-info'></div></div>"+
				 '<button type="button" onclick="removeImg(userLogo'+i+')" class="btn btn-danger btn-sm btn-round rowRemove formElement" title="Remove Image">'+
			        '<i class="fa fa-remove" style="padding: 5px;"></i>'+
			      	'</button>'+"</td>";
		var td9 = "<td><img width='100px' height='90px' id='userLogo"+i+"' class=EmpFamDetImg></td>";
		var td10 = 	'<td style="text-align: center;">'+
			        '<button type="button" onclick="removeRow(this)" class="btn btn-danger btn-sm btn-round rowRemove formElement" title="<spring:message code="label.commonDelete"></spring:message>">'+
			        '<i class="fa fa-trash" style="padding: 5px;"></i>'+
			      	'</button>'+
					'</td>';
		$("#EditEmpFamilyDet tbody").append(tr+td1+td2+td3+td4+td5+td6+td7+td8+td9+td10);  
		$("#MembName1,#relation1,#DateOfBirthTbl1,#education").addClass('mandatory').prop('required','required');
		$("#MembName"+i).alpha();
		$("#occupation"+i).alpha();
		$("#education"+i).alphanum();
		$("#DateOfBirthTbl"+i).numeric({decimalPlaces: 2 ,negative: false});
		$("#relation"+i).append('<option value="">Select Relation</option>');
    	$.each(respReltion, function(key,value) {
				nKey = parseInt(key)+1;
				$("#relation"+i).append('<option value="'+respReltion[key].code_mst_id+'"> '+respReltion[key].code_desc+'');
		}); 
	}
	$("[id*=DateOfBirthTbl]").datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 });
	$("[id*=relation]").select2({
		placeholder:"Select relation",
		width:'100%',
		multiple:false,
		allowClear: true
	});
 	$("[id*=depend").select2({
		placeholder:"Select dependent or not",
		width:'100%',
		multiple:false,
		allowClear: false
	});
	reloadValidationJs()
 	$('#EditEmpFamilyDet tbody tr:visible:first').find(".form-control").addClass('mandatory').prop('required','required');
	$('#EditEmpFamilyDet tbody tr:visible:first').find("input[name=MembName]").trigger("change")
 
}
/**********************Setting for Modify**********************/
function setFormData(employee_mst_id){
	let  respReltion="";
    $.ajax({  
	    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
	    data : JSON.stringify({
			"param" : "1210",
			"sqlMstId" :12
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(response){
	    	  respReltion = JSON.parse(response["codeList"])	    	 
	      },
	 });
	$.ajax({
		url: "${pageContext.request.contextPath}/app/common/getCodeList",
		data : JSON.stringify({
			"param" : "null",
			"sqlMstId" : 311
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
        success: function (resp) {
    	    $("#EditEmpFamilyDet tbody").empty();
        	respListSet = JSON.parse(resp["codeList"]);
        	let datacourt=[];
        	let keyVal=0;
        	$.each(respListSet, function (key,j) {
        		let amtcount=$("#EditEmpFamilyDet tbody tr").length+1;
           		if(respListSet[key]['employee_mst_id']==employee_mst_id){
           			keyVal=keyVal+1; 
               		$("#ListEmpName").val(employee_mst_id).trigger('change');
               		$("#Designation").val(respListSet[key]['desig_name']);
       				$("#DateOfBirth").val(respListSet[key]['dob'])
       				$("#DateOfJoin").val(respListSet[key]['joindate'])
              		i=$("#EditEmpFamilyDet tbody tr").length+1;
       				var tr = "<tr id='row"+i+"' >";
              		var td1 = '<td class="rowCount" style="text-align:center"><label class=rowSrNo>'+(amtcount)+'</label><input type="hidden" class="pi_srno" value="'+i+'">'
		       			   	+'<span class="pi_enquiry_trn_no hidden">0</span><input type="hidden" class=rowFlag  value=M>'
		       			   	+'<input type="hidden" id="Empfamily_DetID'+i+'" name="Empfamily_DetID" class="Empfamily_DetID right" size="5" value="'+respListSet[key]['emp_family_det_id']+'"/>'
		       			   	+'<input type="hidden" class="activeFlag" value="Y"><input type="hidden" class="deleteFlag" value="N"></span></td>';
       				var td2 = "<td><input type='text' class='form-control mandatory' name='MembName' maxlength=100 id='MembName"+i+"' value="+respListSet[key]['member_name']+" data-toggle='tooltip' title='Please fill Member Name' placeholder='Please fill Member Name' required><small style='color: red;'></small></td>";
       				var td3 = "<td><select id='relation"+i+"' class=form-control required data-toggle='tooltip' title='Please select relation' placeholder='Please select relation'></select><small style=color: red></small></td>";
       				var td4 = '<td><div class="form-group"> <div class="form-group has-feedback">'
       						 +'<input name="DateOfBirthTbl" type="text" class="form-control mandatory hasDatepic " required data-toggle="tooltip" value="'+respListSet[key]['birth_date']+'" name="DateOfBirthTbl" id="DateOfBirthTbl'+i+'" placeholder="dd/mm/yy" maxlength="10" style="" title="Enter date of Birth"  >'
       						 +'<span class="fa fa-calendar fa-lg form-control-feedback"></span> <small style="color: red"></small></div></div></td>';
       				var td5 = "<td><input type='text' class='form-control mandatory' maxlength=30 required value="+respListSet[key]['education']+" name='education' id='education"+i+"'  data-toggle='tooltip' title='Please fill education' placeholder='Please fill education'><small style='color: red;'></small></td>";
       				var td6 = "<td><input type='text' class='form-control mandatory' maxlength=120 required value="+respListSet[key]['occupation']+"  name='occupation' id='occupation"+i+"'  data-toggle='tooltip' title='Please fill occupation' placeholder='Please fill occupation'><small style='color: red;'></small></td>";  
       				var td7 = "<td><select id='depend"+i+"' class='form-control mandatory' data-toggle='tooltip' required title='Please select Dependent or not' placeholder='Please select Dependent or not'><option value='Y' selected>Yes</option><option value='N' >No</option></select></td>";
       				var td8 = "<td><span  class='btn btn-success btn-sm btn-round uploadIcon' id=browse"+i+"' onclick='triggerUpload(this)' title='Upload File'><i class='fa fa-upload' style='padding: 5px;'></i></span>"
       						 +"<span class='fileName"+i+"'></span>"
       						 +"<input type='file' class='upload' style='display:none' value='Browse' id='upload"+i+"'  accept='image/png,image/jpg,image/jpeg' />" 
       						 +"<div class='progress progress-striped progress-lg active' style='display:none'></div>"+
       						'<button type="button" onclick="removeImg(userLogo'+i+')" class="btn btn-danger btn-sm btn-round rowRemove formElement" title="Remove Image">'+
       				        '<i class="fa fa-remove" style="padding: 5px;"></i>'+"</td>";
       				var td9 = "<td><img width='100px' height='90px' id='userLogo"+i+"' class=EmpFamDetImg src="+respListSet[key]['family_photo']+"></td>";
       				var td10 = 	'<td style="text-align: center;">'+
       							'<button type="button" onclick="removeRow(this)" class="btn btn-danger btn-sm btn-round rowRemove formElement" title="<spring:message code="label.commonDelete"></spring:message>">'+
       							'<i class="fa fa-trash" style="padding: 5px;"></i>'+
       							'</button>'+
       							'</td>';
       				$("#EditEmpFamilyDet tbody").append(tr+td1+td2+td3+td4+td5+td6+td7+td8+td9+td10); 
       				$("#relation"+i).append('<option value="">Select Relation</option>');
       		    	$.each(respReltion, function(key,value) {
       						nKey = parseInt(key)+1;
       						$("#relation"+i).append('<option value="'+respReltion[key].code_mst_id+'"> '+respReltion[key].code_desc+'');
       				});
       				$("#depend"+i).select2({
       					placeholder:"Select",
       					width:'100%',
       					multiple:false,
       					allowClear: false
       				});
       		    	$("#relation"+i).select2({
       		    		placeholder:"Select relation",
       		    		width:'100%',
       		    		multiple:false,
       		    		allowClear: true
       		    	});
       				$("#relation"+i).val(respListSet[key]['relation_type_id']).trigger('change')
       				$("#depend"+i).val(respListSet[key]['dependent_yn']).trigger('change')
              }     		
            });   
		},
		failure : function() {
			console.log("failed to load list.");
		}		
	});
	reloadValidationJs()   	 		
}
/********************for column creation in select2************************************/
function formatResultMulti(data) {
		  var design = $(data.element).data('design');
		  var Dob = $(data.element).data('dob');  
		  var id = $(data.element).data('id');
		  var classAttr = $(data.element).attr('class');
		  var hasClass = typeof classAttr != 'undefined';
		  classAttr = hasClass ? ' ' + classAttr : '';
		  var $result = $(
		    '<div class="row" id=' + id + '>' +
		    '<div class="col-md-6 col-xs-6' + classAttr + '">' + data.text + '</div>' +
		    '<div class="col-md-3 col-xs-3' + classAttr + '">' + design + '</div>'  +
		    '<div class="col-md-2 col-xs-2' + classAttr + '">' + Dob + '</div>' +
		    '</div>'
		  );
		  return $result;
}
/****************************************************************************************************/
function toggleTableAndForm(flag, empMstId) {
	if (showForm) {
		showForm = false;
		showTable = true;
		$('.showTableDiv').show();
		$('.showFormDiv').hide();
	} else {
		if (flag == 'M') {
			$("#ResetEmpFamilyDetails").show();
			$('.formTitle').html('Update  Employee Family Details');
			$('.submitBtnName').html('<i class="fa fa-save"></i> Update Employee Family Details ');
			op_flag = "M";	
			EnableInputs();
			tblReset()
			ListEmp(op_flag)
			setFormData(empMstId);
			EMPListDataTbl();
		}
		if (flag == 'N') {	
			$("#ResetEmpFamilyDetails").show();	
			$('.formTitle').html('Create New Employee Family Details ');
			$('.submitBtnName').html('<i class="fa fa-save"></i> Save Employee Family Details ');
			$('.submitBtnName').attr('disabled', 'disabled');
			tblReset();
			EnableInputs();
			ListEmp(op_flag);
			resetForm();
    		$('.showTableDiv').show();
    		EMPListDataTbl();
		}
		if (flag == 'D') {
			$("#ResetEmpFamilyDetails").hide();
			$('.formTitle').html('<i class="fa fa-save"></i> Delete  Employee Family Details');
			$('.submitBtnName').html('Delete Employee Family Details ');
			op_flag = "D";
			tblReset();
			ListEmp(op_flag)
			setFormData(empMstId);
			EMPListDataTbl();	
			DisableInputs();
			setTimeout(function(){$("#AddRow").attr('disabled', 'disabled');},10);
		}
		showForm = true;
		showTable = false;
		$('.showTableDiv').hide();
		$('.showFormDiv').show();
	}	
}
/******************************************************/
function tblReset(){
		if ($.fn.DataTable.isDataTable('#EditEmpFamilyDet')) {
	        $('#EditEmpFamilyDet').DataTable().destroy();
	    }
}
/******************************************************/
function EMPListDataTbl(){
	setTimeout(function(){
		tblReset();	
		$("#EditEmpFamilyDet").DataTable({
 	        "Destroy":true,
	        deferRender:    true,
	        "paging":   false, 
 	       "bPaginate": false,
 	        "bInfo" : false,
 	      	scrollY:  '50vh',
 	        scrollCollapse: true,
 	        "ordering":false,
	        responsive: true,
	        "columnDefs": [
	            {
	                "className": "text-center",
	                "targets": [0,7,9]
	            } ,
	        ]
		});

	    $('table#EditEmpFamilyDet tbody').find('input,textarea').removeClass("tooltipstered");
	    $('table#EditEmpFamilyDet tbody').find('.select2,.select2-container').removeClass("tooltipstered");
		$('table#EditEmpFamilyDet tbody').find('input,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
		$('table#EditEmpFamilyDet tbody ').find('.select2-container').tooltipster({
		    functionInit: function(instance, helper){
		        var content = $(helper.origin).closest('td').find('select').attr("title");
		        instance.content(content);
		    },
		    delay: 100,
		    theme: 'tooltipster-punk',
		    side: 'bottom'
		});
		$("#EditEmpFamilyDet_wrapper").closest(".row").find(".row:first-child .col-sm-6:first-child").append('<div class="col-sm-3" id="AddButton"> <button id="AddRow" type="button" class=" btn btn-primary addBtn formElement">'
				+'<i class="fa fa-plus"></i> Add Row</button></div>');
		},10);
}
/******************************************************/
function resetForm(){
	$("#Designation").val("");
	if($('#ListEmpName').val()!=null){
		 $('#ListEmpName').val(null).trigger('change');
	}
	$("#DateOfBirth").val("");
	$("#DateOfJoin").val("");
	$("[id^=MembName]").val("");
	$("[id^=relation]").val("").trigger('change');
	$("[id^=DateOfBirthTbl]").val("");
	$("[id^=education]").val("");
	$("[id^=occupation]").val("");
	$("[id^=depend]").val("").trigger('change');
	op_flag="N";
	global_Empfamily_DetID=0;
	$('#EditEmpFamilyDet tbody').empty();
	CreateRow(3,"N");
	$("[id*=relation]").select2({
		placeholder:"Select relation",
		width:'100%',
		multiple:false,
		allowClear: true
	});
 	$("[id*=depend").select2({
		placeholder:"Select Dependent or not",
		width:'100%',
		multiple:false,
		allowClear: false
	});
	formValidator.resetForm();
	EnableInputs();
}
/******************************************************/
function DisableInputs(){
	$("#ListEmpName").attr('disabled', 'disabled');
	$("#AddRow").attr('disabled', 'disabled');
	$('#EditEmpFamilyDet>tbody>tr').find('input').attr('disabled', 'disabled');
	$('#EditEmpFamilyDet>tbody>tr').find('select,.select2').attr('disabled', 'disabled');
}
/******************************************************/
function EnableInputs(){
	$("#ListEmpName").removeAttr('disabled');
	$("#AddRow").removeAttr('disabled');
	$('#EditEmpFamilyDet>tbody>tr').find('input').removeAttr('disabled');
	$('#EditEmpFamilyDet>tbody>tr').find('select,.select2').removeAttr('disabled');
}
/*****************************************************/
function validateForm(){
	formValidator = $("#EmpFamilyDetails").validate({
        rules: {
        	"ListEmpName": {required: true},
        	},
        messages: {
        	"ListEmpName": {required: "Please select Employee Name"},
        		  },
        highlight: function (element, errorClass, validClass) {
        	if($(element).hasClass('mandatory')){
        		var elem = $(element);
                elem.addClass(errorClass);
                elem.siblings('.select2-container').addClass(errorClass); 
        	}
        },    
        unhighlight: function (element, errorClass, validClass) {
              var elem = $(element);
              elem.removeClass(errorClass);
              elem.siblings('.select2-container').removeClass(errorClass);
              elem.siblings('small').empty();
        },
        errorPlacement: function(error, element) {
            $(element).siblings('small').empty().html(error);
         },
        submitHandler: function (form) {
        	e.preventDefault(e);
            return false; 
        }
    });
}
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptId" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<div class="row showTableDiv">
	<div class="col-lg-12">
		<div class="panel newPanel">
			<div class="panel-heading">
				<div class="panel-control">
					<button class="btn btn-default" data-click="panel-expand">
						<i class="fa fa-expand"></i>
					</button>
					<button class="btn btn-default" data-click="panel-reload" onclick="loadListOfLocation();">
						<i class="fa fa-refresh"></i>
					</button>
					<button class="btn btn-default" data-click="panel-collapse">
						<i class="fa fa-chevron-down"></i>
					</button>
					 <button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
					<button onclick="toggleTableAndForm('N',null)" class="btn btn-info">
						<i class="fa fa-plus"></i> Add New
					</button>
				</div>
				<h3 class="panel-title">Employee Family Details</h3>
			</div>
			<div class="panel-body">		
				<table class="table table-striped table-bordered table-hover locationMasterTable table-responsive" id="detailList">
					<thead>
						<tr>
							<th>Sr. No.</th>
							<th>Employee Name </th>
							<th>Designation</th>	
							<th>Date of Birth</th>	
							<th>Action</th>													
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>								
			</div>
		</div>
	</div>
</div>
<!------------------------------------------------------------>
<div class="row showFormDiv">
	<div class="col-lg-12">
		<form id="EmpFamilyDetails">
			<div class="panel newpanel">
				<div class="panel-heading">
					<div class="panel-control">
						<button class="btn btn-default" data-click="panel-expand">
							<i class="fa fa-expand"></i>
						</button>
						<button class="btn btn-default" data-click="panel-reload">
							<i class="fa fa-refresh"></i>
						</button>
						<button class="btn btn-default" data-click="panel-collapse">
							<i class="fa fa-chevron-down"></i>
						</button>
						<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()">
							<i class="fa fa-times"></i>
						</button>
						<button onclick="toggleTableAndForm('N',null);" type="button" class="btn btn-success">
						<i class="fa fa-chevron-left"></i>&nbsp; Back to List </button>
					</div>
					<h3 class="panel-title formTitle">Create New Employee Family Details </h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-4">
							<div class="form-group">
								<label for="ListEmpName"  class="LblImp control-label ">
									<spring:message code="label.empMaster_EmployeeName"></spring:message> 
								</label>
								<select id="ListEmpName" class="form-control mandatory"  name=ListEmpName
								data-toggle="tooltip" required title="Select <spring:message code="label.empMaster_EmployeeName"></spring:message>  ">
								</select>
								<small style="color: red"></small>
							</div>
						</div>
						<div class="col-sm-3">
							<div class="form-group">
								<label for="Designation" class="control-label LblImp">
									<spring:message code="label.EmpDesignation"></spring:message>
								</label>
								<input name="Designation" type="text" class="form-control mandatory" data-toggle="tooltip" name="Designation"
								 placeholder="Enter <spring:message code="label.EmpDesignation"></spring:message>"  title="Enter Party Filling Case" 
								  size="60" maxlength="200"  id="Designation" required disabled>
							</div>
						</div>					
						<div class="col-sm-2">
							<div class="form-group">
								<div class="form-group has-feedback">	
									<label for="DateOfBirth"  class="LblImp control-label">
										<spring:message code="label.empMaster_DateOfBirth"></spring:message>
									</label>								
									<input name="DateOfBirth" type="text" class="form-control mandatory" data-toggle="tooltip" id="DateOfBirth" name="DateOfBirth"
									 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;" disabled
									  title="Enter <spring:message code="label.empMaster_DateOfBirth"></spring:message>" required >
									<span class="fa fa-calendar fa-lg form-control-feedback"></span>
									<small style="color: red"></small>
								</div>
							</div>
						</div>
						<div class="col-sm-2">
							<div class="form-group">
								<div class="form-group has-feedback">	
									<label for="DateOfJoin"  class="LblImp control-label">
										<spring:message code="label.dateOfJoining"></spring:message>
									</label>								
									<input name="DateOfJoin" type="text" class="form-control mandatory" data-toggle="tooltip" id="DateOfJoin"
									 placeholder="dd/mm/yy" maxlength="10" style="text-align: center;"  name="DateOfJoin" disabled
									 title="Enter <spring:message code="label.dateOfJoining"></spring:message>" required >
									<span class="fa fa-calendar fa-lg form-control-feedback"></span>
									<small style="color: red"></small>
								</div>
							</div>
						</div>
						</div>
					<br>
					<div class="row">
						<div class="col-sm-12">
							<div class="form-group">
								<table id="EditEmpFamilyDet" style="height:10px;"
								class="table table-striped table-bordered table-hover locationMasterTable table-responsive" >
									<thead>
									<tr>
										<th>Sr No.</th>
										<th>Member Name<span style="color: red;"> *</span></th>
										<th>Relation With Employee<span style="color: red;"> *</span></th>
										<th>Date of birth<span style="color: red;"> *</span></th>
										<th>Education<span style="color: red;"> *</span></th>
										<th>Occupation<span style="color: red;"> *</span></th>
										<th>Dependent</th>
										<th>Upload</th>
										<th>Photo</th>
										<th>Action</th>
										</tr>
									</thead>
									<tbody ></tbody>
								</table>
							</div>
						</div>
					</div>
					<hr>
					<button  class="btn btn-primary submitBtnName" type="button" id="SaveEmpFamDetails">
					 <i class="fa fa-save"></i>Save Employee Family Details
					</button>
					&nbsp;
					<button type="button" class="btn resetBtnName btn-danger" id="ResetEmpFamilyDetails" onclick="resetForm()">
					Reset
					</button>						
				</div>
			</div>
		</form>
	</div>
</div>
</body>
</html>