<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - Komal Indoriya
Creation Date	-09/04/2019
Project Name	- MLWB
Module Name		- 
Page\Class\etc... Name -Employee Nominee details
Description	-
Link		-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================-->
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>

<!--Bootstrap Select -->
<link href="assets/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet">

<script src="assets/panelActions.js"></script>
<!--Bootstrap Select2 [ OPTIONAL ]-->
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">


<!--Datepicker [ OPTIONAL ]-->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">

<script src="assets/plugins/jquery-ui-1.12.1/jquery-ui.min.js"></script>

	
<!--Bootstrap Select -->
<script src="assets/plugins/bootstrap-select/bootstrap-select.min.js"></script>


<!--Bootstrap Select2 [ OPTIONAL ]-->
<script src="assets/plugins/select2/select2.min.js"></script>

<!--Bootstrap Validator [ OPTIONAL ]-->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>


<!--Bootstrap Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>


<!--Data Parsley [ OPTIONAL ]-->
<!-- <script src="assets/plugins/parsley/parsley.min.js"></script> -->


<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>


<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">


<!-- Panel Actions -->
<script src="assets/panelActions.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<script src="assets/plugins/Loading-Spinner/jquery-loader.js"></script>

<script src="assets/plugins/tabbable/jquery.tabbable.js"></script>
<script src="assets/plugins/cleave.js/cleave.min.js"></script>

<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Validator -->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Bootstrap Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="assets/panelActions.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<script src="assets/plugins/mask-input/jquery.mask.js"></script>
<script src="assets/plugins/mask-input/jquery.mask.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<script src="assets/plugins/select2/select2.min.js"></script>

<script type="text/javascript">
let op_flag = "N";
let showForm = false;
let showTable = true;
let listOfLoan = [];
let global_nominee_id = 0;
let listofCountry = [];
let listofEmployeeNom =[];
let listOfEmployee =[];
let listOfEmployeeUpdateState=[];
let listOfEmployeeNewState=[];
$('.submitBtnName').text("Save Employee Nominee");


$(document).ready(function(){
	
   
	 $('.showTableDiv').show();
	 $('.showFormDiv').hide();
	 $('#designation').attr('disabled', 'disabled');
	 $('#dob').attr('disabled', 'disabled');
	 $('#joindate').attr('disabled', 'disabled');
	 

/*======================================Select 2=======================================================  */
	 $("#emp_name").on("change select2:select",function(){
		 	var emp_id_selected;
		 	emp_id_selected = $("#emp_name").val();
			 listOfEmployee.forEach(function(user,i){
				if(user.prop2==emp_id_selected){
				 	$("#designation").val(user.prop7);
		            $("#dob").val(user.prop5);
		            $("#joindate").val(user.prop6); 
		       	    $('#designation').attr('disabled', 'disabled');
		    	    $('#dob').attr('disabled', 'disabled');
		    	    $('#joindate').attr('disabled', 'disabled');
		    	    
				}
			
			}); 
		});



/*=========================================ToolTip=====================================================  */
$('form').find('input,textarea,option,button').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
$('.select2-container').tooltipster({
     functionInit: function(instance, helper){
       var content = $(helper.origin).closest('.form-group').find('select').attr("title");
        instance.content(content);
    }, 
    delay: 100,
    theme: 'tooltipster-punk',
    side: 'bottom'
});
/*=========================================Method call=====================================================  */
loadTableList();
getRealtionList();
addItemRow(5,1);
/*========================================= validation=====================================================  */
	validateForm();
	$('#NomnieeForm').on('keyup change paste blur select2:close', 'input, select, textarea, button', function(event){
		let elem = event.target;
		var elValid = false;
		 if (!$(elem).valid()) {
			elValid = true;
        } 
        $('.mandatory').each(function() {
        	
        	if(!$(elem).is($(this))){
    		      
        		if ($(this).val()=='' || $(this).val()==null) {

        			elValid = true;
	            }
        	}
        });
        if (elValid) {
        	$('.submitBtnName').attr('disabled', 'disabled');
        } else {
        	$('.submitBtnName').removeAttr('disabled');
        	
        }
	});
	
	/*========================================= load list modify=====================================================  */	
	 var branchMstId =$("#branchMstId").val();
	 var parameter = "EMP_EDU_HELP ~ AND E.OP_BRANCH_MST_ID = "+branchMstId+" AND EXISTS(SELECT 1 FROM PAY_EMP_NOMINEE_DETAIL H WHERE H.EMPLOYEE_MST_ID = E.EMPLOYEE_MST_ID AND coalesce(H.ACTIVE_FLAG,''Y'')=''Y'' AND coalesce(H.DELETE_FLAG,''N'')=''N'')";
     	$.ajax({
				url : "${pageContext.request.contextPath}/app/common/getHelpList",
				data : JSON.stringify({
					"param" : parameter
				}),
			method : "post",
			dataType : "json",
			contentType : "application/json",	
			success : function(resp) {
				listOfEmployeeUpdateState = resp.helpList;
			},
		}); 
    	/*========================================= End load list modify=====================================================  */
	
    	
     	/*========================================= load list New=====================================================  */	
   	 var branchMstId =$("#branchMstId").val();
   	 var parameter = "EMP_EDU_HELP ~ AND E.OP_BRANCH_MST_ID = "+branchMstId+" AND NOT EXISTS(SELECT 1 FROM PAY_EMP_NOMINEE_DETAIL H WHERE H.EMPLOYEE_MST_ID = E.EMPLOYEE_MST_ID AND coalesce(H.ACTIVE_FLAG,''Y'')=''Y'' AND coalesce(H.DELETE_FLAG,''N'')=''N'')";
        	$.ajax({
   				url : "${pageContext.request.contextPath}/app/common/getHelpList",
   				data : JSON.stringify({
   					"param" : parameter
   				}),
   			method : "post",
   			dataType : "json",
   			contentType : "application/json",	
   			success : function(resp) {
   				listOfEmployeeNewState = resp.helpList;
   			},
   		}); 
       	/*========================================= End load list New=====================================================  */
	
	
	
	
});//end of ready


/*================================================ Start loadCustomerList===========================================================  */
function loadTableList(){
	
	 var branchMstId =$("#branchMstId").val();
	 if ($.fn.dataTable.isDataTable('.detailList')) {
			dtTable.clear().destroy();
		}
	 	$.ajax({
				url : "${pageContext.request.contextPath}/app/common/getHelpList",//getHelpList==branchMstId
				data : JSON.stringify({
					"param" : "EMP_EDU_HELP ~ AND E.OP_BRANCH_MST_ID = "+branchMstId+" AND EXISTS(SELECT 1 FROM PAY_EMP_NOMINEE_DETAIL H WHERE H.EMPLOYEE_MST_ID = E.EMPLOYEE_MST_ID AND coalesce(H.ACTIVE_FLAG,''Y'')=''Y'' AND coalesce(H.DELETE_FLAG,''N'')=''N'')"
				}),
			method : "post",
			dataType : "json",
			contentType : "application/json",	
			success : function(resp) {
			
				listOfCustomer = resp.helpList;
				if(listOfCustomer.length){
					let tbodyData="";
					listOfCustomer.forEach(function(user,i){
						tbodyData = tbodyData+'<tr>'+
						'<td style="text-align: right">'+(i+1)+'</td>'+
						'<td>'+(user.prop3==null ? "" : user.prop3)+'</td>'+
						'<td>'+(user.prop4==null ? "" : user.prop4)+'</td>'+
						'<td style="text-align:center">'+(user.prop5==null ? "":user.prop5)+'</td>'+
						'<td style="text-align: center;">'+
						'<a href="javascript:;" onclick="toggleTableAndForm(\'M\',\''+user.prop2+'\')" class="btn btn-primary btn-sm btn-round" title="<spring:message code="label.commonEdit"></spring:message>">'+
		                '<i class="fa fa-pencil"style="padding: 5px;"></i>'+
		              '</a>&nbsp;'+
		              '<a href="javascript:;" onclick="toggleTableAndForm(\'D\',\''+user.prop2+'\')" class="btn btn-danger btn-sm btn-round" title="<spring:message code="label.commonDelete"></spring:message>">'+
		                '<i class="fa fa-trash" style="padding: 5px;"></i>'+
		              '</a>'+
						'</td></tr>';
					});
				$('.detailListTableBody').empty().html(tbodyData);
					
					dtTable = $('.detailList').DataTable({});
				}
				
			},
			failure : function() {
				console.log("failed to load list.");
			}
		}); 

	}
/*================================================ End loadCustomerList===========================================================  */

	
	/*================================================ Start loadEmployeeSelect2List===========================================================  */
	function loadEmployeeSelect2List(id){
		 $("#emp_name").empty();
		 if(op_flag=='M' || op_flag == 'D'){ 	
		    listOfEmployee = listOfEmployeeUpdateState;
		 }else{
			  listOfEmployee = listOfEmployeeNewState;
		 }
				let	listOfItemsSelectAndOptions = '<optgroup class="def-cursor" label="Name"  data-design="Designation" data-Dob="DOB" >';
					let optGrpAndSelectEnd = '</optgroup></select>';
					let options='';
			
					listOfEmployee.forEach(function(user,i){
							  options = options+'<option value="'+user.prop2+'" data-id="'+user.prop2+ '" label="'+user.prop3
								+'" data-design="'+user.prop4+'" data-Dob="'+user.prop5+'">'+user.prop3+'</option>';
							  
						});
						
					listOfItemsSelectAndOptions = listOfItemsSelectAndOptions+options+optGrpAndSelectEnd;
					 $("#emp_name").empty().append(options);
					
					
					 $('#emp_name').select2({
			    		    width: '100%',
			    			placeholder:"Select",
			    			allowClear: true,
			    		    templateResult: formatResultMulti,
			    		}).on('change',function(){
			    			if($(this).val()==null){
			    				resetForm();
			    			}
			    		});
					
				}
				
			
		
	
function formatResultMulti(data) {
	  var design = $(data.element).data('design');
	  var Dob = $(data.element).data('dob');  
	  var id = $(data.element).data('id');
	  var classAttr = $(data.element).attr('class');
	  var hasClass = typeof classAttr != 'undefined';
	  classAttr = hasClass ? ' ' + classAttr : '';
	  var $result = $(
	    '<div class="row" id=' + id + '>' +
	    '<div class="col-md-6 col-xs-6' + classAttr + '">' + data.text + '</div>' +
	    '<div class="col-md-3 col-xs-3' + classAttr + '">' + design + '</div>'  +
	    '<div class="col-md-2 col-xs-2' + classAttr + '">' + Dob + '</div>' +
	    '</div>'
	  );
	  return $result;
}
/*================================================ End loadEmployeeSelect2List===========================================================  */	
/*===============================================Started DeducationCalON=======================================================================  */
  function getRealtionList(i,id){
	  $('[Id^=emp_relation_row]').select2({
			placeholder:"Select Employee Relation",
			multiple:false,
			allowClear:true,
			width:'100%',
		   });
		
	
		var postParameter={
				"param" : "1210",
				"sqlMstId":12
		}
		$.ajax({
			url : "${pageContext.request.contextPath}/app/common/getCodeList",
			data:JSON.stringify(postParameter),
			method:"post",
			dataType:"json",
			contentType:"application/json",
			async:false,
			success:function(response){
				listofCountry=JSON.parse(response["codeList"]);
				/* $.each(listofCountry, function(k, resp) {
                 $('#emp_relation_row'+i).append("<option value='"+resp.code_mst_id+"' >"+resp.code_desc+"</option>");
					 }); */
			}
		
		});
		
	}
 
/*===============================================Ended DeducationCalON=======================================================================  */
 /*================================================toggleTableAndForm Start===========================================================  */  
 function toggleTableAndForm(flag, Deduction_Id) {
	
	  //console.log("tooggle"+flag+"--"+Deduction_Id);
	if (showForm) {
		showForm = false;
		showTable = true;
		$('.showTableDiv').show();
		$('.showFormDiv').hide();
		$('.panel-title').text("Employee Nominee List");
     	$('.addNewBtnOnForm').empty().html('<i class="fa fa-plus"></i> Add New Nomination');
		
	} else {
		if (flag == 'M') {
			
			$('.panel-title').html("Update Employee Nominee");
			$('.submitBtnName').text("Update Employee Nominee");
			
			$('.addBtn').attr("disabled",false);
			op_flag = "M";
			inAbled();
			loadEmployeeSelect2List(Deduction_Id);
			global_nominee_id=Deduction_Id;
			setFormData(Deduction_Id);
			
		}
		if (flag == 'N') {
			
			global_nominee_id =0;
			$('.panel-title').text("New Employee Nominee");
			$('.submitBtnName').text("Save Employee Nominee");
			$('.addBtn').attr("disabled",false);
			inAbled();
			resetForm();
			loadEmployeeSelect2List(Deduction_Id);
			$('#InfoTable tbody').empty();
			addItemRow(5,1)
		    
		}
		if (flag == 'D') {
			
			$('.panel-title').html("Delete Employee Nominee");
			$('.submitBtnName').text("Delete Employee Nominee");
			$("#documentsTab").show();
			$('.addBtn').attr("disabled","disabled");
			op_flag = "D";
			loadEmployeeSelect2List(Deduction_Id);
			global_nominee_id=Deduction_Id;
			setFormData(Deduction_Id);
			disAbled();
		}
		showForm = true;
		showTable = false;
		$('.showTableDiv').hide();
		$('.showFormDiv').show();
		$('.addNewBtnOnForm').empty().html('<b><i class="fa fa-angle-left" style="font-weight: 900;"></i></b> Back To List');
	}
}
/*================================================toggleTableAndForm End===========================================================  */ 
/*================================================ Start disAbled===========================================================  */
 	function disAbled(){
		document.getElementById("submitBtnName").disabled = false;
 		$('#emp_name').attr('disabled', 'disabled');
		$('#designation').attr('disabled', 'disabled');
		$('#dob').attr('disabled', 'disabled');
		$('#joindate').attr('disabled', 'disabled'); 
		$('#InfoTable tbody tr input,select').prop('disabled','disabled');
//		$('#InfoTable tbody tr input').prop('disabled','disabled');
		
	}
/*================================================ End disAbled===========================================================  */
/*================================================ Start inAbled===========================================================  */
 	function inAbled(){
		document.getElementById("submitBtnName").disabled = false;
 		$('#emp_name').removeAttr('disabled');
 		

 
	}
/*================================================ End inAbled===========================================================  */
/*================================================ End resetForm===========================================================  */ 
  function resetForm(){
	
	  if($('#emp_name').val()!=null){
			 $('#emp_name').val(null).trigger('change');
		}
			op_flag = "N";
			global_Loan_id =0;
			
			$('#designation').val("");
			$('#dob').val(null);
			$('#joindate').val(null);
			$("#InfoTable tbody").empty();
			addItemRow(5,1);
			
}

  function isNumberKey(evt, id, value) {
	  console.log(id+"id");
      var rval = "";           
      var code;
      if (!e) var e = window.event;
      if (e.keyCode) code = e.keyCode;
      else if (e.which) code = e.which;
      var character = String.fromCharCode(code);        
      var AllowRegex = /^[0-9.]+$/;         
      if (AllowRegex.test(character)) {
          if (value < 0 || value >= 99) {
              $("#"+id).css({
                  "border": "1px solid red"

              });
              alert('Percentage must be between 0 and 100');
              $("#"+id).val("");
              rval= false;
          }
          else {  
              rval = true;
          }
      }
      else {

          rval = false;
      }     
      return rval;
  }
/*================================================ End resetForm===========================================================  */
/*================================================ Start setFormData===========================================================  */
 	 function setFormData(Loan_id) {
	 	var emp_name_selected;
 		emp_name_selected =Loan_id;
 		
 		console.log(Loan_id+"Loan_id");
 		var postParameter={
 				"param" : ""+emp_name_selected+"",
 				"sqlMstId":312
 		}
 		$.ajax({
 			url : "${pageContext.request.contextPath}/app/common/getCodeList",
 			data:JSON.stringify(postParameter),
 			method:"post",
 			dataType:"json",
 			contentType:"application/json",
 			async:false,
 			success:function(response){
 				
 				listOfEmployeeNom=JSON.parse(response["codeList"]);
 				
 				$('#InfoTable tbody').empty();
 				
 				$.each(listOfEmployeeNom, function(i, resp) {
 			    $('#emp_name').val(resp.employee_mst_id).trigger('change');
 				$("#designation").val(resp.desig_name);
 	            $("#dob").val(resp.dob);
 	            $("#joindate").val(resp.joindate);
 	           
 	            $('.InfoTable').append('<tr>'+

 	   		            '<td class="nomineeId" id="nomineeId'+i+'" style="text-align: center" hidden><label>'+resp.emp_nominee_det_id+'</label></td>'+
 	   		 		    '<td class="rowCount" id="'+(i)+'" style="text-align: center;width: 4%"><label class="rowforDel">'+(i+1)+'</label>'+
 	   		 		        '<input type="hidden" class="chkIdForRemoveRow" value="'+(i+1)+'">'+
 	   		 		        '<input type="hidden" class="activeFlag" value="Y">'+
 	   		 		        '<input type="hidden" class="deleteFlag" value="N"></td>'+
 	            		'<td style="width: 15%"><input type="text" class="form-control input-sm emp_name_row "  name="emp_name_row" id="emp_name_row'+i+'" value="'+(resp.member_name==null?"":resp.member_name)+'" title="Enter Memeber Name"><small style=color: red></small></td>'+
 	            		'<td class="" style="width: 10%"><select class="form-control input-sm emp_relation_row" name="emp_relation_row" id="emp_relation_row'+i+'" value="'+(resp.relation_type_id==null?"":resp.relation_type_id)+'" title="Select Relation"></select><small style=color: red></small></td>'+
 	            		'<td class=""  style="width: 20%">'+
 	           		    '<div class="form-group has-feedback">'+													
 	           		    '<input type="text" class="form-control dob_row" name="dob_row" id="dob_row'+i+'" value="'+(resp.birth_date==null?"":resp.birth_date)+'" title="Select DOB "'+
 	                    'maxlength="10" style="text-align: center; height: 30px;" required>'+
 	                    '<span class="fa fa-calendar fa-lg form-control-feedback"></span>'+
 	                    '<small style="color: red;"></small>'+
 	           	        '</div></td>'+
 	            		'<td style="width: 13%;text-align:right;"><input type="text" class="form-control input-sm percentage_row "  data-toggle="tooltip" title="Enter Percentage" maxlength=3 name="percentage_row" id="percentage_row'+i+'" value="'+(resp.percentage==null?"":resp.percentage)+'" onkeypress="return isNumberKey(event,this.id,this.value);"><small style=color: red></small></td>'+
 	            		'<td style="width: 20%"><textarea type="text" class="form-control input-sm address_row" name="address_row" id="address_row'+i+'" value='+(resp.address==null?"":resp.address)+'  title="Enter Address"></textarea><small style=color: red></small></td>'+
 	            		'<td style="width: 2%;text-align:center"><button type="button" class="btn btn-success btn-sm btn-round uploadIcon" onclick="triggerUpload('+i+')" title="<spring:message code="label.commonUploadFile"></spring:message>"><i class="fa fa-upload" style="padding: 5px;"></i></button>'+
 	                	   '<span class="fileName"></span>'+
 	                	   '<input type="file" value="'+i+'" class="uploadDoc" id="uploadDoc'+i+'" style="display:none;"  accept="image/png,image/jpg,image/jpeg" onchange="readURL(this,'+i+')"  data-docname="test">'+
 	                	   '<span class="generatedDocName "></span>'+
 	                       '<span class="doc_attach_tran_id hidden">0</span>'+
 	                       '<span class="docpath" style="display:none"></span>'+
 	                       '</td>'+
 	             		'<td style="width: 100px; height:90px" ><img width="100px" height="90px" class="userLogo" id="userLogo'+i+'" src='+resp.photo+'>'+ 
 	            			'</td>'+ 
 	            		 '<td style="text-align: center;width: 2%">'+
 	                        '<button type="button" onclick="removeItemRow(this)" class="btn btn-danger btn-sm btn-round rowRemove" title="<spring:message code="label.commonDelete"></spring:message>">'+
 	                          '<i class="fa fa-trash" style="padding: 5px;"></i>'+
 	                        '</button>'+
 	            		'</td>'+ 
 	            		
 	            	'</tr>');
 	            
 	       	$("#emp_name_row"+i).alpha();
 	   	$("#address_row"+i).alphanum();
 	   	$("#percentage_row"+i).numeric();
 	            
 	            $('[Id^=dob_row]').datepicker({
 	        	    changeMonth: true,
 	        	    changeYear: true,
 	        	    dateFormat: "dd/mm/yy",
 	        	 });
 	            
 	          	$('#emp_relation_row'+i).select2({
 	    	   		placeholder:"Select Employee Relation",
 	    	   		multiple:false,
 	    	   		allowClear:true,
 	    	   		width:'100%',
 	    	   	});
 	           $('.InfoTable tr:last').find('input, button,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
 	     	 $('.InfoTable tr:last').find('.select2-container').tooltipster({
 	     		    functionInit: function(instance, helper){
 	     		        var content = $(helper.origin).closest('td').find('select').attr("title");
 	     		        instance.content(content);
 	     		    },
 	     		    delay: 100,
 	     		    theme: 'tooltipster-punk',
 	     		    side: 'bottom'
 	     		});
 	            
 	            
 	          
 	            $.each(listofCountry, function(k, resp) {
                   $('#emp_relation_row'+i).append("<option value='"+resp.code_mst_id+"' >"+resp.code_desc+"</option>");
					 }); 
 	          
 	
 	           $('#emp_relation_row'+i).val(resp.relation_type_id).trigger('change');
 	         $('#address_row'+i).val(resp.address);
 	      	 
 	           
 	        	});
 			}
 		
 		});

	 	}
/*================================================ End setFormData===========================================================  */
/*================================================ Start validateForm===========================================================  */
 			function validateForm(){
			
			formValidator = $("#LoanDeductForm").validate({
				ignore: [], 
		        rules: {
		            "emp_name": {
		                required: true,
   		                }
		        },
		        messages: {
		            "emp_name": {
		            	
		              	required: "Please Select Employee Name",
		              	  			            },
		        },
		        highlight: function (element, errorClass, validClass) {
		            var elem = $(element);
		            elem.addClass(errorClass);
		            elem.siblings('.select2-container').addClass(errorClass); 
		        },    
		        unhighlight: function (element, errorClass, validClass) {
		              var elem = $(element);
		              elem.removeClass(errorClass);
		              elem.siblings('.select2-container').removeClass(errorClass);
		              elem.siblings('small').empty();
		        },
		        errorPlacement: function(error, element) {
		            $(element).siblings('small').empty().html(error);
		         },
		        submitHandler: function (form) {
		        	e.preventDefault(e);
		            return false; 
		        }
		    });
			
		}
/*================================================ end validateForm===========================================================  */
/*================================================ Start addItemRowButton===========================================================  */
 
 function addItemRowButton(){
	 let totalRowCount = $('.InfoTable').find('tbody tr').length;		
     
     addItemRow(1,totalRowCount);
     
 } 
/*================================================ end addItemRowButton===========================================================  */
 
/*===============================================Start addItemRow=======================================================================  */
 
 function addItemRow(NoOfRow,Init){
	let totalRowCount = $('.InfoTable').find('tbody tr').length;
	
	let i=1;
	let count=NoOfRow;
	for (var k = 1;k <= count; k++) {  
		i=$("#InfoTable tbody tr").length+1;
	$('.InfoTable').append('<tr>'+
		
		'<td class="nomineeId" id="nomineeId'+i+'" style="text-align: center" hidden><label>'+0+'</label></td>'+
		'<td class="rowCount" id="'+(i)+'" style="text-align: center;width: 4%"><label class="rowforDel">'+(i)+'</label>'+
		        '<input type="hidden" class="chkIdForRemoveRow" value="0">'+
		        '<input type="hidden" class="activeFlag" value="Y">'+
		        '<input type="hidden" class="deleteFlag" value="N"></td>'+
		'<td  style="width: 15%"><input type="text" class="form-control input-sm emp_name_row"  name="emp_name_row"  data-toggle="tooltip" title="Enter Member Name" placeholder="Enter Memeber Name" id="emp_name_row'+i+'"><small style=color: red></small></td>'+
		'<td class="" style="width: 10%"><select class="form-control input-sm emp_relation_row"  data-toggle="tooltip" title="Select Relation" placeholder="Select Relation" name="emp_relation_row" id="emp_relation_row'+i+'"></select><small style=color: red></small></td>'+
		'<td class=""  style="width: 22%">'+
		'<div class="form-group has-feedback">'+													
		'<input type="text" class="form-control dob_row"  data-toggle="tooltip" title="Select DOB" placeholder="Select DOB" name="dob_row" id="dob_row'+i+'"'+ 
        ' title="Select Start Date"'+
        'maxlength="10" style="text-align: center; height: 30px;" required>'+
        '<span class="fa fa-calendar fa-lg form-control-feedback"></span>'+
        '<small style="color: red;"></small>'+
	    '</div></td>'+
		'<td style="width: 13%;text-align:right;"><input type="text" class="form-control input-sm percentage_row" data-toggle="tooltip" placeholder="Enter percentage" title="Enter Percentage" name="percentage_row" id="percentage_row'+i+'"  onkeypress="return isNumberKey(event,this.id,this.value);"><small style=color: red></small></td>'+
		'<td style="width: 20%"><textarea class="form-control input-sm address_row" data-toggle="tooltip" title="Enter Address"placeholder="Enter Address" name="address_row" id="address_row'+i+'"  title="Enter Address"></textarea><small style=color: red></small></td>'+
		'<td style="width: 2%;text-align:center"><button type="button" class="btn btn-success btn-sm btn-round uploadIcon"  onclick="triggerUpload('+i+')" title="<spring:message code="label.commonUploadFile"></spring:message>"><i class="fa fa-upload" style="padding: 5px;"></i></button>'+
    	   '<span class="fileName"></span>'+
    	   '<input type="file"  value="'+i+'" class="uploadDoc" style="display:none;" id="uploadDoc'+i+'"  accept="image/png,image/jpg,image/jpeg" onchange="readURL(this,'+i+')"  data-docname="test">'+
    	   '<span class="generatedDocName "></span>'+
           '<span class="doc_attach_tran_id hidden">0</span>'+
           '<span class="docpath" style="display:none"></span>'+
           '</td>'+
 		'<td style="width: 100px; height:90px"><img style="width:100px; height:90px"  class="userLogo" id="userLogo'+i+'">'+ 
			'</td>'+ 
		 '<td style="text-align: center;width: 2%">'+
            '<button type="button" onclick="removeItemRow(this)" class="btn btn-danger btn-sm btn-round rowRemove" title="<spring:message code="label.commonDelete"></spring:message>">'+
              '<i class="fa fa-trash" style="padding: 5px;"></i>'+
            '</button>'+
		'</td>'+ 
		
	'</tr>');
	
	
	$("#emp_name_row"+i).alpha();
	$("#address_row"+i).alphanum();
	$("#percentage_row"+i).numeric();
	
		$('[Id^=dob_row]').datepicker({
	    changeMonth: true,
	    changeYear: true,
	    dateFormat: "dd/mm/yy",
	 });
		
		$('#emp_relation_row'+i).select2({
			placeholder:"Select Employee Relation",
			multiple:false,
			allowClear:true,
			width:'100%',
		});

	     $('.InfoTable tr:last').find('input, button ,textarea').tooltipster({delay: 100,theme: 'tooltipster-punk',side: 'bottom'});
	     	 $('.InfoTable tr:last').find('.select2-container').tooltipster({
	     		    functionInit: function(instance, helper){
	     		        var content = $(helper.origin).closest('td').find('select').attr("title");
	     		        instance.content(content);
	     		    },
	     		    delay: 100,
	     		    theme: 'tooltipster-punk',
	     		    side: 'bottom'
	     		});
		
	$.each(listofCountry, function(k, resp) {
        $('#emp_relation_row'+i).append("<option value='"+resp.code_mst_id+"' >"+resp.code_desc+"</option>");
			 });


$("#emp_name_row1,#address_row1,#percentage_row1,#emp_relation_row1").addClass('mandatory').prop('required','required');

}
}

 /*===============================================Ended addItemRow=======================================================================  */
 /*===============================================Start triggerUpload=======================================================================  */
 function triggerUpload(value) {
	 //console.log("--"+value);
	$("#uploadDoc"+value).click();
	
}
/*===============================================End triggerUpload=======================================================================  */
/*===============================================Start getNameDetails=======================================================================  */
 
 	
/*===============================================End getNameDetails=======================================================================  */  
/*===============================================Start saveUpdateDeleteOnFlag=======================================================================  */
function saveUpdateDeleteOnFlag(){
	let tblNomlist = 0;
	$("#InfoTable tbody tr>td>input.form-control").each(function(m){
		   if($(this).val()!=""){
			   tblNomlist++;
		   }	   
		});

	
	tblNomlist = (tblNomlist/4);
	var empName =$("#emp_name").val();
	var empDesig =$("#designation").val();
	var empDOB =$("#DOB").val();
	var empJoinDate =$("#joindate").val();
	let NomNameList = [];
	let NomRelList = [];
	let NomDOBList = [];
	let NomPerList = [];
	let NomAddressList = [];
	let NomPhotoList = [];
	let NomPhotoPathList = [];
	let NomSrnoList = [];
	let NomDetId =[];
	let NomActiveFlag =[];
	let NomDeleteFlag =[];
//console.log(tblNomlist);



$("#InfoTable tbody tr").each(function(index){
	
	//fetch data from table 
	if(($(this).find('.emp_name_row').val()!="") && ($(this).find('.dob_row').val()!="")){
 	NomSrnoList.push($(this).index()+1);
    NomActiveFlag.push($(this).find('.activeFlag').val());
    NomDeleteFlag.push($(this).find('.deleteFlag').val());
 	NomNameList.push($(this).find('.emp_name_row').val()==""?"":$(this).find('.emp_name_row').val());
 	NomRelList.push($(this).find('.emp_relation_row').val()==""?"":$(this).find('.emp_relation_row').val());
 	NomDOBList.push($(this).find('.dob_row').val()==""?"":$(this).find('.dob_row').val());
 	NomPerList.push($(this).find('.percentage_row').val()==""?"":$(this).find('.percentage_row').val());
 	NomAddressList.push($(this).find('.address_row').val()==""?"":$(this).find('.address_row').val());
 	NomPhotoList.push($(this).find(".userLogo").attr('src'));//$('#userLogo2').attr('src')
 	NomDetId.push($(this).find('.nomineeId').text());
	}	
});


/*       for(var i=0;i<tblNomlist;i++){ 
      NomActiveFlag.push($("#InfoTable tbody tr:eq("+i+") td:eq(1) input.activeFlag").val());
      NomDeleteFlag.push($("#InfoTable tbody tr:eq("+i+") td:eq(1) input.deleteFlag").val());
	  NomSrnoList.push($("#InfoTable tbody tr:eq("+i+") td:eq(1) label").text());
      NomNameList.push($("#InfoTable tbody tr:eq("+i+") td:eq(2) input").val());
      NomRelList.push($("#InfoTable tbody tr:eq("+i+") td:eq(3) select").val());
      NomDOBList.push($("#InfoTable tbody tr:eq("+i+") td:eq(4) input").val());
      NomPerList.push($("#InfoTable tbody tr:eq("+i+") td:eq(5) input").val());
      NomAddressList.push($("#InfoTable tbody tr:eq("+i+") td:eq(6) textarea").val());
      NomPhotoList.push($("#InfoTable tbody tr:eq("+i+") td:eq(8) img").prop('src'));
      NomDetId.push($("#InfoTable tbody tr:eq("+i+") td:eq(0) label").text());	
      
    };  
	 */
	 console.log("NomAddressList"+NomAddressList);
	
	 
		 var postParam = {
				empName:empName,
				empDesig:empDesig,
				empDOB:empDOB,
				empJoinDate:empJoinDate,
				NomSrnoList:NomSrnoList,
				NomNameList:NomNameList,
				NomRelList:NomRelList,
				NomDOBList:NomDOBList,
				NomPerList:NomPerList,
				NomAddressList:NomAddressList,
				NomPhotoList:NomPhotoList,
				op_flag:op_flag,
				NomDetId:NomDetId,
				NomActiveFlag:NomActiveFlag,
				NomDeleteFlag:NomDeleteFlag,
			
			} 
	

 	$.ajax({
		url : "${pageContext.request.contextPath}/saveEmpNomineeDetailsArray",
		data : JSON.stringify(postParam),
		method : "post",
		dataType : "json",
		contentType : "application/json",
	 	success : function(res) {

	    	if (JSON.parse(res["responseObj"]).status == "success") {
		          toastr.success(JSON.parse(res["responseObj"]).msg,'Success', {
		            closeButton: true,
		            positionClass: 'toast-bottom-right'
		          });
		          
		          $('#submitBtnName').attr('disabled', 'disabled');
		          	  disAbled();
			          resetForm();
			          loadTableList();
			          		        
			        } else {
		             toastr.error(JSON.parse(res["responseObj"]).msg, 'Error', {
		             closeButton: true,
		             positionClass: 'toast-bottom-right'
		          });

		        }
		}, 
	 

		
	});
		 loadTableList(); 
    
}
/*===============================================End saveUpdateDeleteOnFlag=======================================================================  */ 
/*===============================================Start readURL=======================================================================  */  
 
 function readURL(input,id){
	//console.log(input+"----"+id);
	
	var op_flag= $("#mode").val();
	if($("#flag").val()=="M"){
		img_change_flag="M";
	}
	fName = input.files[0].name;	
	var last = fName.split('.').pop();
	if( last!="jpg" &&  last!="jpeg"  && last!="png" && last!="JPG" && last!="JPEG" && last!="PNG" ){
		alert("File Type not permitted(only jpg,jpeg,png are allowed)");
		$("#browse").val("");
		return false;
	}
	else if (input.files && input.files[0]) {
	   var reader = new FileReader();
	
	   reader.onload = function (e) {
	       $('#userLogo'+id).attr('src', e.target.result);
	         
	   };
	
	   reader.readAsDataURL(input.files[0]);
}
   
}
 /*===============================================End readURL=======================================================================  */ 
/*===============================================start removeItemRow=======================================================================  */ 
 function removeItemRow(trObj){
		if(op_flag =="M"){
			$.confirm({
		        title: 'Are you sure want to Remove ?',
		        content: '',
		        type: 'blue',
		        buttons: {
		            Remove: {
		            	 action: function () {
		            		 if(parseInt($(trObj).closest('tr').find('.chkIdForRemoveRow').val())==0){
		            			 let rowCount = 0;
		            				let removedRow=$(trObj).closest('tr').index();
		            				$(trObj).closest('tr').remove();
		            			console.log("ooooooooooo");
		            				 $('.InfoTable tbody tr').each(function(){
		            					$(this).find('.rowforDel').text($(this).index()+1);
		            				});
		            				
		            		 }else {
		            		 	let rowCount = 0;
		            			let removedRow=$(trObj).closest('tr').index();
		            			$(trObj).closest('tr').hide();
		            			console.log("pppppppppppppppppppppppp"+$(trObj).closest('tr').find(".activeFlag").val());
		            			$(trObj).closest('tr').find(".activeFlag").val("N");
	           				    $(trObj).closest('tr').find(".deleteFlag").val("Y");
	           					
		            			let count=1;
	           					$('.InfoTable tbody tr').each(function(i){
	           						if($(this).is(":visible")){
	           							$(this).find('.rowforDel').text(count);
	           							count++;
	           						}
	           					}); 
	           				
	           				
	           					
	           					 
		            		 }	 
		            	 }
		            },
		             Cancel: {
		                keys: ['N'],
		                action: function () {
		                	
		                }
		            }, 
		        }  
			});		
		 }else{
			let rowCount = 0;
			let removedRow=$(trObj).closest('tr').index();
			//$(trObj).closest('tr').remove();
			
			 $('.InfoTable tbody tr').each(function(){
				$(this).find('.rowCount').text($(this).index()+1);
			});	 
			 
			$('.InfoTable tbody tr:eq('+removedRow+')').remove();
			
			$('.InfoTable tbody tr').each(function(){
				$(this).find('.rowCount').text($(this).index()+1);
			});
		 }  
		
		//headerTotal();
		//getTotalOFTaxInHedr();
	}
 /*===============================================End removeItemRow=======================================================================  */ 
 	/**************************Check if last input of td is empty************************/
	$('#NomnieeForm').on('focus',"input, .select2", function () {
		let valueCurr = $(this).closest('td').prev('td').find('input,select').val();
 		if(valueCurr==""){  
 			$(this).addClass('mandatory').prop('required','required');
 			$(this).closest('td').prev('td').find('input,select').focus().addClass('mandatory').prop('required','required');
 		}
		$(this).closest('tr').nextAll('tr').find('input,.select2,select').removeClass('mandatory').removeAttr('required').removeClass("error").siblings('small').empty();
	})
	/**************************Check if last input of tr is empty************************/
	$('#NomnieeForm').on('keydown focus selec2:open',"[id^=MembName],.select2", function () { 
	var konst;
	for(var i=5;i>=1;i--){
		var m=$(this).closest('tr').prev('tr').find('td:eq('+i+')>input,td:eq('+i+')>select').val();
	        if(m==""){
	        	konst=i;
	        }
		}
		$(this).closest('tr').prev('tr').find('td:eq('+konst+')>input,td:eq('+konst+')>select').focus().addClass('mandatory').prop('required','required');;
})
 
</script>
</head>
<body>

<%@page import="com.vgipl.erp.login.model.User"%>
<%	
		User userObject =(User) request.getSession().getAttribute("currentUser");
		String userName = userObject.getUsername().toString();
		String branchName = userObject.getBranchName().toString();
		String stateName = userObject.getStateName()==null?"null":userObject.getStateName().toString();
		String stateId = userObject.getStateId()==null?"null":userObject.getStateId().toString();
		String branchMstId = userObject.getBranchMstId();
		String userId = userObject.getUserId();
		String DeptId=userObject.getDeptId();
		String workingDate = userObject.getWorkingDate().toString();
		String flag ="N";// request.getAttribute("flag").toString();
	    String rights ="Y~Y~Y~Y~Y~Y";//request.getAttribute("rights").toString();
	    String rightsArr[] = rights.split("~");
%>
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
  <div class="col-lg-12">
				<div class="panel newPanel">
					<div class="panel-heading">
						<div class="panel-control">
							<button class="btn btn-default" data-click="panel-expand">
								<i class="fa fa-expand"></i>
							</button>
							<button class="btn btn-default" data-click="panel-reload">
								<i class="fa fa-refresh"></i>
							</button>
							<button class="btn btn-default" data-click="panel-collapse">
								<i class="fa fa-chevron-down"></i>
							</button>
							<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()"><i class="fa fa-times"></i></button>
							<button onclick="toggleTableAndForm('N',null)"
								class="btn btn-info addNewBtnOnForm">
								<i class="fa fa-plus"></i>&nbsp;Add Employee Nominee
							</button>
						</div>
						<h3 class="panel-title">Employee Nominee List</h3>
					 </div>
					
					
					
		<div class="panel-body">
		    <div class="row showTableDiv">
				<div class="table-responsive">
					<table class="table table-striped table-bordered table-hover detailList" >
						<thead>
							<tr>
								<th style="text-align: center"><spring:message code="label.srno"></spring:message></th>
								<th style="text-align: center"><spring:message code="label.employeeName"></spring:message></th>
								<th style="text-align: center"><spring:message code="label.designationMstId"></spring:message></th>
								<th style="text-align: center"><spring:message code="label.dob"></spring:message></th> 
								<th style="text-align: center">Action</th>
								
							</tr>
						</thead>
						<tbody class="detailListTableBody">
						</tbody>
					</table>
				</div>
			   </div>
			   
			   <div class="row showFormDiv">
				<form id="NomnieeForm">
	
			<!--Row1  -->
					<div class="row">
				     <div class="col-md-4">
					  <div class="form-group">
						<label class=" control-label"><spring:message code="label.employeeName"></spring:message><small style="color: red;">*</small></label>	
						   <select  id="emp_name" name="emp_name" class="form-control input-sm mandatory" data-toggle="tooltip" title="Select Name"
						    title="Select Employee Name" ">	
						    <option>---Select---</option>
					   	</select>	<small style="color: red;"></small>
					  </div>
				   </div>
						<div class="col-md-4">
						<div class="form-group">
								<label class="control-label"><spring:message code="label.designationMstId"></spring:message><small style="color: red;">*</small></label> 
								<input name="designation" type="text" onchange="" id="designation"
									class="form-control designation input-sm k-textbox mandatory"maxlength="200"
									placeholder="Enter Designation" title="Enter Designation">
								<small style="color: red;"></small>
							</div>
						</div>
						<div class="col-md-2">
						<div class="form-group">
								<label class="control-label"><spring:message code="label.dob"></spring:message></label> 
								<input name="dob" type="text" id="dob"
									class="form-control dob input-sm k-textbox" maxlength="400"
									placeholder="Enter DOB" title="Enter DOB">
								<small style="color: red;"></small>
							</div>
						</div>
						<div class="col-md-2">
						<div class="form-group">
								<label class="control-label"><spring:message code="label.joindate"></spring:message></label> 
								<input name="joindate" type="text" id="joindate"
									class="form-control dob input-sm k-textbox"maxlength="400"
									placeholder="Enter Join Date" title="Enter Join Date">
								<small style="color: red;"></small>
							</div>
						</div>
					</div>	
	
	
	                  <div class="">
						<button type="button" class="pull-right btn btn-primary addBtn" onclick="addItemRowButton()" style="margin: 10px;"><i class="fa fa-plus"></i> <spring:message code="label.addItem"></spring:message></button>
					  </div>
	
		              <div class="table-responsive">
                    	<table class="table table-striped table-hover table-vcenter table-condensed table-bordered InfoTable" id="InfoTable">
                    		<thead>
                               <tr>
                                <th style="text-align: center" hidden>Nominee Id</th>
                                <th style="text-align: center"><spring:message code="label.srno"></spring:message></th>
                                <th style="text-align: center;"><spring:message code="label.memberName"></spring:message></th>
                                <th style="text-align: left;">Relation with Employee</th>
                                <th style="text-align: center;"><spring:message code="label.dob"></spring:message></th>
                                <th style="text-align: center;"><spring:message code="label.percentage"></spring:message></th>
                                <th style="text-align: center;"><spring:message code="label.address"></spring:message></th>
                                <th style="text-align: center;"><spring:message code="label.SO.upload"></spring:message></th>
                                <th style="text-align: center;"><spring:message code="label.photo"></spring:message></th>
                                 <th style="text-align: center;"><spring:message code="label.action"></spring:message></th>
                                
                               </tr>
                           </thead>
                           <tbody class="InfoTableBody">
                           
                           </tbody>
                    	</table>
                     </div>
	
				<div class="visibleSubmitIfHaveRight" style="  margin-top: 5%;">
						<button  class="btn btn-primary submitBtnName" type="button" id="submitBtnName"
						 onclick="saveUpdateDeleteOnFlag()"></button>
						&nbsp;
						<button type="button" class="btn btn-danger" onclick="resetForm()">Reset</button>
				</div>
									
		        </form>
		       </div>
		 </div>
       </div>
	  </div>
</body>

</html>