<!--=====================================================================
------------This JSP Page Generated By System---
Original Author - Aishwarya Domde
Creation Date	- Jul 10, 2019 5:23:28 PM
Project Name	- MLWB 
Module Name		- 
Page\Class\etc... Name -: Employee Family Details
Description	-
Link		-
	 Modify Author	  -    Modify Date    -    
1)		
2)
3)
=====================================================================
-->
<%@taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Service Book MIS</title>

<link href="assets/plugins/chosen/chosen.min.css" rel="stylesheet">
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<link href="assets/plugins/select2/select2.min.css" rel="stylesheet">
<!--For Datepicker -->
<link href="assets/plugins/jqueryUI-DatepickerCSS/datepicker.css" rel="stylesheet">
<script src="assets/plugins/jquery-ui/jquery-ui.min.js"></script>
<!--Bootstrap Table -->
<link href="assets/plugins/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet">
<link href="assets/plugins/datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<!--Chosen -->
<script src="assets/plugins/chosen/chosen.jquery.min.js"></script>
<!--DataTables -->
<script src="assets/plugins/datatables/media/js/jquery.dataTables.js"></script>
<script src="assets/plugins/datatables/media/js/dataTables.bootstrap.js"></script>
<script src="assets/plugins/datatables/extensions/Responsive/js/dataTables.responsive.min.js"></script>
<!--Bootstrap Validator -->
<script src="assets/plugins/bootstrap-validator/bootstrapValidator.min.js"></script>
<!--Bootstrap Validator -->
<script src="assets/plugins/jquery-validation/jquery.validate.min.js"></script>
<script src="assets/panelActions.js"></script>
<!--Numeric Input -->
<script src="assets/plugins/numeric/jquery.numeric.min.js"></script>
<script src="assets/plugins/mask-input/jquery.mask.js"></script>
<script src="assets/plugins/mask-input/jquery.mask.min.js"></script>
<script src="assets/plugins/alphanum/jquery.alphanum.js"></script>
<script src="assets/plugins/select2/select2.min.js"></script>
<script src="assets/js/focusOnEnter.js"></script>

<script type="text/javascript">

var myDate = new Date();
var TodaySet = myDate.getDate() + '/' +(myDate.getMonth()+1) + '/' +myDate.getFullYear();
$(document).ready(function(){
    $("select").select2({
		placeholder:"Select",
		width:'100%',
		multiple: false,
		allowClear:true,		
	});
    $("#ServD2_Tbl").DataTable();
	/***********************Calling all Employee for availing Employee list*******************/
	$.ajax({  
	    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
	    data : JSON.stringify({
			"param" : "NULL~"+$("#branchMstId").val(),
			"sqlMstId" :7159
		}),
		method : "post",
		dataType : "json",
		contentType : "application/json",
		async: false,
	    success: function(response){
	    	let resp = JSON.parse(response["codeList"])
	    	$("#empName").append('<option value="">Select empName</option>');
	    	$.each(resp, function(key,value) {
					nKey = parseInt(key)+1;
					$("#empName").append('<option value="'+resp[key].employee_mst_id+'"> '+resp[key].employee_name+'');
			}); 
	      },
	 });
	/*****************After Selecting Employee Setting Other all information**************/
	$("#empName").on("select2:select",function(){
		var EmpID =$("#empName").val();
		var branchID= $("#branchMstId").val();
	    $.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7283,
				"param" : EmpID+"~NULL",
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response1){
		    	let respList1 = JSON.parse(response1["codeList"]);
		    	$.each(respList1, function(key,value) {
		    	    $("#EMIS_Name").val(respList1[key].employee_name);
		    	    $("#EMIS_TempAddr").val(respList1[key].address_1);
		    	    $("#EMIS_DeclAddr").val(respList1[key].p_address_1);
		    	    $("#EMIS_ConfBday").val(respList1[key].employee_birth_date);
		    	    $("#EMIS_Eheight").val(respList1[key].employee_height);
		    	    $("#EMIS_FName").val(respList1[key].employee_fathername);
		    	    $("#EMIS_FAddr").val(respList1[key].father_address_1);
		    	    $("#govEmpSign").val(respList1[key].medical_officer_name);
		    	    $("#EMIS_AttactedPerson").val();
		    	    $("#EMIS_AttactedDesig").val();
		    	    $("#EMIS_AttactedDt").val();
		    	    $("#CerNO").val(respList1[key].medical_cert_no);
		    	    $("#CerDT").val(respList1[key].medical_cert_date);
		    	    $("#CerAllotName").val(respList1[key].medical_officer_name);
		    	    $("#CerAllotDesign").val(respList1[key].medical_officer_designation);
		    	    $("#EMIS_BIdenty").val(respList1[key].birth_identication);
		    	    $("#EMIS_EduJoin").val(respList1[key].medical_officer_designation);
		    	    $("#EMIS_AJoinEdu").val(respList1[key].medical_officer_designation);
		    	    $("#EMIS_Cast").val(respList1[key].cast_name==null?"":respList1[key].cast_name+","
				    	    +respList1[key].religion_name==null?"":respList1[key].religion_name);
				}); 
		      },
		 });
		 /*************Service Details8 -Ajax Invocation for Education Details*****************/
		$.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7297,						//7284,
				"param" : ""+EmpID+"",
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response2){ 	
	       	 	if ($.fn.DataTable.isDataTable('#ServD8_Tbl')) {
	                $('#ServD8_Tbl').DataTable().destroy();
	            }
			    let education=[];
			    let keyVal=0;
		    	let respList2 = JSON.parse(response2["codeList"]);
		    	$.each(respList2, function(key,value) {
		    	    keyVal=keyVal+1;
		    	    education.push([keyVal,respList2[key]['education'],
	         			(respList2[key]["passing_year"]=="null"?"":respList2[key]["passing_year"]),
	         			(respList2[key]["percentage_marks"]==null?"":respList2[key]["percentage_marks"]),
	   					(respList2[key]["grade"]==null?"":respList2[key]["grade"]),
	   		   			(respList2[key]["board_university"]==null?"":respList2[key]["board_university"]),
	   		   			(respList2[key]["remarks"]==null?"":respList2[key]["remarks"])])
		    	});
		    	$('#ServD8_Tbl').DataTable({
	                 data: education,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageinfo	:false,
	                 scrollCollapse: true,
	                 responsive: true,
	              
	             });
		    }
		 });
		 /********************Getting Year **************************/
		 $.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7313,						//7284,
				"param" : branchID+'~'+EmpID,
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response12){
		        let resp12 = JSON.parse(response12["codeList"]);
		    	$("#empYr").append('<option value="">Select empName</option>');
		    	$.each(resp12, function(key,value) {
						nKey = parseInt(key)+1;
						$("#empYr").append('<option value="'+resp12[key].st_salary_year+'"> '+resp12[key].st_salary_year+'');
				});
			 }
		 });
		 /*************Service Details6 -Ajax Invocation for Transfer Details*****************/
		$.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7306,						//7284,
				"param" : EmpID+'~'+branchID,
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response6){		     	
	       	 	if ($.fn.DataTable.isDataTable('#ServD6_Tbl')) {
	                $('#ServD6_Tbl').DataTable().destroy();
	            }

	    		$("#empYr option:eq(1)").prop('selected', true).trigger("change");
			    let education=[];
			    let keyVal=0;
		    	let respList6 = JSON.parse(response6["codeList"]);
		    	$.each(respList6, function(key,value) {
		    	    keyVal=keyVal+1;
		    	    education.push([keyVal,respList6[key]["transfer_type"],
	         			(respList6[key]["transfer_order"]=="null"?"":respList6[key]["transfer_order"]),
	         			(respList6[key]["transfer_date"]==null?"":respList6[key]["transfer_date"]),
	         			(respList6[key]["transfer_from"]==null?"":respList6[key]["transfer_from"]),
	         			(respList6[key]["transfer_to"]==null?"":respList6[key]["transfer_to"]),
	         			(respList6[key]["relieve_date"]==null?"":respList6[key]["relieve_date"]),
	   					(respList6[key]["join_date"]==null?"":respList6[key]["join_date"])])
		    	});
		    	$('#ServD6_Tbl').DataTable({
	                 data: education,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageinfo	:false,
	                 scrollCollapse: true,
	                 responsive: true,
	             });
		    }
		 });
		/*************Service Details7 -Ajax Invocation for Trainee Details*****************/
		$.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7315,						//7284,
				"param"    :EmpID+'~'+branchID,							//  '50~11', 			// ""+EmpID+"",
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response7){		
			    console.log(response7)     	
		       	 	if ($.fn.DataTable.isDataTable('#ServD7_Tbl')) {
		                $('#ServD7_Tbl').DataTable().destroy();
		            }
				    let education=[];
				    let keyVal=0;
			    	let respList7 = JSON.parse(response7["codeList"]);
			    	$.each(respList7, function(key,value) {
			    	    keyVal=keyVal+1;
			    	    education.push([keyVal,
			    	    respList7[key]["trainig_name"],
			    	    respList7[key]["period_mm_yyyy"],
			    	    respList7[key]["trainig_place_name"],
			    	    respList7[key]["period_from"],
			    	    respList7[key]["period_to"],
			    	    respList7[key]["name_of_institute"],
			    	    respList7[key]["total_days"],
			    	    respList7[key]["trainig_type_name"],
			    	    respList7[key]["sponsor_by"],
			    	    respList7[key]["remark"]
						])
			    	});
			    	$('#ServD7_Tbl').DataTable({
		                 data: education,
		                 "autoWidth": false,
		                 deferRender: true,
		                 pageinfo	:false,
		                 scrollCollapse: true,
		                 responsive: true,
	              
		             });
		    }
		 });
		 /*************Service Details9 -Ajax Invocation for Family Details*****************/
		$.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7298,						//7284,
				"param" :""+EmpID+"",
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response9){ 	
	       	 	if ($.fn.DataTable.isDataTable('#ServD9_Tbl')) {
	                $('#ServD9_Tbl').DataTable().destroy();
	            }
			    let education=[];
			    let keyVal=0;
		    	let respList9 = JSON.parse(response9["codeList"]);
		    	$.each(respList9, function(key,value) { 
		    	    keyVal=keyVal+1;
		    	    education.push([keyVal,respList9[key]["member_name"],
	         			(respList9[key]["birth_date"]=="null"?"":respList9[key]["birth_date"]),
	         			(respList9[key]["occupation"]==null?"":respList9[key]["occupation"]),
	   					(respList9[key]["relation"]==null?"":respList9[key]["relation"]),
	   		   			(respList9[key]["photo"]==null?"":respList9[key]["photo"])])
		    	});
		    	$('#ServD9_Tbl').DataTable({
	                 data: education,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageinfo	:false,
	                 scrollCollapse: true,
	                 responsive: true,
	              
	             });
		    }
		 });
		 /*************Service Details10 -Ajax Invocation for Nomeeine Details*****************/
		$.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7299,						//7284,
				"param" : ""+EmpID+"",
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response10){		     	
	       	 	if ($.fn.DataTable.isDataTable('#ServD10_Tbl')) {
	                $('#ServD10_Tbl').DataTable().destroy();
	            }
			    let education=[];
			    let keyVal=0;
		    	let respList10 = JSON.parse(response10["codeList"]);
		    	$.each(respList10, function(key,value) {
		    	    keyVal=keyVal+1;
		    	    education.push([keyVal,respList10[key]["member_name"],
	         			(respList10[key]["birth_date"]=="null"?"":respList10[key]["birth_date"]),
	         			(respList10[key]["occupation"]==null?"":respList10[key]["occupation"]),
	   					(respList10[key]["relation"]==null?"":respList10[key]["relation"]),
	   		   			(respList10[key]["photo"]==null?"":respList10[key]["photo"])])
		    	});
		    	$('#ServD10_Tbl').DataTable({
	                 data: education,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageinfo	:false,
	                 scrollCollapse: true,
	                 responsive: true,
	              
	             });
		    }
		 });
		 /*************Service Details11 -Ajax Invocation for Daily Dairy Details*****************/
		$.ajax({  
		    url:"${pageContext.request.contextPath}/app/common/getCodeList",  
		    data : JSON.stringify({
				"sqlMstId" :7301,						//7284,
				"param" : 'null~'+EmpID+'~null~null', 
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response11){		     	
	       	 	if ($.fn.DataTable.isDataTable('#ServD11_Tbl')) {
	                $('#ServD11_Tbl').DataTable().destroy();
	            }
			    let education=[];
			    let keyVal=0;
		    	let respList11 = JSON.parse(response11["codeList"]);
		    	$.each(respList11, function(key,value) {
		    	    keyVal=keyVal+1;
		    	    education.push([keyVal,respList11[key]["work_date"],
	         			(respList11[key]["from_time"]=="null"?"":respList11[key]["from_time"]),
	         			(respList11[key]["upto_time"]==null?"":respList11[key]["upto_time"]),
	   					(respList11[key]["work_detail"]==null?"":respList11[key]["work_detail"])])
		    	});
		    	$('#ServD11_Tbl').DataTable({
	                 data: education,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageinfo	:false,
	                 scrollCollapse: true,
	                 responsive: true,
	              
	             });
		    }
		 });
		 /***************************************************************************/
		    let postParametersView={
		    		branchId : $("#branchMstId").val(),
		   			userId	 : $("#userId").val(),
					EmpMstId :EmpID,
					desc	 : null,
					frmdate	 : null,
					todate	 :"'"+TodaySet+"'"
		    	    };
			$.ajax({ 
				url : "${pageContext.request.contextPath}/app/payroll/EmpLeave/LeaveApplication/getLeaveApplication",
				data : JSON.stringify(postParametersView),
				method : "post",
				dataType : "json",
				contentType : "application/json",
				success : function(res) {
				if ($.fn.DataTable.isDataTable('#ServD4_Tbl')) {
		                $('#ServD4_Tbl').DataTable().destroy();
		            }
		            $("#ServD4_Tbl tbody").empty();
		        	let keyVal=0;	let datacourt=[];
		        	 var ListDetails = JSON.parse(res["EmpLeaveDetails"]);
		        	 $.each(ListDetails, function (key,i) {
		         		keyVal=keyVal+1;        		
		  				datacourt.push([keyVal,ListDetails[key]['leave_name'],ListDetails[key]['opening_leaves'],
		  	  				ListDetails[key]['total_allotted'],ListDetails[key]['total_used'],ListDetails[key]['bal_leaves']]) ; 
		         	 });
		       	 	$('#ServD4_Tbl').DataTable({
		                data: datacourt,
		                "autoWidth": false,
		                deferRender: true,
		                pageLength: 10,
		                "bLengthChange": false,
		                info: false,
		                scrollCollapse: true,
		                responsive: true,
		            }); 
		 		},
		 		failure : function() {
		 			console.log("failed to load list.");
		 		}	
			});
	});
	 /*************Service Details5 -Ajax Invocation for Salary Details*****************/
	$("#empYr").on("change",function(){		
		var yr=$("#empYr").val();
		var EmpID =$("#empName").val();
		var branchID= $("#branchMstId").val();
		if(yr!=""){
		$.ajax({  
	  	  	url:"${pageContext.request.contextPath}/app/common/getCodeList",  
	    	data : JSON.stringify({
				"sqlMstId" :7308,						//7284,
				"param" : EmpID+'~'+yr+'~'+branchID, 
			}),
			method : "post",
			dataType : "json",
			contentType : "application/json",
			async: false,
		    success: function(response5){		     	
	       	 	if ($.fn.DataTable.isDataTable('#ServD5_Tbl')) {
	                $('#ServD5_Tbl').DataTable().destroy();
	                $('#ServD5_Tbl tbody').empty()
	            }
			    let salary=[];
			    let keyVal=0;
		    	let respList5 = JSON.parse(response5["codeList"]);
		    	$.each(respList5, function(key,value) {
	    	    keyVal=keyVal+1;
	    	    salary.push([keyVal,
	    	        (respList5[key]["salry_year"]),
	    	        (respList5[key]["st_salary_month"]),
	    	        (respList5[key]["st_prd_days"]),
	    	        (respList5[key]["basic"]),
	    	        (respList5[key]["gp"]),
	    	        (respList5[key]["total_basic"]),
	    	        (respList5[key]["da"]),
	    	        (respList5[key]["cca"]),
	    	        (respList5[key]["hra"]),
	    	        (respList5[key]["lta"]),
	    	        (respList5[key]["medical"]),
	    	        (respList5[key]["cash"]),
	    	        (respList5[key]["special"]),
	    	        (respList5[key]["washing"]),
	    	        (respList5[key]["oth_ear1"]),
	    	        (respList5[key]["oth_ear2"]),
	    	        (respList5[key]["oth_ear3"]),
	    	        (respList5[key]["da_diff"]),
	    	        (respList5[key]["total_earning"]),
	    	        (respList5[key]["cpf"]),
	    	        (respList5[key]["pt"]),
	    	        (respList5[key]["gpf"]),
	    	        (respList5[key]["society"]),
	    	        (respList5[key]["income_tax"]),
	    	        (respList5[key]["staff_advance"]),
	    	        (respList5[key]["lic"]),
	    	        (respList5[key]["gis"]),
	    	        (respList5[key]["hba"]),
	    	        (respList5[key]["vl_int"]),
	    	        (respList5[key]["bank_loan"]),
	    	        (respList5[key]["com"]),
	    	        (respList5[key]["salary_adv"]),
	    	        (respList5[key]["soc_mnt"]),
	    	        (respList5[key]["stamp"]),
	    	        (respList5[key]["va"]),
	    	        (respList5[key]["oth_ded1"]),
	    	        (respList5[key]["oth_ded2"]),
	    	        (respList5[key]["oth_ded3"]),
	    	        (respList5[key]["cpf_on_da_diff"]),
	    	        (respList5[key]["total_deduction"]),
	    	        (respList5[key]["net_salary"])
   					])
	    		});
		    	$('#ServD5_Tbl').DataTable({
	                 data: salary,
	                 "autoWidth": false,
	                 deferRender: true,
	                 pageinfo	:false,
	                 scrollCollapse: true,
	//                 responsive: true,
	//                 "scrollX": true
	             });
	    	}
	 	});
	 }
 });
 	
});
</script>
</head>
<body>
<%@page import="com.vgipl.erp.common.AllUtils"%>
<%@page import="com.vgipl.erp.login.model.User"%>	
<%
	User userObject = (User) request.getSession().getAttribute("currentUser");
	String userPost = String.valueOf(request.getSession().getAttribute("userPost"));	
	String userName = userObject.getUsername();
	String branchName = userObject.getBranchName();
	String branchAddress = userObject.getBranchAddress();
	String branchMstId = userObject.getBranchMstId();
	String userId = userObject.getUserId();
	String deptId = userObject.getDeptId();
%>	
<input type="hidden" id="branchMstId" value="<%=branchMstId%>">
<input type="hidden" id="userId" value="<%=userId%>">
<input type="hidden" id="finYrId" value="<%=userObject.getLoggedInFinYrId()%>">
<input type="hidden" id="deptIdF" value="<%=deptId%>">
<input type="hidden" id="branchName" value="<%=branchName%>">
<input type="hidden" id="branchAddress" value="<%=branchAddress%>">
<input type="hidden" id="userPost" value="<%=userPost%>">
<input type="hidden" id="postUserId" value="">
<input type="hidden" id="userPostName" value="">
<span class="demo" style="display:none;"><%=userPost%></span>
<input type="hidden" name="mode" id="mode" value="1" />
<!------------------------------------------------------------>
<div class="row showFormDiv">
	<div class="col-lg-12">
			<div class="panel newpanel">
				<div class="panel-heading">
					<div class="panel-control">						
						<button class="btn btn-default" data-click="panel-collapse">
							<i class="fa fa-chevron-down"></i>
						</button>
						<button class="btn btn-default closeFormBtn" data-dismiss="panel" onclick="closeActiveForm()">
							<i class="fa fa-times"></i>
						</button>
					</div>
					<h3 class="panel-title formTitle"> Service Book MIS </h3>
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-sm-3">
							<select name="empName" class="form-control" data-toggle="tooltip" title="Select Employee Name "  id="empName">
							</select>
						</div>
					</div>
					<div class="col-sm-12" id="tab1" data-role="tab">
						<ul class="nav nav-tabs">
							<li class="active firstTab" >
								<a href="#tabContent1" data-toggle="tab" id="tabLabel1">Servies Details1</a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent2" id="tabLabel2">Service Details2</a>
							</li>
								<li class="" >
								<a data-toggle="tab" href="#tabContent3"  id="tabLabel3">Service Book Leave Details</a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent4" id="tabLabel4">Leave Details</a>
							</li>
								<li class="" >
								<a data-toggle="tab" href="#tabContent5"  id="tabLabel5">Salary Details</a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent6" id="tabLabel6">Transfer Details</a>
							</li>
							<li class="" >
								<a data-toggle="tab" href="#tabContent7" id="tabLabel7">Training Details</a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent8" id="tabLabel8">Education Details</a>
							</li>
							<li class="" >
								<a data-toggle="tab"  href="#tabContent9"id="tabLabel9">Family Details</a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent10" id="tabLabel10">Nominee Details</a>
							</li>
							<li class="">
								<a data-toggle="tab" href="#tabContent11" id="tabLabel11">Daily Dairy Detail</a>
							</li>
						</ul>
						<!-- ----------------------TABS Starts------------- -->
						<br>
						<div class="tab-content">
						  	<div class="tab-pane fade active in" id="tabContent1">
								<div class=row>
									<div class="col-sm-3">									
										<div class="form-group">
										<label for="EMIS_Name" class="control-label"><spring:message code="label.EMIS_Name"></spring:message></label> 
										<input type="text" disabled class="form-control" id="EMIS_Name">                              
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<label for="EMIS_Cast" class="control-label"><spring:message code="label.EMIS_Cast"></spring:message></label>   
											<input type="text" disabled class="form-control" id="EMIS_Cast">
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											<label for="EMIS_TempAddr" class="control-label">
											i)<spring:message code="label.EMIS_TempAddr"></spring:message></label>
											<textarea disabled class="form-control" id="EMIS_TempAddr" rows="2" style="resize: vertical;"></textarea>
										</div>
									</div>
									<div class="col-sm-3">							
										<div class="form-group">
											<label for="EMIS_DeclAddr" class="control-label">
											ii)<spring:message code="label.EMIS_DeclAddr"></spring:message></label>
											<textarea disabled class="form-control" id="EMIS_DeclAddr" rows="2" style="resize: vertical;"></textarea> 
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-3">			
										<div class="form-group">
											<label for="EMIS_ConfBday" class="control-label"><spring:message code="label.EMIS_ConfBday"></spring:message></label>
											<input type="text" disabled class="form-control" id="EMIS_ConfBday">
										</div>
									</div>
									<div class="col-sm-3">			
										<div class="form-group">
											<label for="EMIS_Eheight" class="control-label"><spring:message code="label.EMIS_Eheight"></spring:message></label>
											<input type="text" disabled class="form-control" id="EMIS_Eheight">
										</div>
									</div>
									<div class="col-sm-3">			
										<div class="form-group">
											<label for="EMIS_FName" class="control-label"><spring:message code="label.EMIS_FName"></spring:message></label>
												<input type="text" disabled class="form-control" id="EMIS_FName"> 
										</div>
									</div>
									<div class="col-sm-3">			
										<div class="form-group">
											<label for="EMIS_FAddr" class="control-label"><spring:message code="label.EMIS_FAddr"></spring:message></label>
											<textarea disabled class="form-control" id="EMIS_FAddr" rows="2" style="resize: vertical;"></textarea>
									</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-3">
										<div class="form-group">
											<label for="EMIS_BIdenty" class="control-label"><spring:message code="label.EMIS_BIdenty"></spring:message></label>
											<input type="text" disabled class="form-control" id="EMIS_BIdenty">
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
											i) <label for="EMIS_EduJoin" class="control-label"><spring:message code="label.EMIS_EduJoin"></spring:message></label> 
											<input type="text" disabled class="form-control" id="EMIS_EduJoin">
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
										ii)<label for="EMIS_AJoinEdu" class="control-label"><spring:message code="label.EMIS_AJoinEdu"></spring:message></label>
										<input type="text" disabled class="form-control" id="EMIS_AJoinEdu">
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
										<label for="govEmpSign" class="control-label"><spring:message code="label.govEmpSign"></spring:message></label>	
										<input type="text" disabled class="form-control" id="govEmpSign">
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<label for="EMIS_medTestDesc" class="control-label" style="font-weight: 600;"><spring:message code="label.EMIS_medTestDesc"></spring:message></label>
									</div>
									<br>
									<div class="col-sm-3">
										<div class="form-group">
										<label for="CerNO" class="control-label"><spring:message code="label.CerNO"></spring:message></label> 
										<input type="text" disabled class="form-control" id="CerNO" >
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
										<label for="CerDT" class="control-label"><spring:message code="label.CerDT"></spring:message></label> 	
										<input type="text" disabled class="form-control" id="CerDT" >
										</div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
										<label for="CerAllotName" class="control-label"><spring:message code="label.CerAllotName"></spring:message></label>	
										<input type="text" disabled class="form-control" id="CerAllotName" ></div>
									</div>
									<div class="col-sm-3">
										<div class="form-group">
										<label for="CerAllotDesign" class="control-label"><spring:message code="label.CerAllotDesign"></spring:message></label>
										<input type="text" disabled class="form-control" id="CerAllotDesign" >
										</div>
									</div>
								</div>
							</div>
							<!-- ---------------------------2TAB------------------------>
							<div class="tab-pane fade" id="tabContent2">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD2_Tbl">
									<thead>
									<tr>
										<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
										<th><label for="EMIS_PayScale" class="control-label"><spring:message code="label.EMIS_PayScale"></spring:message></label></th>
										<th><label for="EMIS_GradePay" class="control-label"><spring:message code="label.EMIS_GradePay"></spring:message></label></th>
										<th><label for="EMIS_SelPost" class="control-label"><spring:message code="label.EMIS_SelPost"></spring:message></label></th>
										<th><label for="EMIS_Post_YN" class="control-label"><spring:message code="label.EMIS_Post_YN"></spring:message></label></th>
										<th><label for="IsPermnent" class="control-label"><spring:message code="label.IsPermnent"></spring:message></label></th>
										<th><label for="EMIS_PerAppnt" class="control-label"><spring:message code="label.EMIS_PerAppnt"></spring:message></label></th>
										<th><label for="EMIS_postAppnt" class="control-label"><spring:message code="label.EMIS_postAppnt"></spring:message></label></th>
										<th><label for="EMIS_SalasAppnt" class="control-label"><spring:message code="label.EMIS_SalasAppnt"></spring:message></label></th>
										<th><label for="EMIS_SOverpayment" class="control-label"><spring:message code="label.EMIS_SOverpayment"></spring:message></label></th>
										<th><label for="EMIS_Orevenu" class="control-label"><spring:message code="label.EMIS_Orevenu"></spring:message></label></th>
										<th><label for="EMIS_AppDate" class="control-label"><spring:message code="label.EMIS_AppDate"></spring:message></label></th>
										<th><label for="EMIS_GovEmpSign" class="control-label"><spring:message code="label.EMIS_GovEmpSign"></spring:message></label></th>
										<th><label for="EMIS_CerEmpSign" class="control-label"><spring:message code="label.EMIS_CerEmpSign"></spring:message></label></th>
										<th><label for="EMIS_AppExp" class="control-label"><spring:message code="label.EMIS_AppExp"></spring:message></label></th>
										<th><label for="EMIS_AppExpReason" class="control-label"><spring:message code="label.EMIS_AppExpReason"></spring:message></label></th>
										<th><label for="EMIS_FrmDate" class="control-label"><spring:message code="label.EMIS_FrmDate"></spring:message></label></th>
										<th><label for="EMIS_ToDate" class="control-label"><spring:message code="label.EMIS_ToDate"></spring:message></label></th>
										<th><label for="EMIS_rewards" class="control-label"><spring:message code="label.EMIS_rewards"></spring:message></label></th>
										<th><label for="EMIS_EmpStatDate" class="control-label"><spring:message code="label.EMIS_EmpStatDate"></spring:message></label></th>
										<th><label for="EMIS_RefNOS" class="control-label"><spring:message code="label.EMIS_RefNOS"></spring:message></label> </th>
										<th><label for="EMIS_RefDate" class="control-label"><spring:message code="label.EMIS_RefDate"></spring:message></label> </th>
										</tr>
									</thead>
								</table>
							</div>	
							<!-- ---------------------------3TAB------------------------>
							<div class="tab-pane fade" id="tabContent3">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD3_Tbl">
									<thead>
									<tr>
									<th>dnfghfweghfve nbdvfef</th>
									</tr>
									</thead>
								</table>
							</div>
							<!-- ---------------------------4TAB------------------------>
							<div class="tab-pane fade" id="tabContent4">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD4_Tbl">
									<thead>
									<tr>
										<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
										<th><label for="EMIS_LeaveType1" class="control-label"><spring:message code="label.EMIS_LeaveType1"></spring:message></label></th>
										<th><label for="openLeave" class="control-label"><spring:message code="label.openLeave"></spring:message></label></th>
										<th><label for="AllotLeave" class="control-label"><spring:message code="label.AllotLeave"></spring:message></label></th>
										<th><label for="usedLeave" class="control-label"><spring:message code="label.usedLeave"></spring:message></label></th>
										<th><label for="AvailLeave" class="control-label"><spring:message code="label.AvailLeave"></spring:message></label></th>
									</tr>
								</thead>
								</table>
							</div>
							<!-- ---------------------------5TAB------------------------>
							<div class="tab-pane fade" id="tabContent5">
							<div class="col-sm-12">
								<div class="col-sm-3 ">
									<label class="control-label">Year</label>
									<select name="empYR" class="form-control" data-toggle="tooltip" title="Select Year "  id="empYr">
									</select>
								</div>
							</div>
							<div class="col-sm-12" style="overflow: auto;top:8px;border: 1px solid #e3dddd;">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD5_Tbl">
									<thead>
									<tr>
										<th rowspan="2"><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
									<th colspan="19"><label for="EMIS_Income" class="control-label"><spring:message code="label.EMIS_Income"></spring:message></label>   </th>			
										<th colspan="21"><label for="EMIS_Cut" class="control-label"><spring:message code="label.EMIS_Cut"></spring:message></label>  </th>	
										<th rowspan="2"><label for="EMIS_NetSal" class="control-label"><spring:message code="label.EMIS_NetSal"></spring:message></label>  </th>
									</tr>
									<tr>
										<th><label for="EMIS_SalYr" class="control-label"><spring:message code="label.EMIS_SalYr"></spring:message></label> </th>
										<th><label for="EMIS_SalMonth" class="control-label"><spring:message code="label.EMIS_SalMonth"></spring:message></label></th>
										<th><label for="EMIS_Days" class="control-label"><spring:message code="label.EMIS_Days"></spring:message></label>  </th>
										<th><label for="EMIS_basic" class="control-label"><spring:message code="label.EMIS_basic"></spring:message></label></th>
										<th><label for="EMIS_GP" class="control-label"><spring:message code="label.EMIS_GP"></spring:message></label>      </th>
										<th><label for="EMIS_totBasic" class="control-label"><spring:message code="label.EMIS_totBasic"></spring:message></label></th>
										<th><label for="EMIS_Dallow" class="control-label"><spring:message code="label.EMIS_Dallow"></spring:message></label>  </th>
										<th><label for="EMIS_cityPay" class="control-label"><spring:message code="label.EMIS_cityPay"></spring:message></label></th>
										<th><label for="EMIS_Hrent" class="control-label"><spring:message code="label.EMIS_Hrent"></spring:message></label>    </th>
										<th><label for="EMIS_HomeRentPay" class="control-label"><spring:message code="label.EMIS_HomeRentPay"></spring:message></label></th>
										<th><label for="EMIS_LeavePay" class="control-label"><spring:message code="label.EMIS_LeavePay"></spring:message></label>  </th>
										<th><label for="EMIS_cash" class="control-label"><spring:message code="label.EMIS_cash"></spring:message></label>  </th>
										<th><label for="EMIS_apper" class="control-label"><spring:message code="label.EMIS_apper"></spring:message></label></th>
										<th><label for="EMIS_washing" class="control-label"><spring:message code="label.EMIS_washing"></spring:message></label></th>
										<th><label for="EMIS_OEarn1" class="control-label"><spring:message code="label.EMIS_OEarn1"></spring:message></label></th>
										<th><label for="EMIS_OEarn2" class="control-label"><spring:message code="label.EMIS_OEarn2"></spring:message></label></th>
										<th><label for="EMIS_OEarn3" class="control-label"><spring:message code="label.EMIS_OEarn3"></spring:message></label></th>
										<th><label for="EMIS_DffDAllow" class="control-label"><spring:message code="label.EMIS_DffDAllow"></spring:message></label></th>
										<th><label for="EMIS_TotCash" class="control-label"><spring:message code="label.EMIS_TotCash"></spring:message></label>    </th>
										<th><label for="EMIS_ConProfit" class="control-label"><spring:message code="label.EMIS_ConProfit"></spring:message></label></th>
										<th><label for="EMIS_ContriProfFund" class="control-label"><spring:message code="label.EMIS_ContriProfFund"></spring:message></label></th>
										<th><label for="EMIS_Proftax" class="control-label"><spring:message code="label.EMIS_Proftax"></spring:message></label></th>
										<th><label for="EMIS_Society" class="control-label"><spring:message code="label.EMIS_Society"></spring:message></label></th>
										<th><label for="EMIS_Incometax" class="control-label"><spring:message code="label.EMIS_Incometax"></spring:message></label></th>
										<th><label for="EMIS_StaffAdv" class="control-label"><spring:message code="label.EMIS_StaffAdv"></spring:message></label>  </th>
										<th><label for="EMIS_LifeInsurnce" class="control-label"><spring:message code="label.EMIS_LifeInsurnce"></spring:message></label> </th>
										<th><label for="EMIS_GIS" class="control-label"><spring:message code="label.EMIS_GIS"></spring:message></label>          </th>
										<th><label for="EMIS_HomeAdv" class="control-label"><spring:message code="label.EMIS_HomeAdv"></spring:message></label>	</th>
										<th><label for="EMIS_VehiclIntrst" class="control-label"><spring:message code="label.EMIS_VehiclIntrst"></spring:message></label> </th>
										<th><label for="EMIS_BankLoan" class="control-label"><spring:message code="label.EMIS_BankLoan"></spring:message></label></th>
										<th><label for="EMIS_Comput" class="control-label"><spring:message code="label.EMIS_Comput"></spring:message></label>    </th>
										<th><label for="EMIS_PayAdvnc" class="control-label"><spring:message code="label.EMIS_PayAdvnc"></spring:message></label></th>
										<th><label for="EMIS_SocietyMaint" class="control-label"><spring:message code="label.EMIS_SocietyMaint"></spring:message></label></th>
										<th><label for="EMIS_Stamp" class="control-label"><spring:message code="label.EMIS_Stamp"></spring:message></label>  </th>
										<th><label for="EMIS_VehiclAllow" class="control-label"><spring:message code="label.EMIS_VehiclAllow"></spring:message></label>   </th>
										<th><label for="EMIS_OtrDeduct1" class="control-label"><spring:message code="label.EMIS_OtrDeduct1"></spring:message></label></th>
										<th><label for="EMIS_OtrDeduct2" class="control-label"><spring:message code="label.EMIS_OtrDeduct2"></spring:message></label></th>
										<th><label for="EMIS_OtrDeduct3" class="control-label"><spring:message code="label.EMIS_OtrDeduct3"></spring:message></label></th>
										<th><label for="EMIS_CPFvsDA" class="control-label"><spring:message code="label.EMIS_CPFvsDA"></spring:message></label>      </th>
										<th><label for="EMIS_totDeduct" class="control-label"><spring:message code="label.EMIS_totDeduct"></spring:message></label> </th>
<%-- 										<th><label for="EMIS_NetSal" class="control-label"><spring:message code="label.EMIS_NetSal"></spring:message></label>  </th> --%>
									</tr>
									</thead>
								</table></div>
							</div>
							<!-- ---------------------------6TAB------------------------>
							<div class="tab-pane fade" id="tabContent6">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD6_Tbl">
									<thead>
									<tr>
									<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
									<th><label for="EMIS_TrnsfrType" class="control-label"><spring:message code="label.EMIS_TrnsfrType"></spring:message></label></th>
									<th><label for="EMIS_TrnsfrOffer" class="control-label"><spring:message code="label.EMIS_TrnsfrOffer"></spring:message></label></th>
									<th><label for="EMIS_TrnsfrDate" class="control-label"><spring:message code="label.EMIS_TrnsfrDate"></spring:message></label></th>
									<th><label for="EMIS_TransfrBy" class="control-label"><spring:message code="label.EMIS_TransfrBy"></spring:message></label></th>
									<th><label for="EMIS_TransfrTo" class="control-label"><spring:message code="label.EMIS_TransfrTo"></spring:message></label></th>
									<th><label for="EMIS_EvenDate" class="control-label"><spring:message code="label.EMIS_EvenDate"></spring:message></label></th>
									<th><label for="EMIS_JoinDate" class="control-label"><spring:message code="label.EMIS_JoinDate"></spring:message></label></th>
									</tr>
									</thead>
								</table>
							</div>
							<!-- ---------------------------7TAB------------------------>
							<div class="tab-pane fade" id="tabContent7">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD7_Tbl">
									<thead>
									<tr>
									<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
									<th><label for="EMIS_TraingSub" class="control-label"><spring:message code="label.EMIS_TraingSub"></spring:message></label></th>
									<th><label for="EMIS_ReqDate" class="control-label"><spring:message code="label.EMIS_ReqDate"></spring:message></label></th>
									<th><label for="EMIS_TraingPlc" class="control-label"><spring:message code="label.EMIS_TraingPlc"></spring:message></label></th>
									<th><label for="EMIS_TraingFrmDt" class="control-label"><spring:message code="label.EMIS_TraingFrmDt"></spring:message></label></th>
									<th><label for="EMIS_TraingToDt" class="control-label"><spring:message code="label.EMIS_TraingToDt"></spring:message></label></th>
									<th><label for="EMIS_TraingInfo" class="control-label"><spring:message code="label.EMIS_TraingInfo"></spring:message></label></th>
									<th><label for="EMIS_TraingDur" class="control-label"><spring:message code="label.EMIS_TraingDur"></spring:message></label></th>
									<th><label for="EMIS_TraingMode" class="control-label"><spring:message code="label.EMIS_TraingMode"></spring:message></label></th>
<%-- 									<th><label for="EMIS_RecomEmp" class="control-label"><spring:message code="label.EMIS_RecomEmp"></spring:message></label></th> --%>
<%-- 									<th><label for="EMIS_TraingDecr" class="control-label"><spring:message code="label.EMIS_TraingDecr"></spring:message></label></th> --%>
<%-- 									<th><label for="EMIS_RecomByEmp1" class="control-label"><spring:message code="label.EMIS_RecomByEmp1"></spring:message></label></th> --%>
									<th><label for="EMIS_SancEmp" class="control-label"><spring:message code="label.EMIS_SancEmp"></spring:message></label></th>
<%-- 									<th><label for="EMIS_SancDate" class="control-label"><spring:message code="label.EMIS_SancDate"></spring:message></label></th> --%>
									<th><label for="EMIS_SancDesc" class="control-label"><spring:message code="label.EMIS_SancDesc"></spring:message></label></th>
									</tr>
									</thead>
								</table>
							</div>							
							<!-- --------------------------8TAB------------------------>
							<div class="tab-pane fade" id="tabContent8">
								<div class="col-sm-12">
								<table class="table table-striped table-bordered table-hover table-responsive" id="ServD8_Tbl">
									<thead>
									<tr>
										<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
										<th><label for="EMIS_Edu1" class="control-label"><spring:message code="label.EMIS_Edu1"></spring:message></label></th>
										<th><label for="EMIS_PassYr" class="control-label"><spring:message code="label.EMIS_PassYr"></spring:message></label></th>
										<th><label for="EMIS_Percent" class="control-label"><spring:message code="label.EMIS_Percent"></spring:message></label></th>
										<th><label for="EMIS_Division" class="control-label"><spring:message code="label.EMIS_Division"></spring:message></label></th>
										<th><label for="EMIS_Board" class="control-label"><spring:message code="label.EMIS_Board"></spring:message></label></th>
										<th><label for="EMIS_Note" class="control-label"><spring:message code="label.EMIS_Note"></spring:message></label></th>
									</tr>
									</thead>
								</table></div>
							</div>
							<!-- ---------------------------9TAB------------------------>
							<div class="tab-pane fade" id="tabContent9">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD9_Tbl">
									<thead>
									<tr>
									<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
									<th><label for="EMIS_Name" class="control-label"><spring:message code="label.EMIS_Name"></spring:message></label></th>
									<th><label for="EMIS_BOD" class="control-label"><spring:message code="label.EMIS_BOD"></spring:message></label></th>
									<th><label for="EMIS_Occup" class="control-label"><spring:message code="label.EMIS_Occup"></spring:message></label></th>
									<th><label for="EMIS_Relation" class="control-label"><spring:message code="label.EMIS_Relation"></spring:message></label> </th>
									<th><label for="EMIS_Img" class="control-label"><spring:message code="label.EMIS_Img"></spring:message></label></th>
									</tr>
									</thead>
								</table>
							</div>
							<!-- ---------------------------10TAB------------------------>
							<div class="tab-pane fade" id="tabContent10">
								<div class="col-sm-12">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD10_Tbl">
									<thead>
										<tr>
											<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
											<th><label for="EMIS_NominiName" class="control-label"><spring:message code="label.EMIS_NominiName"></spring:message></label></th>   
											<th><label for="EMIS_BOD" class="control-label"><spring:message code="label.EMIS_BOD"></spring:message></label> </th>                
											<th><label for="EMIS_Percnt" class="control-label"><spring:message code="label.EMIS_Percnt"></spring:message></label> </th>  
											<th><label for="EMIS_Relation" class="control-label"><spring:message code="label.EMIS_Relation"></spring:message></label> </th>       
											<th><label for="EMIS_Addr" class="control-label"><spring:message code="label.EMIS_Addr"></spring:message></label></th>										
										</tr>
									</thead>
								</table></div>
							</div>
							<!-- ---------------------------11TAB------------------------>
							<div class="tab-pane fade" id="tabContent11">
								<div class="col-sm-12">
								<table class="table table-striped table-bordered table-hover  table-responsive" id="ServD11_Tbl">
									<thead>
									<tr>
									<th><label for="EMIS_SrNo" class="control-label"><spring:message code="label.EMIS_SrNo"></spring:message></label></th>
									<th><label for="EMIS_WorkDate" class="control-label"><spring:message code="label.EMIS_WorkDate"></spring:message></label></th>
									<th><label for="EMIS_FrmTime" class="control-label"><spring:message code="label.EMIS_FrmTime"></spring:message></label></th>
									<th><label for="EMIS_ToTime" class="control-label"><spring:message code="label.EMIS_ToTime"></spring:message></label></th>
									<th><label for="EMIS_WorkInspect" class="control-label"><spring:message code="label.EMIS_WorkInspect"></spring:message></label></th>
									</tr>
									</thead>
								</table></div>
							</div>
						</div>					
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>